### ISSUE TITLE
Me ajuda ae ;)

### ISSUE THREAD

**Issue by iPokenWIGGLE** [FabioZumbi12/UltimateChat#10]
O vídeo mostra o que vou digitar.
https://www.youtube.com/watch?v=IQXn_kgNkT4

O remove chat não reconhece cores, ai os bracket só some quando estão brancos, porem os brancos quando alguém muda a cor da tag do clan a ultima bracket fica azul e deixa feio, eu queria deixar cinza ou todo branco, não da para usar &r reset, buga do mesmo jeito. Já tentei por no remove chat [&7], &7[&7] , &7[{clan_ctag}&7] e não adianta eles continuam no chat, tentei criando tags só para o bracket e para a cor separados ai eu colocar no tag builder clan-cor,clan-bracket más também não foi.

**Comment by FabioZumbi12** [comment]
Baixa a ultima versão no jenkins que vc pode adicionar mais de uma tag a ser removida na configuração.
http://158.69.121.149:8080/job/UltimateChat/
