### ISSUE TITLE
Message Toggle

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#101]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.5-b149

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Suggestion

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  I'm proposing a /messagetoggle (or similar command) system where players can toggle if they receive personal messages or not. For example, people tend to spam me a lot so when I don't want to be disturbed, I'd just toggle messages and people would be notified "This player has disabled their personal messages."

**Comment by FabioZumbi12** [comment]
You already can do `/chat ignore <player>`

**Comment by Coaley** [comment]
I'm aware but that's not what my suggestion is about. 
If you use /chat ignore <player> you would not see any messages from that player and would have to manually ignore every single player too. What I'm proposing is that you disable receiving personal messages for a time from all players all-together until you toggle it back on. This is very helpful for people who really don't want to be bugged by anyone for a while.

**Comment by FabioZumbi12** [comment]
Added on latest dev build. Download from our jenkins.
