### ISSUE TITLE
[Suggestion] Add Placeholders to ubroad

### ISSUE THREAD

**Issue by Lorrainrm** [FabioZumbi12/UltimateChat#103]
Ello, Fábio!

Que tal add parse nos Placeholders no /ubroad ?
Tipo /ubroad Bla bla bla hover:%rank_name% cmd:w %player% etc
Seria excelente para alguns comandos custom.

Abraço!

**Comment by Lorrainrm** [comment]
And maybe /ptell ?

**Comment by FabioZumbi12** [comment]
Added on latest dev build. Download from our jenkins.

**Comment by Lorrainrm** [comment]
ptell doesnt work and ubroad spams multiples input commands:

/ubroad test
returns
testtesttesttesttest

**Comment by FabioZumbi12** [comment]
Na build 173 ja foi corrigido isso, e o uchat nao registra /ptell

**Comment by Lorrainrm** [comment]
Ye, still same issue with 173

**Comment by FabioZumbi12** [comment]
Axo q agr ta arrumado, testa a ultima build 178.
