### ISSUE TITLE
[Discrepancy] UltimateChat disables ProjectWorlds

### ISSUE THREAD

**Issue by wolfity50** [FabioZumbi12/UltimateChat#107]
### Platform:  
Sponge

### Jar version:  
UltimateChat-1.8.6-b160-Universal.jar
  
### Minecraft version:  
1.12.2
 
### Question:  
Is it possible to use _ProjectWorlds_ and _UltimateChat_ at the same time?

### Description:  
After setting up the ProjectWorlds plugin to move between the worlds, I installed UltimateChat and after rebooting the server, I found that ProjectWorlds did not work. There are no error messages in the console. Is there any solution to this problem?

**Comment by FabioZumbi12** [comment]
If no errors i dont know what to fix or why this other plugin dont load. Try to ask for the other plugin owner.
