### ISSUE TITLE
[Suggestion] display multiple groups

### ISSUE THREAD

**Issue by QueenGambit** [FabioZumbi12/UltimateChat#108]
**What you want?:**  
I'd like to be able to have Uchat display all the groups a user is in LuckPerms for Sponge.

**Description:**  
For example, my server is going to have this system: [https://www.lucidchart.com/publicSegments/view/48fec885-63f6-4c8b-a445-7f0c10ac1842/image.jpeg](url)
Players will have 2 ranks and be in 2 groups simultaneously. One of them is associated with their total time on the server, another is for manual promotions for being good players.

**Level of importance:** Very Low
This is not important. There are alternative things I can do to get what I want. For example, I can just provide nicknames to players. I can also create a list of players and keep track of their 2nd rank. Finally, I can utilize other plugins to display a separate rank.

**Comment by FabioZumbi12** [comment]
Added on latest dev builds form our jenkins. Check the config header for new placeholder.
