### ISSUE TITLE
Problem using /ch L

### ISSUE THREAD

**Issue by KappaKiddie** [FabioZumbi12/UltimateChat#11]
https://pastebin.com/D1ePT9L5

Descrição: Mudei o alias do canal pra L  e G (maiusculos), e quando mudei pros canais, apareceu esse erro e o chat ficou do Vanilla

**Comment by FabioZumbi12** [comment]
Ja tinha arrumado isso no spigot mas não no Sponge. baixa a ultima build do jenkis q eh p funcionar!
