### ISSUE TITLE
Nucleus Mute isnt working?

### ISSUE THREAD

**Issue by Lorrainrm** [FabioZumbi12/UltimateChat#110]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  
spongeforge-1.12.2-2611-7.1.0-BETA-2990
_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  
UltimateChat-1.8.6-b156-Universal
_Your server Minecraft version_  
Minecraft version:  
1.12.2

_Issue or Suggestion?_  
What you want?:  
Nucleus mute apparently isnt working. Player can still talk
Nucleus said it might be your end issue, using 1.3.5

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
none
Description:

**Comment by FabioZumbi12** [comment]
And is. Using uchat you need to use uchat mute, not nucleus. The command is /chat mute/tempmute [player]

**Comment by Lorrainrm** [comment]
Thank you!
