### ISSUE TITLE
Sometimes messages are not visible in local chat!

### ISSUE THREAD

**Issue by JusTecYT** [FabioZumbi12/UltimateChat#115]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:   Sponge

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat 1.8.5

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  
A working solution :)

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  

Hey,
first installed plugins:

Nucleus, ProjectWorlds, LuckPerms, UniverseGuard2
Mods:
![unbenannt](https://user-images.githubusercontent.com/38291135/38626086-26872202-3dac-11e8-9c76-46197385d89a.PNG)

I have to problem that some messages in the local chat are not visible, or I could say, the local chat works not every time. I can read all messages from the player in the console. Sometimes it works, we can read all messages each other but later on it doesnt work anymore.

Do u have an idea?
Sorry for bad english and greetings from germany^^

**Comment by FabioZumbi12** [comment]
Hi,
This is an issue that i got on Sponge too and i think be an SpongeForge issue. As i already reproduced this, i dont know how to fix by uchat side.

**Comment by FabioZumbi12** [comment]
The same as #117

**Comment by XakepSDK** [comment]
@FabioZumbi12 use `getDistanceSquared` and compare with squared distance. `getDistance` uses `Math.sqrt`, square root operation may be slow. This can affect on TPS.
