### ISSUE TITLE
Command Channel Discord and jedis

### ISSUE THREAD

**Issue by blacksythe** [FabioZumbi12/UltimateChat#116]
Platform:  Sponge

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.6-b169-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12 forge 

What you want?:  When running both jedis and discord, the command channel on discord gets spammed with messages here is an example of one of them. It isnt a major issue as only anyone with the owner rank on discord can see this channel.

Description:  /tellraw dann8924 {"extra":[{"clickEvent":{"action":"run_command","value":"/ch Global"},"hoverEvent":{"action":"show_text","value":{"extra":[{"color":"dark_aqua","text":"Channel name: "},{"color":"dark_green","text":"Global\n"},{"color":"aqua","text":"Click to join this channel"}],"text":""}},"extra":[{"color":"dark_green","text":"[Global]"}],"text":""},{"hoverEvent":{"action":"show_text","value":{"extra":[{"color":"dark_aqua","text":"Rank: "},{"color":"white","text":"owner"}],"text":""}},"extra":[{"extra":[{"color":"gold","text":"\u003c"},{"color":"dark_blue","text":"O"},{"color":"dark_green","text":"w"},{"color":"dark_aqua","text":"n"},{"color":"dark_red","text":"e"},{"color":"dark_purple","text":"r"},{"color":"gold","text":"\u003e"}],"text":""}],"text":""},{"hoverEvent":{"action":"show_text","value":{"extra":[{"color":"dark_aqua","text":"Player: "},{"color":"white","text":"1zee1\n"},{"color":"dark_aqua","text":"Money: "},{"color":"gray","text":"1160"}],"text":""}},"extra":[{"text":"1zee1"}],"text":""},{"extra":[{"color":"reset","text":": "}],"text":""},{"extra":[{"text":"hi dab"}],"text":""},{"text":""},{"text":""}],"text":""}

**Comment by FabioZumbi12** [comment]
probally you is with Debug messages enabled, or some other command listeners. Uchat itself dont show this on console until in debug mode.

**Comment by blacksythe** [comment]
I will investigate this further.

**Comment by blacksythe** [comment]
No debug mode is disabled but i will do a bit more testing it may be another plugin interfering but that i would not understand as we have disabled all other plugins that interact with discord.
