### ISSUE TITLE
Local chat and Mention a player

### ISSUE THREAD

**Issue by goga133** [FabioZumbi12/UltimateChat#117]
Hello!
Plataform:   SpongeForge 1.12.2-2655-7.1.0-BETA-3025
Jar version:  Tested 1.8.3, 1.8.5 and 1.8.6
Minecraft version:  1.12.2
What you want?:  If in local.conf distance =40 - okay, else in local.conf distance more 40 (example distance = 100) Local chat dont visible.
And dont work
http://image.prntscr.com/image/0e232c4214eb4f0982dbac4c5f26a11c.jpeg

Description:  There are no problems in the console

Please fix this problem! I'll pay you, brother. And I can say that in one Russian Minecraft (minecraftonly.ru)  (Server SandBox) everything works on SpongeForge perfectly

**Comment by FabioZumbi12** [comment]
The local chat is fixed on latest dev version available on Jenkins. And mention works, the player need the mention permission to use.

**Comment by goga133** [comment]
Thanks
