### ISSUE TITLE
Bungeecord messages queuing up on empty server

### ISSUE THREAD

**Issue by danjono** [FabioZumbi12/UltimateChat#120]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform: Spigot 

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  1.8.6-b182

_Your server Minecraft version_  
Minecraft version: 1.12.2

_Issue or Suggestion?_  
What you want?:  Bungeecord messages are queuing on empty servers and not clearing.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  If messages are sent on a bungeecord channel, the messages are queued up until a player joins the server. When this happens all the messages since the last player was on are sent to the player. If too many messages are queued, the player will be force disconnected from the server for the reason "You are sending too many packets!".

**Comment by FabioZumbi12** [comment]
Fixed on https://github.com/FabioZumbi12/UltimateChat/commit/f10e8270602e724b96e9291411fe2ebc9d49844d
Try the latest dev build

**Comment by danjono** [comment]
Issue resolved in 1.8.6-b183
