### ISSUE TITLE
[Bug] [Prefix] Bug com prefixes [Gravíssimo]

### ISSUE THREAD

**Issue by galoti** [FabioZumbi12/UltimateChat#122]
_Sponge versão 7.1 build 2990

_Ultimate Chat 1.8.5-b151-Universal

_Versão do minecraft 1.12.2  

- Após fazer os grupos,  configurar prefixes e weights e separá-los em tracks no Luck perms, apenas 1 prefix aparece corretamente no chat. Fiz 3 tracks e configurei no Luck para aparecer no chat 3 prefixes ao mesmo tempo (opção highest_on_track_<nomedatrack> ).  Vou colocar aqui algumas imagens para ajudar a explicar o que está acontecendo.

![Como deveria aparecer](https://i.imgur.com/uYbJMiQ.png)

   Deveria aparecer do jeito que está na imagem acima no campo prefix, porém aparece desse jeito aqui:

![Como aparece](https://i.imgur.com/CwPS6XZ.png)

** O prefix treinador está correto, no lugar do prefix membro deveria estar ajudante (membro é o primeiro da track) e a prefix de dono nem aparece.**CAMPEÃO** é uma custom-tag feita no uchat, não faz parte do problema.

   Com o chat do nucleus aparece certo:

![No nucleus](https://i.imgur.com/48VLgDQ.png)

**Comment by FabioZumbi12** [comment]
O Uchat só mostra uma tag por vez. Não posso ajudar com a configuração de tags junto com o LuckPerms justamente por depender do LuckPerms. Infelizmente se ainda não conseguir fazer funcionar usa o chat do Nucleus mesmo.

**Comment by FabioZumbi12** [comment]
E vc ta usando uma versão desatualizada. Vc nao tenttou a do link que tava aqui no template pra baixar as versões dev? https://host.areaz12server.net.br:8080/job/RedProtect/

**Comment by FabioZumbi12** [comment]
E vc ta usando uma versão desatualizada. Vc não tentou a versão que ta no link daqui do template de issues? https://host.areaz12server.net.br:8080/job/UltimateChat/

**Comment by galoti** [comment]
Eu testei com builds mais recentes e também não aparece. O chat do Nucleus é muito simples, não da pra mudar pra ele só por isso. Vou tentar substituir usando custom-tags, mas seria interessante o suporte a opção highest_on_track_ do LuckPerms já que ele é praticamento o plugin de perms padrão do Sponge.

**Comment by FabioZumbi12** [comment]
Adicionada opção para mostrar mais prefixes ao mesmo tempo. Baixa a ultima versão e ve as placeholders novas.
