### ISSUE TITLE
Sugestão

### ISSUE THREAD

**Issue by zMaily** [FabioZumbi12/UltimateChat#123]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.5-b151-Universal

_Your server Minecraft version_  
Minecraft version: 1.8

_Issue or Suggestion?_  
What you want?: Adicionar config para definir um certo tempo(em segundos) entre cada envio de qualquer mensagem enviada por cada jogador e acrescentar uma permissão para ignorar esse tempo.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Por exemplo, se eu definir um tempo entre mensagens para 15 segundos no canal global e eu não tiver a permissão de ignorar, apenas poderei enviar mensagem a cada 15 segundos, ou seja, só posso usar o chat a cada 15 segundos. Enviei uma mensagem ai serei impedida de usar o chat por 15 segundos e a cada tentativa de enviar mensagens, o plugin informará quantos segundos faltam para que eu possa usar o chat para enviar outra mensagem.
Um gif mostrando como seria: https://prnt.sc/jiw14i (O tempo é independente para cada jogador)
(Lembrando que não é um atraso de mensagens, apenas impedirá o jogador de usar do canal para envio de mensagens no tempo definido na config)

**Comment by FabioZumbi12** [comment]
Não vou adicionar por agora, mas o uchat tem PAI caso algum dev quira fazer.
