### ISSUE TITLE
Problemas de Cores na Config

### ISSUE THREAD

**Issue by Mark154872** [FabioZumbi12/UltimateChat#125]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:   UltimateChat-1.8.6-b189-Universal

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Esta dando problema na hora de usar cores na config, ja tentei por &r porem nao funciona

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  https://i.imgur.com/DZ8dvlr.png

**Comment by FabioZumbi12** [comment]
Não encontrei a solução pra esse problema ainda.

**Comment by FabioZumbi12** [comment]
Vc ja achou a solução em contato no discord. A solução eu ja tinha mencionado, que segundo vc, ja tinha tentado, de usar &f no inicio da linha (ta no discord).
