### ISSUE TITLE
Erro ao habilitar chat-protection.antispam.enabled em protections.yml

### ISSUE THREAD

**Issue by Metalflame12** [FabioZumbi12/UltimateChat#127]
**Plataform:**  Paper 1.12.2

**Jar version:**  UltimateChat-1.8.6-b${BUILD_NUMBER}-Universal.jar _(Não sei por que o BUILD_NUMBER ficou assim... Não fiz nenhuma alteração, só baixei o .zip, extrai, abri com o IntelliJ e rodei o install.)_

**Minecraft version:**  1.12.2

**What you want?:**  O problema ocorre quando o jogador manda alguma mensagem no canal global enquanto a opção chat-protection.antispam.enabled em protections.yml está habilitada. 
Não ocorre com o UltimateChat-1.8.5-b151-Universal.jar.

**Description:** Console logs https://hastebin.com/jumahaxibu.vbs

**Comment by FabioZumbi12** [comment]
Não precisa compilar no seu intellij, só baixar a ultima build do jenkins que ta aqui na home do github. 
Baixa essa versão do jenkins e tenta denovo com o numero da build correta.

**Comment by Metalflame12** [comment]
Certo, baixei a versão UltimateChat-1.8.6-b192-Universal.jar e o erro existe nela... 
https://hastebin.com/oluyotujoz.vbs

Antes de testar criei um servidor usando o paperclip-1472.jar só com o UltimateChat.


E pra acessar o jenkins tive que usar uma vpn, quando tento entrar sem ela usando o Firefox da esse erro: https://prnt.sc/k0ocwa
E no Google Chrome da esse:  https://prnt.sc/k0odw3

Obrigado
