### ISSUE TITLE
Could not pass event PlayerJoinEvent to UltimateChat v1.8.6

### ISSUE THREAD

**Issue by GethelpObv** [FabioZumbi12/UltimateChat#128]
Plataform: Spigot/PaperSpigot

Jar version:
UltimateChat-1.8.6-b189-Universal
UltimateChat-1.8.5-b151-Universal

Minecraft version:  Tested it on the Versions below
spigot-1.12.2-R0.1-SNAPSHOT-b1638  
PaperSpigot-1.12.2
PaperSpigot-1.8.8

Other Plugins: 
SavageFactions v1.6.9.5-U0.2.1-RC-1.4-BETA-2

Some logfiles i tested it on a lot of versions

Server PaperSpigot-1.12.2 clint 1.8.9
https://hastebin.com/raw/isiholeqig

Server PaperSpigot-1.12.2 client 1.12.2
https://hastebin.com/raw/sulabucaye

Server spigot-1.12.2-R0.1-SNAPSHOT-b1638 client 1.12.2
https://hastebin.com/raw/uguloviyuj

Server PaperSpigot-1.8.8 client 1.8.9
https://hastebin.com/raw/macagimenu

**Comment by FabioZumbi12** [comment]
`Caused by: java.lang.ClassNotFoundException: com.massivecraft.factions.RelationParticipator`

You need to use the latest Factions plugin wheres support relation placeholders (not factionsUUID, as is not from original owner, its just a fork)

**Comment by GethelpObv** [comment]
can you add support to use factionsUUID?

**Comment by FabioZumbi12** [comment]
Try the latest dve build. probally this problem was avoided!

**Comment by GethelpObv** [comment]
Tryed the latest dev build and it still happens add more logs for you

UltimateChat-1.8.6-b192-Universal
https://hastebin.com/raw/epujipises
