### ISSUE TITLE
JSON não está funcionando no chat

### ISSUE THREAD

**Issue by Eufranio** [FabioZumbi12/UltimateChat#13]
Não testei no Sponge, mas no Thermos (1.7.10, bukkit/spigot) as funções JSON não estão funcionando. Texto clicável, hover message, etc, não estão funcionando no chat, o texto aparece limpo (tudo normal, cores, etc)

**Comment by FabioZumbi12** [comment]
1.7 nao tem suporte a Json no chat, so a partir do 1.8.

**Comment by Eufranio** [comment]
Well, alguns plugins usam o próprio `/tellraw` como o ChatReaction (que funciona na 1.7)...

**Comment by evernife** [comment]
Alguma chance de ser implementado?

**Comment by Eufranio** [comment]
Já foi

**Comment by evernife** [comment]
Interesting ✌️
