### ISSUE TITLE
uChat+Luckperm=?

### ISSUE THREAD

**Issue by vnvyvu** [FabioZumbi12/UltimateChat#132]
I added LuckPerm's placeholder prefix, but when it comes to chatting it's showing up

  % luckperm_prefix%

I modified save the permissions file as YAML file

(I downloaded papi, reload carefully, vault-info also received LuckPerm)

**Comment by FabioZumbi12** [comment]
You totally is not using the issue template and title...

Use the latest version available on template issue and on this github home page (1.8.6) and try again.

About luckperms, use the placeholders available on config header. You dont need papi to get LuckPerms tags. read the wiki too for more info and join on our discord.
