### ISSUE TITLE
BungeeCoord No effect

### ISSUE THREAD

**Issue by juzhijian** [FabioZumbi12/UltimateChat#134]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  spongevanilla-1.12.2-7.1.0-BETA-71.jar

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.6-b192-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Use Waterfall Non communication ，bungee=true in global.conf

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:

**Comment by FabioZumbi12** [comment]
For now, theres no bungee support for sponge servers, only bukkit/spigot.
