### ISSUE TITLE
Channel Tag Help

### ISSUE THREAD

**Issue by Piqori** [FabioZumbi12/UltimateChat#135]
Platform:  Sponge

Jar version:  UltimateChat-1.7.1-b22.jar

Minecraft version: 1.12.2

What you want?:  I'm not quite sure how to add channel tags. I've read the whole Wiki and am still confused.

Description:  I'm not sure if this is the right place, but any help would be appreciated!

**Comment by vnvyvu** [comment]
Update latest version in discord !

**Comment by vnvyvu** [comment]
The channel tag is the placeholder
