### ISSUE TITLE
Unable to completely disable all chat protections.

### ISSUE THREAD

**Issue by Deathinflames** [FabioZumbi12/UltimateChat#137]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot 

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.6-b192-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  

After a thorough investigation we have come to the conclusion that it is currently not possible to completely disable ALL of uChat's protections. It appears that either anti-flood or anti-spam will not allow the sending of messages that contain a single character in length. When a single character message, ie: "Player: ." or "Player: t" is sent to a global channel the plugin denies the action and does not specify a reason as to why the action was blocked. We've ensured that no wildcards are used in the permissions group and have tried both allocating each individual permission node the plugin has according to the plugin.yml as well as full operator status.

We would really appreciate it if this issue could be investigated further. Thank you for all of the work that has gone into this plugin, we all appreciate it very much! :D

P.S. This is our current protections.yml: https://pastebin.com/raw/jDiKXJBa

**Comment by FabioZumbi12** [comment]
The problem still?
