### ISSUE TITLE
Config reloads After Restart

### ISSUE THREAD

**Issue by LOLcraft2212** [FabioZumbi12/UltimateChat#138]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform: spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.5-b151-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  every time I restart the server config loads to the defualt config so I have to place the Old one in and reload the chat

**Comment by DutchUser** [comment]
Post ur config / lastest log.

**Comment by LOLcraft2212** [comment]
[here](https://hastebin.com/orixurulew.pl)

**Comment by DutchUser** [comment]
Here is his startup log: https://pastebin.com/2w2YFvcq

**Comment by FabioZumbi12** [comment]
Really after all, you still using 1.8.5?

**Comment by LOLcraft2212** [comment]
That's the newest version?

**Comment by DutchUser** [comment]
Fair point, on spigot it is the last version.

**Comment by LOLcraft2212** [comment]
What is the latest version then?
