### ISSUE TITLE
 Permission to join the chat

### ISSUE THREAD

**Issue by srMylles** [FabioZumbi12/UltimateChat#143]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:   Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.5-b151-Universal

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  you could allow permission for the player to get into a chat type

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  you could allow permission for the player to get into a chat type

**Comment by FabioZumbi12** [comment]
Update to latest version like is described up here. And check for channel permissions on permissions pages on our wiki.
