### ISSUE TITLE
@hand incompatibility with MythicDrops

### ISSUE THREAD

**Issue by Blackyvk** [FabioZumbi12/UltimateChat#145]
Platform: **Spigot**

Jar version:   **UltimateChat-Spigot-1.8.6**

Minecraft version:   **1.12.2**

What you want?:  **Issue**

Description:  

@ hand doesnt work with Items with custom lore from MythicDrops, they show an invalid item, plugins like  [Auctions](https://github.com/sainttx/Auctions/) does show the item pretty well, is it possible to fix it to  with uchat? 
Thanks!

**Comment by FabioZumbi12** [comment]
Fixed on latest version: https://host.areaz12server.net.br:8080/job/UltimateChat/
