### ISSUE TITLE
Suggestion: Command to add words to filter in game

### ISSUE THREAD

**Issue by PokeSaga** [FabioZumbi12/UltimateChat#147]
Been a common problem, when choosing not to use the "partial words" option that you need a new words often. This can be a struggle considering the shear amount of creative words players use to get past the filter.

Would be a great addition to add a simple command to add new words to the filter.

**Comment by FabioZumbi12** [comment]
I think is not necessary. Since the same people who have perms to add this word, have perms to modify the files. Too much work too for this little thing.

**Comment by FabioZumbi12** [comment]
Will be added on next dev builds
