### ISSUE TITLE
[Issue] Integration with mcclans chat

### ISSUE THREAD

**Issue by maximcs1** [FabioZumbi12/UltimateChat#148]
Platform: spongeforge-1.12.2-2705-7.1.0-BETA-3342
Jar version: UltimateChat-1.8.6-b192-Universal
Minecraft version:  1.12.2

Description:  The mcclans plugin has its own clan chat.
Activating this channel with a command "/cc"
But the message from mcclans is shown that the channel has changed, but we are writing to the channel from the UltimateChat (local channel for example).

**Comment by FabioZumbi12** [comment]
MCClans need to cancel the chat event to do not allow other plugins to send the message.

**Comment by maximcs1** [comment]
how i can cancelled chat event Ultimate chat from mcclans?

**Comment by FabioZumbi12** [comment]
I dont know the mcclans code, but the dev probally know how, try to ask him.
