### ISSUE TITLE
O sistema de menção não esta funcionando.

### ISSUE THREAD

**Issue by vinicsantos** [FabioZumbi12/UltimateChat#149]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.5-b151-Universal

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue(Erro)

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  Eae Fabio, tudo bom? Estou com um problema ao mencionar um player no chat, simplesmente não acontece nada
Config: https://hastebin.com/hikogozali.coffeescript
Print http://prntscr.com/kchepy
Estou configurando o plugin em um servidor de testes, caso queira entrar o IP é o seguinte: advancedcraft.virtus.host (1.12.2).
Discord: https://discord.gg/mTJU74P
Espero que tu possa me ajudar vei, vlw ae 
ViniiCarvalhoo

**Comment by FabioZumbi12** [comment]
Provavelmente permissão. Ve a seção de permissões na wiki ou se da erros no console.
