### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by EduBRz** [FabioZumbi12/UltimateChat#150]
06.08 16:44:42 [Server] INFO org.bukkit.command.CommandException: Cannot execute command 'channel' in plugin UltimateChat v1.8.5 - plugin is disabled.
06.08 16:44:42 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:36) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at org.bukkit.craftbukkit.v1_13_R1.CraftServer.dispatchCommand(CraftServer.java:693) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.handleCommand(PlayerConnection.java:1634) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnection.a(PlayerConnection.java:1469) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.PlayerConnectionUtils.a(SourceFile:10) ~[spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_181]
06.08 16:44:42 [Server] INFO at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_181]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.SystemUtils.a(SourceFile:198) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.w(MinecraftServer.java:884) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.DedicatedServer.w(DedicatedServer.java:411) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.v(MinecraftServer.java:819) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at net.minecraft.server.v1_13_R1.MinecraftServer.run(MinecraftServer.java:717) [spigot-1.13.jar:git-Spigot-69774b3-ec2095d]
06.08 16:44:42 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_181]

**Comment by FabioZumbi12** [comment]
Nenhuma informação a mais, so o log? Ok... Atualiza p última versao!

**Comment by EduBRz** [comment]
Obrigado Fabio depois que atualizei resolveu aqui!
