### ISSUE TITLE
Discord Issues with  emojis and a Suggestion

### ISSUE THREAD

**Issue by Blackyvk** [FabioZumbi12/UltimateChat#152]
Platform: **Spigot**

Jar version:   **UltimateChat-Spigot-1.8.6**

Minecraft version:   **1.12.2**

What you want?:  **Issue and Suggestion**

Description:  

This happens when players send server emojis from discord to mc
![imagen](https://user-images.githubusercontent.com/9063912/44306955-71bd7200-a367-11e8-9fb4-5fd40578e0fd.png)

Any way to disable this? disabling external emojis from roles doesn't work for this

Also, there should be a character limit to avoid wall of texts and spam

**Comment by rouing** [comment]
Hmm, this does pose an issue.
It is also funny because in game, you can do <#channelID> or <@userID> and it will tag them/the channel. 

Maybe use a regex function to filter things that use <: > <# > <@ >

**Comment by Blackyvk** [comment]
And where and how do I add custom regex  in uchat ?

what about a character limit? if the message is too long, just sent part of it

**Comment by rouing** [comment]
I was talking in terms of a Developer Perspective. You cannot add regex, but maybe we could add a regex function inside the code to deal with these issues.

**Comment by FabioZumbi12** [comment]
Fixed/added filter on latest dev build.
