### ISSUE TITLE
JDA not loading

### ISSUE THREAD

**Issue by xrhyno2x** [FabioZumbi12/UltimateChat#154]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.8-b196-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.7.10

_Issue or Suggestion?_  
What you want?:  problem with loading the JDA for the 1.7.10 server

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  https://hastebin.com/usuyahidej.rb

**Comment by FabioZumbi12** [comment]
The problem is your cauldron ASM version where some versions come with an old version. Probally because the java version too. Search for cauldron or 1.7.10 asm version to look for a solution.
