### ISSUE TITLE
AsyncPlayerChatEvent

### ISSUE THREAD

**Issue by SevenX159** [FabioZumbi12/UltimateChat#155]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.8-b196-Universal

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  
I was running Uchat for 2 days, full configured, no problem.
Now i added a new channel, and it broke the plugins, i try deleting the folder, still have to error, try delete folder + .jar redownload it and reinstall it and still have the problem, i don"t know what to do now

https://pastebin.com/nbPVFUK9

**Comment by FabioZumbi12** [comment]
Its clear the cause is that other plugin called ChatManager.
