### ISSUE TITLE
AsyncPlayerChatEvent (again)

### ISSUE THREAD

**Issue by SevenX159** [FabioZumbi12/UltimateChat#156]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.8-b196-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  
After Deleting Chat Manager, i still have the second part avec the error

https://pastebin.com/fzwsnvvW

**Comment by FabioZumbi12** [comment]
You have wrong configurations set in your tags section. Check for blanks tags or set to the default configuration and setup again.

**Comment by SevenX159** [comment]
Humm, after a few test, the problem get corrected when i turn off Vault ( https://ci.md-5.net/job/Vault/ this one )

**Comment by SevenX159** [comment]
That's what i have in console when posting a message, https://pastebin.com/EKiACCKR
Problem is corrected if i delete Vault, but obviously i can't, Someone can help ?

**Comment by FabioZumbi12** [comment]
Using what version of vault? Try to update to latest!
