### ISSUE TITLE
Bungeecord: Discord Bot total players

### ISSUE THREAD

**Issue by Blackyvk** [FabioZumbi12/UltimateChat#158]
Jar version:  UltimateChat-1.8.6-b192-Universal.jar 

Minecraft version:  1.12.2version Bungeecord 1355

What you want?:   Suggestion

Description:  The discord Bot when used on a bungeecord environment, the online player count only works for 1 of the servers, if it detects bungeecord it should count the total players of the proxy, not just spigot side I think

**Comment by FabioZumbi12** [comment]
I ll not add, sorry
