### ISSUE TITLE
Tell between Bungeecord users.

### ISSUE THREAD

**Issue by bundabrg** [FabioZumbi12/UltimateChat#159]
# Tags
Platform: Bungeecord + PaperMC
Jar version:  UltimateChat-1.8.7-b195-Universal.jar
Minecraft version:  1.13

# Suggestion
It would be great if the tell channel can span servers. So a user on one backend server can tell to another user on another server, via the Bungeecord proxy.

Unless I'm missing an obvious config item that will allow me to do this.

**Comment by FabioZumbi12** [comment]
You already can do this n a bungee conection, but the nickname need to match exact as is.

**Comment by Blackyvk** [comment]
I tried to use the exact name/nick and It didnt work, my channels work in bungee except private messages using UltimateChat-1.8.8-b200-Universal

**Comment by bundabrg** [comment]
I can't remember why I originally opened this since it seems to work fine for me. In fact, if I type just the first few letters it also works fine.

I'm presently running UltimateChat-1.8.7-b195-Universal.jar on my Bungee and then on each of my backend servers, all running 1.13.2 PaperMC.

**Comment by Blackyvk** [comment]
can you share your config? I have everything setup but I always fail to send msg to another server...

**Comment by bundabrg** [comment]
I've shared them at:
https://drive.google.com/open?id=1RxtflJTgh_9gnRnyamIcSCS8O2u8iRXs

**Comment by Blackyvk** [comment]
I dont know man... @FabioZumbi12 

I have tried everything, /msg CorrectName  case sensitive....  same result 

![imagen](https://user-images.githubusercontent.com/9063912/51082552-659fcb80-16df-11e9-8b14-4684601ff361.png)


Configuration with very basic plugins, default configurations on everything

![imagen](https://user-images.githubusercontent.com/9063912/51082461-b44c6600-16dd-11e9-849f-1eee4f53bacc.png)

Bungee only has UltimateChat-1.8.8-b202-Universal.jar

It doesnt work.... unless there is some hidden configuration that I dont know, then it's broken, public channels work perfectly on bungee, except tells...
