### ISSUE TITLE
Chat Channels

### ISSUE THREAD

**Issue by Pearlyglow** [FabioZumbi12/UltimateChat#16]
I created more chat channels by copying and pasting the global.yml in the channels file. I modified it according to the chat, unfortunately the plugin keeps issuing this message '<name> is an invalid channel or doesn't exist'. Please help me out.

**Comment by FabioZumbi12** [comment]
Fixed? If not, try the latest builds: http://areaz12server.net.br:8080/job/UltimateChat/
