### ISSUE TITLE
Suporte do placeholder {ch-color} em mensagens.

### ISSUE THREAD

**Issue by DevNatan** [FabioZumbi12/UltimateChat#162]
Platform: Spigot
Jar version:  UltimateChat-1.8.7-b195-Universal.jar
Minecraft version:  1.8
What you want?:  Suggestion
Description:  

Adicionar suporte ao placeholder `{ch-color}` em mensagens, tornando a mensagem da mesma cor do canal.
Eu tentei usar
```yaml
message:
  format: '{ch-color}{message}'
```

Mas...
http://prntscr.com/ldq810

**Comment by FabioZumbi12** [comment]
A tag {messages} é especial apenas para mensagens e as placeholders não vão funcionar nela (a não ser que habilite na config, mas os players vão poder escrever tags no chat tambem). Voce tem que por a placeholder da cor do canal dentro de uma tag antes da tag de mensagens.

Deve ficar igual na print:
![image](https://user-images.githubusercontent.com/5833818/47941893-c1bfc580-dece-11e8-86e6-1307007f59e6.png)
