### ISSUE TITLE
Players stealing other players tags

### ISSUE THREAD

**Issue by Aureom** [FabioZumbi12/UltimateChat#163]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: **PaperSpigot**

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.8-b196-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.8.8 using viaversion.

_Issue or Suggestion?_  
What you want?:  **Issue**

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  There is no error in console, but when two players chat at the same time one of the two player "steal" the tags from the other player https://i.imgur.com/LEzafDv.png

**Comment by Aureom** [comment]
Again, https://i.imgur.com/ofN0ZFl.jpg

**Comment by FabioZumbi12** [comment]
Still using latest dev build verisons?

**Comment by Aureom** [comment]
Bom, vou reabrir o pull request pois eu estou voltando com o meu servidor de Minecraft e sim, o bug continua, testei agora mesmo.

Continuo utilizando o **PaperSpigot** e o UltimateChat está na ultima versão (1.9.0-b245)

Como pode ver abaixo, o jogador TequilAxBr está com a tag [GG] e o Aureom com a tag [Fight] (Ambas são adicionadas no mesmo listener)
![img_bug](https://i.imgur.com/GLsWxOT.png)

O codigo: 
```Java
	@EventHandler
	private void onChat(SendChannelMessageEvent event) {
		if(event.getSender() instanceof Player) {
			Player player = (Player) event.getSender();
			Tag tag = plugin.getTagManager().getPlayerTag(player).getInUse();
			if(tag != null) {
				event.addTag("{customtags}", tag.getTag());
			}
		}
	}
```

Como está na config:
```
  customtags:
    format: '{customtags} '
```
