### ISSUE TITLE
Failed connection with redis

### ISSUE THREAD

**Issue by HeberonYT** [FabioZumbi12/UltimateChat#166]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Thermos Build 58 (bukkit-spigot-thermos)

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.8-b202-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.7.10

_Issue or Suggestion?_  
What you want?:  

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  I have a problem using this plugin in the version of minecraft 1.7.10 with thermos.
The problem is that you can not connect to redis, always mark an error in the connection data.
I must clarify that this plugin works without problems when I use spongeForge 1.12.2
https://pastebin.com/raw/rTmW7BpR

![screenshot_3](https://user-images.githubusercontent.com/13698597/49262407-f65e6880-f40b-11e8-8e7d-7abba4885547.png)

**Comment by FabioZumbi12** [comment]
I will add support for bungeecoord on sponge too and remove redis!
