### ISSUE TITLE
2 Suggestions and 2 Issues - Ignore, @'s in-game and discord, Channel Cool-downs, in-game tags

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#167]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version: UltimateChat-1.8.8-b202-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Issues & Suggestions

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  
- **Issue: Chat Ignore** I cannot issue the command /chat ignore. Every time it tells me "You cannot ignore that player/channel". I tested this with my players who do not have Operator (or the '*' permission) and they can ignore successfully. It would appear this is only an issue for Operators and therefore Admins/Owners.
- **Issue: Discord tags** Whenever someone or a group is tagged (@) on discord, it's displayed like that user tagged themselves. (Example: On discord http://prntscr.com/lpcc76 | In-game: http://prntscr.com/lp7v99)
- **Suggestion: Channel Cool-down** The option to set a cooldown in certain channels, so allow players to send a message per x amount of seconds. In my case, for example, I have an /ad channel which allows players to make advertisements/announcements, and I'd love if I could add a cooldown to it too.
- **Suggestion/Issue: @ in-game** When someone mentions another player in-game, all text after is by default reset. I changed this in the config file to this:
` color-template: '&3&l{mentioned-player}&r{ch-color}`
But that didn't work as you can see here: http://prntscr.com/lpcdre That channel is usually light green but for some reason {ch-color} is blue. I'd like to set it up so the chat color doesn't change when someone gets mentioned, they just get their name bolded.

Thanks!

**Comment by FabioZumbi12** [comment]
Issue: Chat Ignore> Theres a permission to do not ignore people. "*" permissions will have this perm (if you want people to ignore OPs, remove * or this perm).

Issue: Discord tags> Fixed on latest dev build

Suggestion: Channel Cool-down> Not for now

Suggestion/Issue: @ in-game> I dont know what can be because works fine on my server. try to add a " " (blank space) like this: `color-template: '&3&l{mentioned-player} &r{ch-color}`
