### ISSUE TITLE
When I create new channels, nobody hears them

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#168]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform:

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  

_Your server Minecraft version_  
Minecraft version:  

_Issue or Suggestion?_  
What you want?:  

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:

**Comment by FabioZumbi12** [comment]
> Put if is the Spigot or Sponge version.
> Platform:
> 
> Inform your UltimateChat jar name like UltimateChat-Spigot-7.0.3.jar.
> Jar version:
> 
> Your server Minecraft version
> Minecraft version:
> 
> Issue or Suggestion?
> What you want?:
> 
> Describe your issue/Suggestion. If issue, use the site hastebin.com to put your error or console logs.
> Description:
Complete all fields please!

Btw, you need to give channels perms to your players be allowed to hear new channels. See here: https://github.com/FabioZumbi12/UltimateChat/wiki/(2)-Permissions#channels

**Comment by Kichiro72** [comment]
Filled
