### ISSUE TITLE
When I create new channels, nobody hears them

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#169]
Put if is the Spigot or Sponge version.
Platform: Spigot

Inform your UltimateChat jar name like UltimateChat-Spigot-7.0.3.jar.
Jar version: UltimateChat-1.8.8-b202-Universal.jar

Your server Minecraft version
Minecraft version: 1.12.2

Issue or Suggestion?
What you want?: Fix this problem

Describe your issue/Suggestion. If issue, use the site hastebin.com to put your error or console logs.
Description: If I create a new channel, then no one hears it. When sending messages, there are two answers that there are no players nearby who can hear you and in this world there are no players who can hear you.

**Comment by FabioZumbi12** [comment]
You need to learn to read the entire messages... as i sayd on your previous Issue with same theme:

> Btw, you need to give channels perms to your players be allowed to hear new channels. See here: https://github.com/FabioZumbi12/UltimateChat/wiki/(2)-Permissions#channels

This is not an issue!
