### ISSUE TITLE
ChannelAlias command

### ISSUE THREAD

**Issue by Sognus** [FabioZumbi12/UltimateChat#17]
I have been trying to configure Global channel to be able to run /g <message>. Without success I tried to use configuration that you have described [here](https://ore.spongepowered.org/FabioZumbi12/UltimateChat)

I also tried logging all commands, looks like commands from ChannelAlias were sent but not in format that was excepected. Looks like "Text" was inserted to command and command iself was enclosed with brackets {} 

**Commands I have used:**
/channel global
/g hello

**Expected result:**
Global/PlayerName: Hello

**Result i got:**
Global/PlayerName: Text

**Command logged for "/g hello":**
/g Text{hello}

**Versions**
uChat: 1.7.1-b30
spongeforge-1.10.2-2281-5.2.0-BETA-2274

**Comment by FabioZumbi12** [comment]
Try the latest builds: http://areaz12server.net.br:8080/job/UltimateChat/

**Comment by linkinkov** [comment]
@FabioZumbi12 can you add ability to use !text for global channel?
