### ISSUE TITLE
Chat Cooldown Suggestion

### ISSUE THREAD

**Issue by MattPuffin** [FabioZumbi12/UltimateChat#171]
_Issue or Suggestion?_  
What you want?: Suggestion :)  

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description:  
Suggestion! I think it would be awesome to have a cooldown on chat channels, for example if a player joins a channel and then doesnt talk for 60 seconds, they get sent to another channel.
I have a channel on my bungee network to talk across servers and players always forget to go back to the server chat, and end up having conversations with their friends but broadcasting it to the whole network!

**Comment by FabioZumbi12** [comment]
Hum... i need to create some cooldowns for each players... some resources where we dont need to alocate.
