### ISSUE TITLE
Discord Integration Not Sending Player Messages

### ISSUE THREAD

**Issue by Coolkc456** [FabioZumbi12/UltimateChat#173]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Sponge

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version: UltimateChat-1.8.8-b202-Universal.jar

_Your server Minecraft version_  
Minecraft version: 1.12.2-2705-7.1.0-BETA-3436

_Issue or Suggestion?_  
What you want?: Issue

_Describe your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._
Description: I am using Ultimate Chat as a requirement for PokeTeams team chat but UltimateChat is conflicting with MagiBridge that I used to stream my server's chat to Discord and vice versa. I'm willing to switch to UltimateChat since it has Discord integration but so far I can only get it to broadcast player start and stop messages and player join/leave messages. If I say "test" in the server chat, it doesn't show up in the Discord channel. Here is my Ultimate Chat configuration: https://pastebin.com/QqtvpERx

**Comment by FabioZumbi12** [comment]
Setup discord channels on uchat channel file.

**Comment by Coolkc456** [comment]
Where is that located?

**Comment by FabioZumbi12** [comment]
In the channels folder inside uchat folder.
