### ISSUE TITLE
Cant seem to get the discord bot online.

### ISSUE THREAD

**Issue by kaimokene** [FabioZumbi12/UltimateChat#175]
Platform:
Paper-513 (Fork of spigot)

Jar version:  
UltimateChat-1.8.8-b202-Universal (The currently latest one from dev builds)

Minecraft version:  
1.13.2
 
What you want?:  
I cant seem to get the discord bot online. Even though im 99% sure everything is correct since  stuff like DiscordSRV worked fine. Decided to change from discordsrv to this since it still sent "filtered" messages.

Configs.
https://prnt.sc/mh0fup
https://prnt.sc/mgv9a4

**Comment by FabioZumbi12** [comment]
Installed the jda from dev builds page too?

**Comment by kaimokene** [comment]
Oh sorry didnt notice that i needed that since most of other discord related plugins seemed to have it built in.

**Comment by FabioZumbi12** [comment]
The size of jda its too big comparated with the uchat jar, this why is alone.
