### ISSUE TITLE
getItemHand Issue

### ISSUE THREAD

**Issue by Wilost0rm** [FabioZumbi12/UltimateChat#177]
Platform: Sponge
 
Jar version:  UltimateChat-1.8.8-b202-Universal.jar

Minecraft version:  1.12.2
  
What you want?:  Can't send messages in-game, console error appears.

Description:  Running a new Stoneblock 2 1.4 server. Using FTBserver-1.12.2-14.23.5.2808-universal.jar with Sponge spongeforge-1.12.2-2768-7.1.5.jar. 

Currently have a network setup without issues running all with FTBserver-1.12.2-14.23.5.2796-universal.jar and spongeforge-1.12.2-2768-7.1.5.jar and have zero issues on the other 3 servers.

The plugin loads and everything works except when a player tries to send a message at all in-game. Messages from other servers show up, and console can use /l or /g to talk but still not players.

Have tried adjusting sponge versions, uchat versions, and forge versions, can't lower forge due to mods dependencies.

We are using SpongeBootstrap-0.6.2 to force sponge to load in.

ERROR:
https://hastebin.com/ejujotobuw.rb

**Comment by FabioZumbi12** [comment]
Fixed on latest version. download from ou jenkins!
