### ISSUE TITLE
Problems (crash) with an increase in the length of the string when using @hand

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#179]
Platform: Spigot

Jar version:  UltimateChat-1.8.8-b202-Universal.jar

Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  somehow solve this problem. In extreme cases, limit the string

Description:  I use RPG items plugin (QuantumRPG), which have a long description (in the items hints), apparently using the "@hand" json string is too long and this causes global kick players from the server

error in console: [00:51:32] [Netty Server IO #1/ERROR]: io.netty.handler.codec.EncoderException: String too big (was 33220 bytes encoded, max 32767)

after which everyone kicks from the server

**Comment by FabioZumbi12** [comment]
The full log?

**Comment by Kichiro72** [comment]
I will not find the full log, only if it happens again. But there are no other mistakes.
I noticed that not only this is due to the long lore. For example, if a player wrote "See what kind of helmet I have: @hand", then everyone is kicked because of this error, and if he just writes "@hand" with the same item, then the item will seem

**Comment by FabioZumbi12** [comment]
I just need to know wheres the exact issue is happening to add a try/cacth to do not crash the server, this way will not crash the server.

**Comment by Kichiro72** [comment]
This log has this error, it is very big, since the server worked for a long time
https://dropmefiles.com/Lv6xT

**Comment by FabioZumbi12** [comment]
Teste the lastest dev buils please!
What i doing checking if will drop the error, and if yes, will show the item without lore, only the item!

**Comment by Kichiro72** [comment]
here is a clean log, with this error with the last build of the chat. Again thrown out after I wrote in the chat "See what a cool item I have @hand"

https://pastebin.com/EF333nYC

**Comment by FabioZumbi12** [comment]
Turn debug on and try again please?

**Comment by Kichiro72** [comment]
done https://pastebin.com/S1Wfsat9

**Comment by Kichiro72** [comment]
debug profile https://pastebin.com/cZ07Tnvi

**Comment by Kichiro72** [comment]
what about this problem?

**Comment by FabioZumbi12** [comment]
On the latest dev build i've aded a filter for this. The lore will be removed if larger than accepted value.

**Comment by Kichiro72** [comment]
Thanks! but in recent months I have not encountered this problem again
