### ISSUE TITLE
Cannot create dependency on API, uChat pom dependent on bukkit plugins???

### ISSUE THREAD

**Issue by Dockter** [FabioZumbi12/UltimateChat#180]
Hello,

I created a dependency on Sponge-7.0-8.0-1.8.6 in a project (Almura), using these instructions:
https://github.com/FabioZumbi12/UltimateChat/wiki/(7)-UChat-API,  I use gradle for my project.

I then attempted to compile my code and got this error?
https://gist.githubusercontent.com/Dockter/f67deb173e0ff4db0459d4be3bc805eb/raw/892f998d3f6cdf141f80f64185872b38dfc71c0a/gistfile1.txt

Why is a SpongePlugin API dependency looking at bukkit plugins.  Please advise.

**Comment by FabioZumbi12** [comment]
I need to update the api and upload th latest s. That error probally is caused by some other plugin where is not located on that repo. I will check.

**Comment by Dockter** [comment]
I appreciate your fast response.

**Comment by Dockter** [comment]
Any thoughts on when this might get done?  We are attempting to roll out an update that depends on uChat's API but can't because it won't compile due to the dependency failures.

**Comment by Dockter** [comment]
@FabioZumbi12 I see that you pushed this: https://github.com/FabioZumbi12/UltimateChat/commit/08d849c1c9e0ef6f8cd7d4c5b8f5b817ce7c19d6

It doesn't appear that a API 1.8.8 is available though from here:  https://github.com/FabioZumbi12/UltimateChat/tree/mvn-repo/br/net/fabiozumbi12/UltimateChat

Please advise.

**Comment by Dockter** [comment]
@FabioZumbi12 Seen the commits from today.  Thank you.
