### ISSUE TITLE
[BUG] possivel conflito com /tell

### ISSUE THREAD

**Issue by Breevz** [FabioZumbi12/UltimateChat#186]
**Descreva o bug**
/tell não funciona, digitando /tell nick msg aparece a mensagem do uchat help

**Reproduzir**
Etapas para reproduzir o comportamento:
1. digite /tell nick msg
2. veja o erro

**Comportamento esperado**
o comando deveria funciona enviando uma mensagem [Player1 > eu: mensagem]

**Capturas de tela e registros**
tell com player normal
http://prntscr.com/naub9h
Chat de OP
http://prntscr.com/naubgq
Tell de OP
http://prntscr.com/naubkw
plugins do servidor
http://prntscr.com/naubqi

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor:  Spigot 1.13.2
 - Versão do plug-in: UltimateChat-1.8.9-b217-Universal.jar

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by FabioZumbi12** [comment]
Parece que ta faltando o alias do tell na config ou o tell ta desativado.

Ve na configuração, na seção e se puder cola como que ta aqui.

**Comment by Breevz** [comment]
tell:
  cmd-aliases: 't,w,m,msg,private,priv,r'
  prefix: '&6[&c{playername} &6-> &c{receivername}&6]: '
  format: '{message}'
  hover-messages: []

Seria isso?

**Comment by FabioZumbi12** [comment]
Sim, fiz varios testes aqui e não consegui reproduzir esse problema... ve se tem mais pls de chat ai e se o tell ta desabilitado no essentials (não precisa, mas ja que ta dando conflito...)

**Comment by Breevz** [comment]
consegui "arrumar"  usando os cmds desse alias "cmd-aliases: 't,w,m,msg,private,priv,r'", mas o ultimate chat é o único plugin de chat instalado, talvez tenha dado conflito com o essentialschat que eu instalei de começo mas desinstalei antes de instalar o ultimatechat

**Comment by FabioZumbi12** [comment]
Ha ele da conflito com essentialschat msm, mas boa que conseguiu arrumar.
