### ISSUE TITLE
[Suggestion] Better Discord sync roles behavior

### ISSUE THREAD

**Issue by NyannyWu** [FabioZumbi12/UltimateChat#189]
**Is your feature request related to a problem? Please describe.**
I think the discord sync feature could be great if some ranks could be kept.

**Describe the solution you'd like**

Temporal role: Should work like the plugin is right now, when you change your group in game, all others in this list are removed from your discord account.

Permanent role: if you reach a ingame group that has this role, you should never lose this role in discord no matter what (unless is removed by a discord admin).

Persistant roles until removed: these roles are only shown if you are in this group in game, isnt removed by a temporal role change.

Bug: If you unlink your discord account you keep your discord roles.

**Comment by FabioZumbi12** [comment]
All of this thing you can setup using permissions, setting temp role perms or a definitive perm. I've fixed the bug to remove all non member roles when leaving a role/permission.

The of unlink its because the plugin cant know the player id anymore...because is unlinked.
