### ISSUE TITLE
My custom tags don't work for non-OP's.

### ISSUE THREAD

**Issue by Erallie** [FabioZumbi12/UltimateChat#190]
So, my custom tags work for OP's, but not for non-OP's. I figured there was a permission for this, but I couldn't find the right one. I assumed it was the "magic" permission, but that doesn't seem to be right. my custom tags include the colors, because I want each channel to have different colors, but when someone joins my server who's not an OP, it doesn't work for them. I set the colors and font style permissions for the default player, but I'm guessing that it's because I included the colors in custom tags that it didn't work. How do I make this work?

**Comment by FabioZumbi12** [comment]
The tested and working permissions plugins is LuckPerms and PermissionsEx, i dont know if works with other perms plugin (as i see on discord, you is using PermissionsBukkit).

We cant help further with configurations, we aim our focuses on bugs and problems. Thry using default configurations, making a backup of UChat folder and let create a new one (where it works fine in all cases).
