### ISSUE TITLE
[BUG] Players can't talk in chat channels

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#192]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.
**Describe the bug**

Hi. I recently got the most recent plugin version- I'm using UltimateChat-1.8.9-b218. This has happened twice on two separate occasions I believe where players couldn't talk in any chat channels and would be stuck in private messages. When they try to talk, it it says “cannot send chat message”.

**Comment by FabioZumbi12** [comment]
I've added some code to prevent this, btw, players can lock the private message with other player just using `/t <playername>` and unlick using the same commands or just `/t`.

Try the latest dve build.
