### ISSUE TITLE
[BUG] Discord @ in in-game chat

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#193]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**

Hi. I opened up a similar ticket before and you said you fixed the issue where when someone or a group would be pinged (@) on discord, in chat it would be displayed as the message sender is tagging themselves. Not it just displays as @? or @null 
![image](https://user-images.githubusercontent.com/35243560/56852731-15134d80-691f-11e9-90e6-e1c0b4e5aee8.png)

What the above should be is @Administrator

**Comment by FabioZumbi12** [comment]
Please, try the latest dev build.
