### ISSUE TITLE
Getting stuck in /msg when you accidentally do /msg (name) *enter* without text[BUG] 

### ISSUE THREAD

**Issue by RSnidder** [FabioZumbi12/UltimateChat#194]
**Describe the bug**
So when someone does /msg (name) and forgets to enter a text and accidentally presses enter its gets him stuck in the /msg of that person and if they try /ch g it still doesn't fix it. Not even trying multiple other /ch works. The only way to talk is to do /msg (name). If you want to change the person you want to /msg you again need to /msg (name2) *enter* without text and then type. Trying to type in global automatically makes it a /msg to the latest person. 

**Server and plugins versions (please complete the following information):**
 - Server: sponge 7.0.1
 - Plugin Version: 1.8.8

**Additional context**
It has happened to many people on the server I play it usually fixes after some time but sometimes it might take days

**Comment by FabioZumbi12** [comment]
This is not a bug, its a function where you can lock private with other player. You just need to use the same command to unlock, or just `/msg` to unlock.
