### ISSUE TITLE
nullpointer after enabling perms for discord sync

### ISSUE THREAD

**Issue by nacjm** [FabioZumbi12/UltimateChat#196]
got a nullpoiner after doing a reload after enabling require perms on discord sync
running sponge 1.12.2-2768-7.1.6-RC3616
forge 2820
mc: 1.12
br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: java.lang.NullPointerException
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at br.net.fabiozumbi12.UltimateChat.Sponge.discord.UCDiscordSync.<init>(UCDiscordSync.java:72)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at br.net.fabiozumbi12.UltimateChat.Sponge.UChat.registerJDA(UChat.java:331)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at br.net.fabiozumbi12.UltimateChat.Sponge.UChat.reload(UChat.java:301)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands.lambda$uchat$11(UCCommands.java:640)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:340)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:334)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:1083)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:960)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:939)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:193)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.network.PacketThreadUtil$1.redirect$onProcessPacket$zlj000(SourceFile:539)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at java.util.concurrent.FutureTask.run(Unknown Source)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.util.Util.func_181617_a(SourceFile:46)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:301)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.server.MinecraftServer.redirect$onRun$zjn000(MinecraftServer.java:3955)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
[br.net.fabiozumbi12.UltimateChat.Sponge.UCCommands:lambda$uchat$11:643]: at java.lang.Thread.run(Unknown Source)

**Comment by FabioZumbi12** [comment]
The latest dev build should fix ;)
