### ISSUE TITLE
[Suggestion] Log chat messages to file

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#198]
An option to log chat messages to a log file, that is possibly rotated every week/month would be very nice

**Comment by Shmeeb** [comment]
Actually I see Nucleus already does this, but they create a new log every reboot, which is less preferable for searching purposes. Not sure if you'd still want to do it.

**Comment by FabioZumbi12** [comment]
This will load the server time/lag and thw work the server will use to send a message, and we have nucleus and servers logs for this.
