### ISSUE TITLE
[BUG] Quick Chat in Channel (no need to focus) not working

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#199]
**Version**
1.8.9.-b222

**Description**
When players try to send a quick message to another channel they aren't focused on (e.g. someone is in Global but does _/local hello_), they just get the UChat Help menu.
This worked normally in 1.8.9.-b219

P.S. `need-focus: false` is in all chat channels.

**Comment by FabioZumbi12** [comment]
A bug. Fixed on latest dev build.
