### ISSUE TITLE
Não sei se posso perguntar isso aqui mas ...

### ISSUE THREAD

**Issue by iPokenWIGGLE** [FabioZumbi12/UltimateChat#2]
Como que coloca a tag do clan entre [ ] eu não consigo personalizar ele nem com o uchat nem direto do simples clan , ele só fica do lado da tag do canal .

http://prntscr.com/bfntru

Desde já , VLW ..

**Comment by iPokenWIGGLE** [comment]
SimpleClans -
safe-civilians: false
tag:
  default-color: '8'
  max-length: 5
  bracket:
    color: '8'
    leader-color: '4'
    left: ']'
    right: '['
  min-length: 2
  separator:
    color: '8'
    leader-color: '4'
    char: '['
settings:
  online-mode: true
  disable-messages: false
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  mchat-integration: true
  enable-auto-groups: false
  chat-compatibility-mode: true
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: true
  display-chat-tags: true
  unrivable-clans:
  - admin
  - staff
  - mod
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - vip
  - clan
  language: en
  disallowed-tag-colors:
  - '4'
  server-name: '&4SimpleClans'
  new-clan-verification-required: true
  allow-regroup-command: true
spout:
  in-game-tags: true
  alert-url: ''
  default-cape-url: http://i.imgur.com/pjqV6.png
  enable-clan-capes: true
  in-game-tags-colored: false
commands:
  more: more
  ally: ally
  clan: clan
  accept: accept
  deny: deny
  global: global
  force-priority: true
economy:
  creation-price: 100.0
  purchase-clan-create: false
  verification-price: 1000.0
  purchase-clan-verify: false
  invite-price: 20.0
  purchase-clan-invite: false
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
clan:
  homebase-teleport-wait-secs: 10
  homebase-can-be-set-only-once: true
  min-size-to-set-rival: 3
  max-length: 25
  max-members: 25
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  ff-on-by-default: false
  min-length: 2
  min-size-to-set-ally: 3
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 100
clanchat:
  rank:
    color: e
  tag-based-clan-chat: false
  name-color: e
  player-bracket:
    left: <
    right: '>'
  announcement-color: e
  message-color: b
  tag-bracket:
    color: e
    left: '['
    right: ']'
  enable: true
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
allychat:
  tag-color: b
  name-color: f
  player-bracket:
    left: <
    right: '>'
  message-color: '3'
  tag-bracket:
    color: '8'
    left: '['
    right: ']'
  enable: true
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 2
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  use-threads: false
  use-bungeecord: false

uChat -
# Arquivo de configuração do Uchat
# Autor: FabioZumbi12
# Recomando usar o Notepad++ para editar este arquivo!
# ------------------------------------------------------------------------
# Tags é onde voce vai personalizar os textos pra aparecer no chat, ao passar o mouse ou clicar na tag.
# Para adicionar uma tag, copie uma existente e troque o nome para um de sua escolha.
# Depois de criar e personalizar a tag, adicione ela em 'general > default-tag-builder'.
# ------------------------------------------------------------------------
# Replacers disponíveis:
# uChat:
#  - {default-format-full}: Use esta tag para ver todas tags de plugins que estão usando o formato padrão do bukkit. Normalmente usado por plugins de 'mito' e tags temporárias. Caso queira apenas usar uma delas elas são separadas por espaços e abaixo vc pode usar apenas uma de cada.
#  - {default-format-0}: Use esta tag para usar apenas uma tag das descritas acima. O numero é a posição dela entre os espaços;
#  - {world}: O mundo de quem enviou a mensagem;
#  - {message}: Mensagem enviada;
#  - {playername}: O nome de quem enviou;
#  - {nickname}: O nick de quem enviou. Se o nick não foi definido irá mostrar o nome;
#  - {ch-name}: Nome do canal;
#  - {ch-alias}: Atalho do canal;
#  - {ch-color}: Cor do canal;
# Vault:
#  - {group-prefix}: Prefixo do grupo do player;
#  - {group-suffix}: Sufixo do grupo do player;
#  - {balance}: Dinheiro do player;
#  - {prim-group}: Tag do grupo primário;
#  - {player-groups}: Lista todos grupos que o player faz parte;
# Simpleclans:
#  - {clan-tag}: Tag do Clan sem cores;
#  - {clan-ctag}: Tag do Clan com cores;
#  - {clan-name}: Nome do Clan;
#  - {clan-kdr}: KDR do player do Clan;
#  - {clan-isleader}: O player é lider;
#  - {clan-rank}: Rank do player no Clan;
#  - {clan-totalkdr}: Clan KDR (não do player);
# Marry Plugins:
#  - {marry-partner}: Mostra o nome do(a) parceiro(a);
#  - {marry-prefix}: Pega a tag de prefixo, normalmente o coração;
#  - {marry-suffix}: Pega a tag de sufixo, ou simbolo masculino do Marriage Reloaded;

config-version: 1.1
debug-messages: false
language: PT-BR
mention:
  enable: true
  prefix-color: '&e@'
  playsound: note_pling
  hover-message: '&e&l{playername} &7mencionou você!'
general:
  console-tag: '&6 {console}&3'
  remove-from-chat: '[]'
  channel-cmd-aliases: channel,ch
  hover-events: true
  default-channel: G
  custom-formats: []
  use-channel-tag-builder: false
  spy-format: '&c&o[Spy] {output}'
  default-tag-builder: marry-tag,ch-tags,clan-tag,group-prefix,nickname,message
tell:
  cmd-aliases: tell,t,w,m,msg,private,priv,r
  prefix: '&7&l[&2{playername} &7-> &2{receivername}&7&l]&7: '
  format: '{message}'
  hover-messages: []
tags:
  group-prefix:
    format: '{group-prefix}'
    click-cmd: ''
    hover-messages:
    - '&bRank : &e{prim-group}'
  playername:
    format: '{playername}'
    click-cmd: tpa {playername}
    hover-messages:
    - '&bAperte para pedir teleporte'
  nickname:
    format: '{nickname}&r'
    click-cmd: ''
    hover-messages:
    - '&bNome : &e{playername}'
    - '&3Este indivíduo possui &e{balance} Pilas &3!'
  group-suffix:
    format: '&r{group-suffix}'
    click-cmd: ''
    hover-messages: []
  world:
    format: '&7[{world}]&r'
    click-cmd: ''
    hover-messages:
    - '&7Sent from world {world}'
  message:
    format: ' : {message}'
    click-cmd: ''
    hover-messages: []
  ch-tags:
    format: '&f&l[&2{ch-alias}&f&l]&r '
    click-cmd: ch {ch-alias}
    hover-messages:
    - '&bNome do Chat : &e{ch-name}'
    - '&3Aperte para entrar no chat!'
  clan-tag:
    format: '[{clan-ctag}]'
    click-cmd: clan search {playername}
    hover-messages:
    - '&bClan Tag: &7{clan-tag}'
    - '&bClan Name: &7{clan-name}'
    - '&bClan KDR: &7{clan-totalkdr}'
    - '&bPlayer KDR: &7{clan-kdr}'
    - '&bPlayer Rank: &7{clan-rank}'
    - '&bIs Leader: &7{clan-isleader}'
    - '&3Aperte para ver mais'
  marry-tag:
    format: '{marry-prefix}{marry-suffix}'
    click-cmd: ''
    hover-messages:
    - '&cMarried with {marry-partner}'
  admin-chat:
    format: '&b[&r{playername}&b] '
    click-cmd: ''
    hover-messages: []

**Comment by iPokenWIGGLE** [comment]
# Arquivo de configuração do Uchat
# Autor: FabioZumbi12
# Recomando usar o Notepad++ para editar este arquivo!
# ------------------------------------------------------------------------
# Tags é onde voce vai personalizar os textos pra aparecer no chat, ao passar o mouse ou clicar na tag.
# Para adicionar uma tag, copie uma existente e troque o nome para um de sua escolha.
# Depois de criar e personalizar a tag, adicione ela em 'general > default-tag-builder'.
# ------------------------------------------------------------------------
# Replacers disponíveis:
# uChat:
#  - {default-format-full}: Use esta tag para ver todas tags de plugins que estão usando o formato padrão do bukkit. Normalmente usado por plugins de 'mito' e tags temporárias. Caso queira apenas usar uma delas elas são separadas por espaços e abaixo vc pode usar apenas uma de cada.
#  - {default-format-0}: Use esta tag para usar apenas uma tag das descritas acima. O numero é a posição dela entre os espaços;
#  - {world}: O mundo de quem enviou a mensagem;
#  - {message}: Mensagem enviada;
#  - {playername}: O nome de quem enviou;
#  - {nickname}: O nick de quem enviou. Se o nick não foi definido irá mostrar o nome;
#  - {ch-name}: Nome do canal;
#  - {ch-alias}: Atalho do canal;
#  - {ch-color}: Cor do canal;
# Vault:
#  - {group-prefix}: Prefixo do grupo do player;
#  - {group-suffix}: Sufixo do grupo do player;
#  - {balance}: Dinheiro do player;
#  - {prim-group}: Tag do grupo primário;
#  - {player-groups}: Lista todos grupos que o player faz parte;
# Simpleclans:
#  - {clan-tag}: Tag do Clan sem cores;
#  - {clan-ctag}: Tag do Clan com cores;
#  - {clan-name}: Nome do Clan;
#  - {clan-kdr}: KDR do player do Clan;
#  - {clan-isleader}: O player é lider;
#  - {clan-rank}: Rank do player no Clan;
#  - {clan-totalkdr}: Clan KDR (não do player);
# Marry Plugins:
#  - {marry-partner}: Mostra o nome do(a) parceiro(a);
#  - {marry-prefix}: Pega a tag de prefixo, normalmente o coração;
#  - {marry-suffix}: Pega a tag de sufixo, ou simbolo masculino do Marriage Reloaded;

config-version: 1.1
debug-messages: false
language: PT-BR
mention:
  enable: true
  prefix-color: '&e@'
  playsound: note_pling
  hover-message: '&e&l{playername} &7mencionou você!'
general:
  console-tag: '&6 {console}&3'
  remove-from-chat: '[]'
  channel-cmd-aliases: channel,ch
  hover-events: true
  default-channel: G
  custom-formats: []
  use-channel-tag-builder: false
  spy-format: '&c&o[Spy] {output}'
  default-tag-builder: marry-tag,ch-tags,clan-tag,group-prefix,nickname,message
tell:
  cmd-aliases: tell,t,w,m,msg,private,priv,r
  prefix: '&7&l[&2{playername} &7-> &2{receivername}&7&l]&7: '
  format: '{message}'
  hover-messages: []
tags:
  group-prefix:
    format: '{group-prefix}'
    click-cmd: ''
    hover-messages:
    - '&bRank : &e{prim-group}'
  playername:
    format: '{playername}'
    click-cmd: tpa {playername}
    hover-messages:
    - '&bAperte para pedir teleporte'
  nickname:
    format: '{nickname}&r'
    click-cmd: ''
    hover-messages:
    - '&bNome : &e{playername}'
    - '&3Este indivíduo possui &e{balance} Pilas &3!'
  group-suffix:
    format: '&r{group-suffix}'
    click-cmd: ''
    hover-messages: []
  world:
    format: '&7[{world}]&r'
    click-cmd: ''
    hover-messages:
    - '&7Sent from world {world}'
  message:
    format: ' : {message}'
    click-cmd: ''
    hover-messages: []
  ch-tags:
    format: '&f&l[&2{ch-alias}&f&l]&r '
    click-cmd: ch {ch-alias}
    hover-messages:
    - '&bNome do Chat : &e{ch-name}'
    - '&3Aperte para entrar no chat!'
  clan-tag:
    format: '[{clan-ctag}]'
    click-cmd: clan search {playername}
    hover-messages:
    - '&bClan Tag: &7{clan-tag}'
    - '&bClan Name: &7{clan-name}'
    - '&bClan KDR: &7{clan-totalkdr}'
    - '&bPlayer KDR: &7{clan-kdr}'
    - '&bPlayer Rank: &7{clan-rank}'
    - '&bIs Leader: &7{clan-isleader}'
    - '&3Aperte para ver mais'
  marry-tag:
    format: '{marry-prefix}{marry-suffix}'
    click-cmd: ''
    hover-messages:
    - '&cMarried with {marry-partner}'
  admin-chat:
    format: '&b[&r{playername}&b] '
    click-cmd: ''
    hover-messages: []

**Comment by iPokenWIGGLE** [comment]
SimpleClans -
safe-civilians: false
tag:
  default-color: '8'
  max-length: 5
  bracket:
    color: '8'
    leader-color: '4'
    left: ']'
    right: '['
  min-length: 2
  separator:
    color: '8'
    leader-color: '4'
    char: '['
settings:
  online-mode: true
  disable-messages: false
  tameable-mobs-sharing: false
  teleport-blocks: false
  teleport-home-on-spawn: false
  drop-items-on-clan-home: false
  keep-items-on-clan-home: false
  item-list: []
  show-debug-info: false
  mchat-integration: true
  enable-auto-groups: false
  chat-compatibility-mode: true
  rival-limit-percent: 50
  use-colorcode-from-prefix-for-name: true
  display-chat-tags: true
  unrivable-clans:
  - admin
  - staff
  - mod
  show-unverified-on-list: false
  blacklisted-worlds: []
  banned-players: []
  disallowed-tags:
  - vip
  - clan
  language: en
  disallowed-tag-colors:
  - '4'
  server-name: '&4SimpleClans'
  new-clan-verification-required: true
  allow-regroup-command: true
spout:
  in-game-tags: true
  alert-url: ''
  default-cape-url: http://i.imgur.com/pjqV6.png
  enable-clan-capes: true
  in-game-tags-colored: false
commands:
  more: more
  ally: ally
  clan: clan
  accept: accept
  deny: deny
  global: global
  force-priority: true
economy:
  creation-price: 100.0
  purchase-clan-create: false
  verification-price: 1000.0
  purchase-clan-verify: false
  invite-price: 20.0
  purchase-clan-invite: false
  home-teleport-price: 5.0
  purchase-home-teleport: false
  home-teleport-set-price: 5.0
  purchase-home-teleport-set: false
  money-per-kill: false
  money-per-kill-kdr-multipier: 10
kill-weights:
  rival: 2.0
  civilian: 0.0
  neutral: 1.0
clan:
  homebase-teleport-wait-secs: 10
  homebase-can-be-set-only-once: true
  min-size-to-set-rival: 3
  max-length: 25
  max-members: 25
  confirmation-for-promote: false
  trust-members-by-default: false
  confirmation-for-demote: false
  ff-on-by-default: false
  min-length: 2
  min-size-to-set-ally: 3
page:
  untrusted-color: '8'
  clan-name-color: b
  subtitle-color: '7'
  headings-color: '8'
  trusted-color: f
  leader-color: '4'
  separator: '-'
  size: 100
clanchat:
  rank:
    color: e
  tag-based-clan-chat: false
  name-color: e
  player-bracket:
    left: <
    right: '>'
  announcement-color: e
  message-color: b
  tag-bracket:
    color: e
    left: '['
    right: ']'
  enable: true
request:
  message-color: b
  ask-frequency-secs: 60
  max-asks-per-request: 1440
bb:
  color: e
  accent-color: '8'
  show-on-login: true
  size: 6
allychat:
  tag-color: b
  name-color: f
  player-bracket:
    left: <
    right: '>'
  message-color: '3'
  tag-bracket:
    color: '8'
    left: '['
    right: ']'
  enable: true
purge:
  inactive-player-data-days: 30
  inactive-clan-days: 7
  unverified-clan-days: 2
mysql:
  username: ''
  host: localhost
  port: 3306
  enable: false
  password: ''
  database: ''
permissions:
  auto-group-groupname: true
  YourClanNameHere:
  - test.permission
performance:
  use-threads: false
  use-bungeecord: false

uChat -
config-version: 1.1
debug-messages: false
language: PT-BR
mention:
  enable: true
  prefix-color: '&e@'
  playsound: note_pling
  hover-message: '&e&l{playername} &7mencionou você!'
general:
  console-tag: '&6 {console}&3'
  remove-from-chat: '[]'
  channel-cmd-aliases: channel,ch
  hover-events: true
  default-channel: G
  custom-formats: []
  use-channel-tag-builder: false
  spy-format: '&c&o[Spy] {output}'
  default-tag-builder: marry-tag,ch-tags,clan-tag,group-prefix,nickname,message
tell:
  cmd-aliases: tell,t,w,m,msg,private,priv,r
  prefix: '&7&l[&2{playername} &7-> &2{receivername}&7&l]&7: '
  format: '{message}'
  hover-messages: []
tags:
  group-prefix:
    format: '{group-prefix}'
    click-cmd: ''
    hover-messages:
    - '&bRank : &e{prim-group}'
  playername:
    format: '{playername}'
    click-cmd: tpa {playername}
    hover-messages:
    - '&bAperte para pedir teleporte'
  nickname:
    format: '{nickname}&r'
    click-cmd: ''
    hover-messages:
    - '&bNome : &e{playername}'
    - '&3Este indivíduo possui &e{balance} Pilas &3!'
  group-suffix:
    format: '&r{group-suffix}'
    click-cmd: ''
    hover-messages: []
  world:
    format: '&7[{world}]&r'
    click-cmd: ''
    hover-messages:
    - '&7Sent from world {world}'
  message:
    format: ' : {message}'
    click-cmd: ''
    hover-messages: []
  ch-tags:
    format: '&f&l[&2{ch-alias}&f&l]&r '
    click-cmd: ch {ch-alias}
    hover-messages:
    - '&bNome do Chat : &e{ch-name}'
    - '&3Aperte para entrar no chat!'
  clan-tag:
    format: '[{clan-ctag}]'
    click-cmd: clan search {playername}
    hover-messages:
    - '&bClan Tag: &7{clan-tag}'
    - '&bClan Name: &7{clan-name}'
    - '&bClan KDR: &7{clan-totalkdr}'
    - '&bPlayer KDR: &7{clan-kdr}'
    - '&bPlayer Rank: &7{clan-rank}'
    - '&bIs Leader: &7{clan-isleader}'
    - '&3Aperte para ver mais'
  marry-tag:
    format: '{marry-prefix}{marry-suffix}'
    click-cmd: ''
    hover-messages:
    - '&cMarried with {marry-partner}'
  admin-chat:
    format: '&b[&r{playername}&b] '
    click-cmd: ''
    hover-messages: []

**Comment by FabioZumbi12** [comment]
Só por os colchetes no uchat ja resolveria: 
http://prntscr.com/bfny1z
http://prntscr.com/bfnyag

**Comment by iPokenWIGGLE** [comment]
Vlw , malz por te incomodar , eu fiz tudo de novo , apaguei todo o resto deixei só o essentials/uchat/simpleclans e deu certo , agora vou modelando , vlw .

**Comment by FabioZumbi12** [comment]
Blz ^^
