### ISSUE TITLE
[BUG]  /chat ignore doesnt work at all

### ISSUE THREAD

**Issue by NyannyWu** [FabioZumbi12/UltimateChat#201]
**Describe the bug**
/chat ignore or /ignore doesn't work at all

**To Reproduce**
1. chat ignore name/channel

**Expected behavior**
It should ignore the player or channel...

**Screenshots and LOGs**
![image](https://user-images.githubusercontent.com/49493026/57578316-edac9c80-7457-11e9-962a-6d43fbfd2634.png)

**Server and plugins versions (please complete the following information):**
- Server: Spigot 1.13.2
- Plugin Version: UltimateChat-1.8.9-b224-Universal.jar
- Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
This message only appears if the player has the permissions to deny ignore like `uchat.cant-ignore.(player)` or if the player is OP. Players without this perm can be ignored!

**Comment by NyannyWu** [comment]
OH wait, I retested again, because my players complain about it, the issue relies on bungeecord channels, if you ignore someone you can still read them on any bungee channel, range and private messages work fine
