### ISSUE TITLE
[BUG] Using Uppercase letters on color codes denies the chat for that user

### ISSUE THREAD

**Issue by Blackyvk** [FabioZumbi12/UltimateChat#204]
**Describe the bug**
Player can't chat if his nick has colorcodes with uppercase letters.

**To Reproduce**
1. /nickname &DN&fa&dr&fw&f&dh&fa&dl
2. try to chat
3. Error.

**Screenshots and LOGs**
https://gist.github.com/Blackyvk/8f243658373973f2ac3e77f893b6d95f

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.13.2
 - Plugin Version: UltimateChat-1.8.9-b224-Universal
 - Java Version:  Java 1.8]

**Comment by FabioZumbi12** [comment]
This is a known issue from paper: https://github.com/PaperMC/Paper/issues/1734
