### ISSUE TITLE
[BUG] PAPI variables in chat

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#205]
Users are able to use PlaceholderAPI variables in PM & chat messages like so: 

https://i.imgur.com/OLt44mQ.png

A good fix for this would be to simply require a permission

**Comment by FabioZumbi12** [comment]
Theres an option config to disable placeholders on messages

**Comment by Shmeeb** [comment]
Using`UltimateChat-1.8.9-b229-Universal`

    # Enable to allow parse tags and placeholders on messages.
    enable-tags-on-messages=false

PAPI messages are still parsed

**Comment by Shmeeb** [comment]
@FabioZumbi12 still happens, could you re-open this?
