### ISSUE TITLE
[BUG] UCDInterface not found when calling uChat.get().getUCJDA()

### ISSUE THREAD

**Issue by Dockter** [FabioZumbi12/UltimateChat#208]
**Describe the bug**
I am getting an "interface not found" error.
Error Link:  https://gist.github.com/Dockter/417b4eccfd4e1876b811d31b1b84d258

My Code:
Code Link: https://github.com/AlmuraDev/Almura/blob/api-7/src/main/java/com/almuradev/almura/shared/util/UchatUtil.java#L16

**Server and plugins versions (please complete the following information):**
 - Server: Sponge: [spongeforge-1.12.2-2838-7.1.7-RC3814]
 - Plugin Version: [UltimateChat-1.8.9-b224-Universal]
 - Java Version: [Java 1.8]

I can't understand why the server doesn't have the interface that getUCJDA() is calling.

**Comment by FabioZumbi12** [comment]
Did you added the UltimatechatJDA.jar?

**Comment by Dockter** [comment]
Yes of course.

**Comment by Dockter** [comment]
I went back to the 1.8.8 version of uChat and it works fine?  Any idea why the same code won't work with the 1.8.9 versions?

**Comment by Dockter** [comment]
Please disregard.  I think this is happening because of something in my environment with how we compile against specific builds.
