### ISSUE TITLE
DiscordIntegration compatibility

### ISSUE THREAD

**Issue by kaal-1** [FabioZumbi12/UltimateChat#21]
When using DiscordIntegration, all messages are sent to discord, regardless of if it is global, local, staff, or even tell chat. I found out that the only case where it is not, is when you use a command. For example:

/g message - Not sent
message (in global chat) - Sent
/l message - Not sent
message (in local chat) - Sent
/tell user message - Not sent
message (with locked /tell user) - Sent

I opened an issue in DiscordIntegration thinking it would be simple to fix on their side, but apparently a fix is needed on both the mod and plugin.

https://github.com/Chikachi/DiscordIntegration/issues/45#event-1128147351

**Comment by FabioZumbi12** [comment]
Checkout the latest dev build. Now all commands fire the chat event to allow plug-ins and mods listen to: http://areaz12server.net.br:8080/job/UltimateChat/
