### ISSUE TITLE
[BUG] SavageFactions breaks the plugin

### ISSUE THREAD

**Issue by proximageuse** [FabioZumbi12/UltimateChat#210]
**Describe the bug**
With SavageFactions installed, interacting with UltimateChat in any way that causes it to parse placeholders throws an error in console .

**To Reproduce**
1. Install SavageFactions along with UltimateChat
2. Interact with UltimateChat in a way that causes it to parse placeholders.

**Expected behavior**
Either the hook with MassiveCore Factions be disabled when someone has SavageFactions installed, or a working hook with SavageFactions

**Screenshots and LOGs**
When I join the game: https://gist.github.com/proximageuse/f460e3c56f76cc68ddd188c957573884
When I say something in chat: https://gist.github.com/proximageuse/1f912c5126b7a31be128d1ca633a4e68

**Server and plugins versions (please complete the following information):**
 - Server: Paper 123 (1.14.3)
 - UltimateChat Version: UltimateChat-1.8.9-b224-Universal.jar
 - SavageFactions Version: 2.2 BETA, as far as I can tell, but the jar is named "Factions-2.0.jar".
 - Java Version: OpenJDK 1.8.0

**Additional context**
This issue is not very urgent, as I was able to remove the hook and make a custom build for my own use.

**Comment by FabioZumbi12** [comment]
UChat hooks with the legacy version of MassiveCore, not with that one modified.

**Comment by proximageuse** [comment]
Yes, I know that. Is it possible to in some way have compatibility with SavageFactions? Even if it's just an option in the config to disable the legacy MassiveCore hook, I would greatly appreciate it.

**Comment by FabioZumbi12** [comment]
Try the latest dev build. https://github.com/FabioZumbi12/UltimateChat/commit/cefa998883997933ef11ef4a472a7ed9b305cd83 should fix this!
