### ISSUE TITLE
[Suggestion] possibility to enable/disable the use of @hand in certain channels

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#211]
**Is your feature request related to a problem? Please describe.**

I wanted to implement a trading chat, so that only @hand could be used in it, but players use @hand in other channels

**Describe the solution you'd like**

possibility to assign channels in which you can use @hand would be very useful

**Describe alternatives you've considered**

-

**Additional context**

-

**Comment by FabioZumbi12** [comment]
Added on latest release. Look for this option on channel config file.
