### ISSUE TITLE
[BUG] 'listener.invalidplayer' message received after every PM

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#214]
https://gyazo.com/acae9510249b25e44bf2c78214de1d39
When sending a PM to another user, I get the `listener.invalidplayer` msg even tho the PM went thru just fine

Sponge versions: https://gyazo.com/bcbb56d9ba375c20b96cee31e14541da
Running UltimateChat-1.8.9-b226-Universal

I assume adding an else here would fix the issue? https://gyazo.com/5c776a9f94f5cffeb7c74e6cdcdda686

**Comment by FabioZumbi12** [comment]
Yep, should fix, thanks!

Try the latest dev build from our discord (not jenkins)

**Comment by Shmeeb** [comment]
Fixed it, tyvm
