### ISSUE TITLE
[BUG] Erro ao dar /chat reload

### ISSUE THREAD

**Issue by SrBedrock** [FabioZumbi12/UltimateChat#216]
**Descrição do BUG**
O plugin apresenta erros ao ser recarregado.

**Reprodução do BUG**
Etapas para reproduzir o comportamento:
1. Execute o comando /chat reload

**Comportamento esperado**
O plugin recarregar sem erro no console ou in-game

**Capturas de tela e registros**
Registro do console: https://hasteb.in/epixihef.md
Registro in-gme: 
![image](https://user-images.githubusercontent.com/51332006/61240778-6100b200-a718-11e9-933e-7b1f6b99ecb2.png)

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Paper version git-Paper-131 (MC: 1.14.3)
 - Versão do plug-in: UltimateChat-1.8.9-b228-Universal.jar
 - Versão do Java: 1.8

**Comment by FabioZumbi12** [comment]
Testa a ultima dev build do discord.

**Comment by SrBedrock** [comment]
Problema resolvido utilizando a última build b228 do Jenkins!
