### ISSUE TITLE
[Sugestão] Definir cor no chat

### ISSUE THREAD

**Issue by SrBedrock** [FabioZumbi12/UltimateChat#218]
**Descreva as alternativas que você considerou**
Gostaria de saber se tem como implementar uma opção de definir a cor no chat.

Exemplo: Se o jogador possui a permissão `uchat.chat.color` habilita o comando `/cor (&4|RED)`, `/color (&5|DARK_PURPLE)` ou algo do tipo, onde ele vai fixar a cor no chat, a cor volta para o definido nas configurações do chat (plugins\UltimateChat\channels\global.yml) caso ele dê `/cor`, `/color`.

**Comment by FabioZumbi12** [comment]
Faz o mesmo esquema que vc fez com as tags personalizadas.

Cria uma tag com a cor no `format`, poe permissão nela, poe no builder e so quem tiver a perm vai escrever naquela cor, e no builder poe essa tag antes da message!

**Comment by SrBedrock** [comment]
Realmente não teria como adicionar um comando para ficar a cor escolhida no chat?
