### ISSUE TITLE
[BUG] Missing language

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#219]
When a player attempts to PM a blocked player, users with social spy see this: https://gyazo.com/ae2c5a3f41dab417594f5523bf6cbe6e

Using `UltimateChat-1.8.9-b229-Universal`

I've also reset the lang file and the same thing still happens

**Comment by FabioZumbi12** [comment]
As a tempfix you ad this language like on language file as
`chat.ignored=&7-ignored-`

I've added on latest dev build.
