### ISSUE TITLE
[Suggestion] Do not count vanished players on player list on discord 

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#222]
Not exactly sure if this is supposed to be a bug or a suggestion, but please make a way so the amount of players displayed online on Discord does **not** include vanished players.

For example: Players in-game in TAB and when they do /list see 22 online players (even when there are 23 online players, just one vanished person) 
![image](https://user-images.githubusercontent.com/35243560/61742926-7d45c400-ad94-11e9-8280-24c4664b87cb.png)
However, on Discord it counts the staff member for everyone to see. So players can see when there are vanished players and how many of them.
![image](https://user-images.githubusercontent.com/35243560/61742966-98b0cf00-ad94-11e9-98ab-ede0eb980954.png)

By the way, I'm using the SuperVanish plugin so if you could include that support too that would be awesome!

**Comment by FabioZumbi12** [comment]
Added on next dev build.
