### ISSUE TITLE
[BUG] Discord Roles Not Removed Upon Group Removal

### ISSUE THREAD

**Issue by williamhatcher** [FabioZumbi12/UltimateChat#224]
When removing a discord synced role from in game, it does not remove that role from discord.

Note, this was observed when using Luckperms

**To Reproduce**
1. Setup discord role syncing.
2. Add a user to a role in game, wait for it to update in discord.
3. Remove their role in game.

**Expected behavior**
The role should be removed from discord, but it isn't.

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.12.2
 - Plugin Version:  UltimateChat-1.8.9-b227-Universal.jar
 - Java Version: 1.8

**Comment by FabioZumbi12** [comment]
Fixed on next dev build.
