### ISSUE TITLE
[BUG] Error on shutdown

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#225]
https://gyazo.com/bdb713bf59cd0bd927ae20398a59aced

Using https://gyazo.com/886e3c6e31ba1b26dc20acc97e579ba8

`UltimateChat-1.8.9-b229-Universal`

**Comment by Shmeeb** [comment]
Actually yes @FabioZumbi12 https://prnt.sc/p0484b

**Comment by FabioZumbi12** [comment]
Fixed on next dev build.
