### ISSUE TITLE
[Suggestion] /ignore <name> alias

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#227]
Not sure how this would align with channel ignore but many players are used to `/ignore <name>` to ignore others (from normal spigot servers), and think they don't have access to it. Would be amazing if this could be changed somehow

**Comment by SrBedrock** [comment]
You can add a aliases on commands.yml
``` yml
aliases:
  ignore:
  - chat ignore $1-

**Comment by FabioZumbi12** [comment]
I have no plans to change this as on sponge i need to register another command (and not subcommand) only for this.
