### ISSUE TITLE
[BUG] Players get permanently locked in PM

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#229]
https://gyazo.com/2cccef60695968a30ef4b1cb994083b0 I've been hearing bug reports/issues like this for awhile now and we can't figure out how to fix it for the player. 

Running `UltimateChat-1.8.9-b229-Universal.jar`
Sponge versions: https://gyazo.com/ed547729d43a2d19924441e85269724b

**Comment by Shmeeb** [comment]
Yes it still happens on `UltimateChat-1.8.9-b236-Universal`. Maybe remove this feature entirely or add an option to disable it?

**Comment by FabioZumbi12** [comment]
Should be fixed on next dev build. (Untested as dont accours on my server anymore)

**Comment by FabioZumbi12** [comment]
Still happening with latest dev builds?

**Comment by Shmeeb** [comment]
Yes it just happened on `UltimateChat-1.8.9-b242-Universal.jar`, a player did this: `/msg (name) (no message)`

**Comment by Shmeeb** [comment]
My staff troubleshoot with people who get stuck and this time this was the fix: https://gyazo.com/5c33d3da24cc90f850bce37950c2ccc3

**Comment by Shmeeb** [comment]
Seems to be fixed

**Comment by GershonR** [comment]
I just had this exactly bug appear on the #243 build. Did this fix get rolled backed?

**Comment by Mike5357** [comment]
Also still experiencing this issue. Very frustrating
