### ISSUE TITLE
Maven-published artifacts for Developers

### ISSUE THREAD

**Issue by Redrield** [FabioZumbi12/UltimateChat#23]
It would be useful for developers if you could publish builds for them to import in some free maven repository. There are several options for this, but the easiest would be [jitpack](https://jitpack.io). Publishing releases on Github would allow developers to import the jar into their projects without using flat directory dependencies in gradle, or system dependencies in maven.

**Comment by FabioZumbi12** [comment]
Done! Check for github description on README to get maven repository!
