### ISSUE TITLE
[BUG][Enhancement Request] Unable to Whisper between Vanished Administrators

### ISSUE THREAD

**Issue by Dimensional** [FabioZumbi12/UltimateChat#230]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
Unable to use /tell or /w to a vanished admin from another vanished admin.

**To Reproduce**
1. Become vanished or have another player/admin become vanished.
2. Have someone attempt to whisper/tell the vanished admin something
3. ???
4. Profit??? (Lousy Joke)

**Expected behavior**
What I was hoping was to be able to whisper between admins so to have a private conversation in case having to watch a player breaking any rules, without getting in the way of generic admin conversations in a channel

**Server and plugins versions (please complete the following information):**
 - Server: SpongeForge-1.12.2-2768-7.1.6-0RC3686.jar. To better help, using it with Pixelmon Reforged 7.0.7.
 - Plugin Version: UltimateChat-1.8.8-b196-Universal.jar
 - Java Version: Client Side, 1.8.0. Server Side, unknown

**Additional context**
It would be nice to have some sort of bypass or exemption permission for administrators so they can still whisper other admins, and any privileged players, who are in vanish mode. It would be very useful to allow any administrator to whisper another to assist with monitoring player activities for possible rule breaking, like XRaying. This would give the administrators a tool to privately converse without having to create a whole new channel solely for them or using the pre-established admin channel that other admins would be using for broader stuff and not need to share it all.

**Comment by FabioZumbi12** [comment]
Fixed on next dev builds. Added permission `uchat.see-vanish`

**Comment by Dimensional** [comment]
Hate to reopen a closed issue, but updated to build 239 and it's not working even with the new permission set on a group and a player. Tried it while vanished, then with another person vanished, and it still wouldn't send to vanished players. Both players either had the permission set directly or were set to their primary group.
