### ISSUE TITLE
[BUG] cant-ignore perm not working

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#232]
As a regular user I am able to ignore other users with the `uchat.cant-ignore.player` permission, but not the `uchat.admin` permission

Using https://gyazo.com/886e3c6e31ba1b26dc20acc97e579ba8
`UltimateChat-1.8.9-b229-Universal`

**Comment by Shmeeb** [comment]
Still happens on `UltimateChat-1.8.9-b236-Universal`

**Comment by FabioZumbi12** [comment]
If i mean what you want, i've removed cant ignore people with perm uchat.admin, only `uchat.cant-ignore.{player}`. Available on next dev builds.

**Comment by FabioZumbi12** [comment]
Did you tested?

**Comment by Shmeeb** [comment]
Still able to ignore players with `uchat.cant-ignore.player`

**Comment by Cyclopeanserver** [comment]
I'm having the same issue right now. the plugin works great except ignore isn't working. If i understood correctly if the group doesn't have the uchat.can't-ignore.player permission, they should be able to be ignored? Maybe I've given them a permission that overrides it?

**Comment by FabioZumbi12** [comment]
Added the permission `chat.cant-ignore.fabiozumbi12` and now players cant ignore me. Removed this permissions and player can ignore me again. All working like as is.
