### ISSUE TITLE
[BUG] Delay switching channels

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#233]
A lot of players have been complaining about how switching from the local channel to /g takes a few (1-3) messages to fully switch. If you send a message right after switching it will be sent to local.

https://gyazo.com/1bb2d13ac52493609ff999bae6b0bbae

Using https://gyazo.com/886e3c6e31ba1b26dc20acc97e579ba8
`UltimateChat-1.8.9-b229-Universal`

**Comment by FabioZumbi12** [comment]
In progress on #84
