### ISSUE TITLE
[BUG] Bungeecord not working

### ISSUE THREAD

**Issue by HeberonYT** [FabioZumbi12/UltimateChat#234]
**Describe the bug**
The bungeecord option is not working on SpongeForge servers.
I have configured the Global channel in bungeecord but when writing messages, they are not displayed on the other servers and the spongeforge server console throws errors.

**To Reproduce**
1. Create a bungeecord server and install UltimateChat-1.8.9-b233-Universal.jar
2. Create a spongeforge server with the following versions.
- Forge 1.12.2-14.23.5.2838
- spongeforge-1.12.2-2838-7.1.7-RC3901
- UltimateChat-1.8.9-b233-Universal
3. Configure the channels to send to bungeecord
4. Write on a channel that you send to bungeecord and watch the error in the sponge console.

**Screenshots and LOGs**
Log server SpongeForge:
https://pastebin.com/raw/baXX4JZN

**Server and plugins versions (please complete the following information):**
 - Server: SpongeForge 1.12.2 (RC3901)
 - Plugin Version: UltimateChat-1.8.9-b233-Universal
 - Java Version: Java 1.8

**Comment by SonkyTV** [comment]
Unfortunately, I have the same problem. I found that on the Sponge website but I'm not into it. Also need help or fix :) 
https://docs.spongepowered.org/stable/en/plugin/event/listeners.html

**Comment by HHServers** [comment]
same issue here UltimateChat-1.8.9-b243-Universal

https://gist.github.com/HHServers/c3aa15261f7bfde71d052bfb83e9efc5

**Comment by Spontini** [comment]
Same issue in here.

**Comment by HeberonYT** [comment]
This problem continues even after the UltimateChat update.
