### ISSUE TITLE
AntiSpam deny all messages [BUG] 

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#235]
If enable antispam in protections.yml, then all messages are perceived as spam, each time triggered a "wait-message". No erros in console.

In discord channel user sayed about it and I tryed reproduce and got same result. I used default config of antispam

**Server and plugins versions:**
 - Server: Spigot 1.13.2
 - Plugin Version: UltimateChat-1.8.9-b233-Universal.jar
 - Java Version: Java 1.8

P.S. with love, plugin expert Kichiro

**Comment by FabioZumbi12** [comment]
Fixed on next dev builds.
