### ISSUE TITLE
[BUG] Ultimachat não liga

### ISSUE THREAD

**Issue by xXFlameTyranusXx** [FabioZumbi12/UltimateChat#240]
O UltimateChat simplesmente para de funcionar ao ligar o Servidor ou dar um restart. Logo abaixo, está a descrição do erro.

gistfile: https://gist.github.com/xXFlameTyranusXx/2027b0b021a00f45293c3ccff11a327d

 - Servidor: Spigot 1.13.2
 - Versão do plug-in: UltimateChat-1.8.9-b239-Universal.jar
 - Versão do Java: Java 1.8

**Comment by FabioZumbi12** [comment]
O erro ta no na comunicação do jda com os servers do dicord, talves por token incorreto ou o jda desatualizado. Se vc nao tiver usando o discord com o uchat, só desabilitar e deletar o UchatJDA.jar
