### ISSUE TITLE
Error in Console [BUG] 

### ISSUE THREAD

**Issue by MysticCity** [FabioZumbi12/UltimateChat#242]
Im on: Paper 1.14.4 Build 196 
with 

  | UltimateChat-JDA.jar | 8.93 MB | anzeigen
-- | -- | -- | --
  | UltimateChat-1.8.9-b240-Universal.jar | 367.12 KB | anzeigen

and get this error with fresh install: https://pastebin.com/etYb2Jk1
and my server stop starting

**Comment by MysticCity** [comment]
Any News?

**Comment by FabioZumbi12** [comment]
Did you tryed to update UltimateChatJDA.jar? http://host.areaz12server.net.br:8080/job/UltimateChat/

**Comment by MysticCity** [comment]
23.10.2019 12:45:08 [INFO] [net.dv8tion.jda.api.JDA] Login Successful!
23.10.2019 12:45:08 [SEVERE] [net.dv8tion.jda.api.utils.SessionControllerAdapter] Worker has failed with throwable!
23.10.2019 12:45:08 java.lang.NoSuchMethodError: com.neovisionaries.ws.client.WebSocketFactory.setServerName(Ljava/lang/String;)Lcom/neovisionaries/ws/client/WebSocketFactory;
23.10.2019 12:45:08 	at net.dv8tion.jda.internal.requests.WebSocketClient.connect(WebSocketClient.java:321) ~[?:?]
23.10.2019 12:45:08 	at net.dv8tion.jda.internal.requests.WebSocketClient$StartingNode.run(WebSocketClient.java:1267) ~[?:?]
23.10.2019 12:45:08 	at net.dv8tion.jda.api.utils.SessionControllerAdapter$QueueWorker.processQueue(SessionControllerAdapter.java:220) ~[?:?]
23.10.2019 12:45:08 	at net.dv8tion.jda.api.utils.SessionControllerAdapter$QueueWorker.run(SessionControllerAdapter.java:203) ~[?:?]

**Comment by MysticCity** [comment]
And this is with 1.14.4 and the last build from your link

**Comment by FabioZumbi12** [comment]
Fixed with the latest version of JDA
