### ISSUE TITLE
[BUG] \n's replaced with nothing

### ISSUE THREAD

**Issue by Shmeeb** [FabioZumbi12/UltimateChat#244]
Even if a player has `uchat.chat.newline` set to false, any `\n`'s get replaced with nothing in chat.

Using `UltimateChat-1.8.9-b242-Universal.jar`

**Comment by FabioZumbi12** [comment]
This is intended, as \n will be replaced with a new line, and without permission, get removed.

**Comment by Shmeeb** [comment]
What if a player is instructing someone

Player: "What is the command for the nexus"
Staff: "./nexus X" turns into ".exus X"
Player: "wut?"

**Comment by SrBedrock** [comment]
O mesmo ocorre no meu servidor quando jogadores tentam enviar no chat o comando `/news`.
A melhor opção nessa caso seria alterar o "comando" para `\n`.

**Comment by FabioZumbi12** [comment]
Fixed on newer latest dev build.
