### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Lurreisper** [FabioZumbi12/UltimateChat#246]
**Descreva o bug**
O Spy está ficando sempre ativo, tem alguma permissão para isso que eu deva remover ou o comando era pra funcionar mesmo com permissão "*"?

**Comportamento esperado**
Ao desativar o spy, não receber mais as mensagens que não estão no meu 'range'.

**Capturas de tela e registros**
http://prntscr.com/pjtgcq

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Spigot 1.8.8
 - Versão do plug-in: Testado com UltimateChat-1.8.9-b242-Universal e UltimateChat-1.8.9-b239-Universal
 - Versão do Java: 8

**Contexto adicional**
Como dito acima, testei em 2 versões e também apaguei a pasta do plugin para testar novamente, porém sem sucesso.

**Comment by Lurreisper** [comment]
Olá?

**Comment by EduBRz** [comment]
o meu servidor tambem fica assim

**Comment by FabioZumbi12** [comment]
Isso ja foi resolvido nas ultimas builds
