### ISSUE TITLE
Anti Spam issue

### ISSUE THREAD

**Issue by CaoTrongThang** [FabioZumbi12/UltimateChat#247]
I swear i don't spamming but its keep telling that i need to wait to chat again even im just join the server and say one message but its still telling me stop spamming, sorry because my bad English

![image](https://user-images.githubusercontent.com/51023235/67530129-604cc400-f6e8-11e9-82da-3d02d1ee2ed1.png)

**Comment by FabioZumbi12** [comment]
It was solved on latest dev builds
