### ISSUE TITLE
Crash when chat the item's name

### ISSUE THREAD

**Issue by CaoTrongThang** [FabioZumbi12/UltimateChat#249]
Sorry about my bad English ~~"

when i turn off your item's name chat feature and replace it by chatitems plugin, everything working great ~~"

i think this is very important issue, when i show my items on chat, all players will got kick, that issue happen when the name to long or when i write any words behide ##, its will kick all players

item-hand:
enable: true
format: '&fx{hand-amount}{hand-name} &r'
placeholder: '##'

This is my items name: &f&l[&6&l◆&f&l] PHÚC THẦN &6&lCUNG &f&l[&6&l◆&f&l] &f&l[+1]
![image](https://user-images.githubusercontent.com/51023235/68523827-102d4e80-02f1-11ea-8608-c50b591a8453.png)

**Comment by FabioZumbi12** [comment]
Plugin and server versions? Try with the latest dev build.

**Comment by CaoTrongThang** [comment]
Sorry because my late respond, I already using latest version ~~" and im having another bug make all players got kick, i will create a new ticket ~~"

**Comment by FabioZumbi12** [comment]
I still needing more info like versions, logs and all info using the template, sorry.

And i didnt reproduced this error, in any way.
