### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by RaphaelMR** [FabioZumbi12/UltimateChat#250]
UChat full version: Ultimate chat-1.8.9-b235-Universal.jar

Problema, quando dou /tell nick, o tell não funciona, aparecendo as mensagens de ajuda do uChat
Print: http://prntscr.com/pxjvpk
Já tentei resetar a config e o problema continua
Também gostaria de saber como colocar a tag "MAGNATA" ( plugin pbrmagnata ) no chat, pois não entendi com o tutorial da Gamers Board, obrigado.

**Comment by FabioZumbi12** [comment]
Ta usado versão antiga. Baixa a ultima dev build, e deleta a config e deixa gerar nova pra esse problema (com a versão nova)
