### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by SrBedrock** [FabioZumbi12/UltimateChat#251]
**Capturas de tela e registros**

https://hasteb.in/utecetoq.shell

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Paper version git-Paper-225
 - Versão do plug-in: UltimateChat-1.8.9-b242-Universal.jar
 - Versão do Java: 1.8

**Contexto adicional**
Adicione qualquer outro contexto sobre o problema aqui.

**Comment by FabioZumbi12** [comment]
Seu server travou por 10 segundos, o uchat so ta tentando mandar mensagem enquanto o sv ta travado
