### ISSUE TITLE
Players Got Kick

### ISSUE THREAD

**Issue by CaoTrongThang** [FabioZumbi12/UltimateChat#252]
My English is very bad, sorry.

Im using Paper Spigot 1.12.2 and your latest version of UltimateChat (b242), i really don't know how all of my players got kick
this is the error, really hope you will take a look about it, if you need anything, just tell me ~~"
https://pastebin.com/TCaxYHRY

**Comment by FabioZumbi12** [comment]
Your server was already frozen, uchat shows in this because people try to send message whit the server in crash state.
