### ISSUE TITLE
[Sugestão] Travar canal por comando /chat lock <canal>

### ISSUE THREAD

**Issue by SrBedrock** [FabioZumbi12/UltimateChat#253]
Sempre que preciso dar um anúncio ou fazer um evento quero travar um chat e não consigo.

**Descreva a solução que você gostaria**
Se for adicionado um comando para travar o canal, isso ajudaria muito.

**Descreva as alternativas que você considerou**
Criar um comando como `/chat|uchat lock <canal>`
Exemplo: `/uchat lock local`

Mensagem ao travar o chat:
- O canal %canal% foi bloqueado pelo jogador %player%!

Mensagem ao tentar falar com canal travado:
- Este canal está bloqueado!

**Comment by FabioZumbi12** [comment]
Não entendi. Se usar o comando `/<canal>` ou `/chat <canal>` por exemplo ja trava.

**Comment by SrBedrock** [comment]
No caso, seria um comando administrativo usado pela staff para bloquear o envio de mensagens em determinado canal.
Exemplo: Ao utilizar o comando `/chat lock geral` a staff bloqueia o envio de mensagem por outros players no canal bloqueado.
