### ISSUE TITLE
[BUG] Savage Factions em conflito!

### ISSUE THREAD

**Issue by hx-gh** [FabioZumbi12/UltimateChat#255]
**Descreva o bug**
Bom, o plugin entra em conflito com o Savage Factions em questão dele possuir um chat extra para as facções, este chat, quando um player envia uma mensagem volta em vazio.

Segundo bug: No chat, ele me volta, o que eu digitei, sem o UltimateChat haver formatado e separado para os canais e logo em seguida vem a mensagem novamente agora com o Canal no qual fora enviado!

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Spigot 1.14.4
 - Versão do plug-in: UltimateChat-1.8.9-b235-Universal
 - Versão do Java: VPS, não saberia informar, fora da VPS em ambiente de testes é o Jdk 1.8

**Comment by FabioZumbi12** [comment]
O Uchat é o ultimo listener na ordem dos eventos. Outros plugins devem registrar seus evento antes do ultimo (os devs sabem como fazer isso) ou em ultimo caso usar a api do uchat.
