### ISSUE TITLE
Redis not working [BUG] 

### ISSUE THREAD

**Issue by HHServers** [FabioZumbi12/UltimateChat#258]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
Jedis messages aren't sending to servers even though jedis is enabled, port and host is in config and "Ping" on jedis server replies "PONG"

global and main conf https://gist.github.com/HHServers/6bbb199e6522d45e2498317170e76222

**Comment by HHServers** [comment]
tried using a local Redis server with localhost in config and same problem - no messages come through

**Comment by FabioZumbi12** [comment]
It was added again on plugin with latest dev build.
