### ISSUE TITLE
[Suggestion] Permissions for AutoMessages

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#260]
It would be cool and useful to add permission support for auto messaging.

For example, I want only vip players to see certain messages

**Comment by SrBedrock** [comment]
Seguindo a linha dessa sugestão, seria possível adicionar um comando para desabilitar as mensagens?
Caso o player não queira receber mais as mensagens ele pode usar o comando /chat autotoggle ou algo do tipo.

**Comment by FabioZumbi12** [comment]
Added permissions for auto messages on latest dev build
