### ISSUE TITLE
[BUG] JDA init error on 1.15.2

### ISSUE THREAD

**Issue by simonchow96** [FabioZumbi12/UltimateChat#261]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <https://host.areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
I have UltimateChat b243 with JDA on Paper 1.15.2. When JDA is being initialized, an error stopped it from loading completely.

**To Reproduce**
Simply install UltimateChat and JDA on Paper 1.15.2. Start the server instance.

**Expected behavior**
JDA loaded successfully

**Screenshots and LOGs**
https://pastebin.com/tTf2nUDv

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.15.2
 - Plugin Version: UltimateChat-1.8.9-b243-Universal
 - Java Version: Java 1.8

**Additional context**
None at the moment

**Comment by FabioZumbi12** [comment]
Jedis re-added on latest dev build.
