### ISSUE TITLE
[Sugestão] Usar Hand com "use-this-builder" ativado

### ISSUE THREAD

**Issue by DGabriel13** [FabioZumbi12/UltimateChat#267]
**Problema:** Sempre que eu uso "true" no use-this-builder no arquivo local.yml para utilizar as tags, quando eu digito "@hand" no canal com essa função ativada ao passar o mouse emcima do item não aparece a descrição por exemplo:

use-this-builder: true
receivers-message: true
allow-hand: true
tag-builder: world,marry-tag,ch-tags,clan-tag,factions,group-prefix,nickname,group-suffix,localmessage
**Imagem:
![image](https://user-images.githubusercontent.com/58773688/77857437-fd7bcd80-722f-11ea-8cf3-e7daa503a1b9.png)
**

use-this-builder: false
receivers-message: true
allow-hand: true
tag-builder: world,marry-tag,ch-tags,clan-tag,factions,group-prefix,nickname,group-suffix,localmessage
**Imagem:
![image](https://user-images.githubusercontent.com/58773688/77857455-1f755000-7230-11ea-9988-316e0bf59fd2.png)
**

Minha sugestão é poder ter essas duas funções trabalhando no mesmo formato

**Comment by FabioZumbi12** [comment]
Não consegui reproduzir aqui. testei e nos 2 modos o hand funciona certinho!
