### ISSUE TITLE
[BUG] errors with jda on dev247

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#268]
I updated to dev-build 247 and JDA not working https://hastebin.com/ebowagibor.sql

**Comment by FabioZumbi12** [comment]
This paste is blank

**Comment by Kichiro72** [comment]
https://pastebin.com/3L908ynG

**Comment by Kichiro72** [comment]
and this one https://pastebin.com/P80iCN3r

**Comment by simonchow96** [comment]
> and this one https://pastebin.com/P80iCN3r

@FabioZumbi12  I have encountered this as well. I hope it can get fixed asap, thanks!

**Comment by FabioZumbi12** [comment]
Please use `/chat ?` and paste me here the response, like this: 
![image](https://user-images.githubusercontent.com/5833818/79677086-ada37d00-81c3-11ea-9e0f-b4f3f506b044.png)

And on server start, UltimateChatJDA should be on v 2.0 like this: 

![image](https://user-images.githubusercontent.com/5833818/79677101-eb080a80-81c3-11ea-8f15-2db3c477c6f2.png)

On my environment (Paper 1.15.2 and on Mohist 1.12.2) i didnt get any errors, and its running on my server very well
![image](https://user-images.githubusercontent.com/5833818/79677111-0d9a2380-81c4-11ea-87fd-f66c5fc51cec.png)

**Comment by FabioZumbi12** [comment]
If possible, upload the jars you is using, here!

**Comment by simonchow96** [comment]
> Please use `/chat ?` and paste me here the response, like this:
> ![image](https://user-images.githubusercontent.com/5833818/79677086-ada37d00-81c3-11ea-9e0f-b4f3f506b044.png)
> 
> And on server start, UltimateChatJDA should be on v 2.0 like this:
> 
> ![image](https://user-images.githubusercontent.com/5833818/79677101-eb080a80-81c3-11ea-8f15-2db3c477c6f2.png)
> 
> On my environment (Paper 1.15.2 and on Mohist 1.12.2) i didnt get any errors, and its running on my server very well
> ![image](https://user-images.githubusercontent.com/5833818/79677111-0d9a2380-81c4-11ea-87fd-f66c5fc51cec.png)

Hi @FabioZumbi12 I was using b247 when I encountered the problem. Now I switched to b248 from your Jenkin the plugin is working without the mentioned issue now.

**Comment by Kichiro72** [comment]
b248 now good working fo me too

**Comment by FabioZumbi12** [comment]
Cool
