### ISSUE TITLE
[Suggestion] Add option to disable case sensitivity for censor

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#269]
If an indecent word (from censor list) has first letter with excellent case, then this word is not considered bad

I suggest adding an option to disable case sensitivity, something like **case-sensitivity: true/false**

**Comment by FabioZumbi12** [comment]
You already can use regex on word for censor

**Comment by Kichiro72** [comment]
yes, but it very difficult for many people
