### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by ProDash1998** [FabioZumbi12/UltimateChat#27]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  TacoSpigot

_Inform you RedProtect jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  java 8u131

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  Previously still worked. After uploading this plg Uchat does not work https://www.spigotmc.org/resources/better-nick-api-1-8-3-1-12.39633/

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  https://hastebin.com/pohivegude.vbs
https://timings.aikar.co/?id=69ca9f8932214f01b6f30ef67d42aa9a#timings

**Comment by FabioZumbi12** [comment]
Test with latest version, but seems this pugin is not compatible with uchat.

**Comment by FabioZumbi12** [comment]
Please, try the latests dev build from jenkins.
