### ISSUE TITLE
Feature Request: Velocity Support

### ISSUE THREAD

**Issue by blacksythe** [FabioZumbi12/UltimateChat#271]
Hi love your plugin.

(Sweetening complete)

Can you velocity support along side upcoming bungee support.

https://www.velocitypowered.com/

It has much better support for later versions of minecraft uuid forwarding is more secure etc.

**Comment by FabioZumbi12** [comment]
But whats wrong? Theres some errors on run UChat on velocity?

**Comment by blackd** [comment]
Hi

I would love it if UChat supported velocity.
Here is the error message we see:

[02:20:05 ERROR]: Unable to load plugin plugins/UltimateChat-1.9.1-b265-Universal.jar
com.velocitypowered.api.plugin.InvalidPluginException: The plugin file UltimateChat-1.9.1-b265-Universal.jar appears to be a Bukkit or BungeeCord plugin. Velocity does not support Bukkit or BungeeCord plugins.

**Comment by blackd** [comment]
I made a UCProxy equivalent for velocity here https://gist.github.com/blackd/3851c230d095958867c8ac6e2d37413c 
I tested it it works without issues.

Feel free to use the code or comment if you want me to make a pull request.

**Comment by FabioZumbi12** [comment]
@blackd and theres no config/yml file? Seems good this code!

**Comment by blackd** [comment]
velocity_plugin.json is generated from the Plugin annotation.

Also I'll do the pull request... I'm using the IDEA's minecraft development plugin and it handled the pom.xml and although not very complex it looks non trivial.
