### ISSUE TITLE
[BUG] JDA Connection spam

### ISSUE THREAD

**Issue by Tahrll** [FabioZumbi12/UltimateChat#272]
**Describe the bug**
Hi I have the following problem, and for me the JDA does not work properly discord blocked my bot because of connection spam

it happens every few seconds

**Screenshots and LOGs**

https://pastebin.com/utxwubeE

**Server and plugins versions (please complete the following information):**
 - Server: Thermos 1.7.10
 - Plugin Version: 248
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
`Encountered IDENTIFY Rate Limit!` its a message from discord, uchat's jda its only logging.
