### ISSUE TITLE
[BUG] Jogadores ficando com a mesma tag ao falar simultaneamente

### ISSUE THREAD

**Issue by Aureom** [FabioZumbi12/UltimateChat#273]
**Antes de abrir um problema, verifique estas etapas:**
* Se você estiver executando o plug-in na primeira vez, tente executar novamente para ver se o problema persiste.
* Verifique se a sua compilação é a mais recente do nosso Jenkins. Clique aqui: <http://host.areaz12server.net.br:8081/job/UltimateChat>
* É importante você incluir o nome do jar do plug-in, porque as informações de versão e construção estão nele.

**Descreva o bug**
É o mesmo bug reportado por mim no issue #163 no qual quando dois jogadores falam ao mesmo tempo eles ficam com as tags de um ou de outro.

Como pode ver abaixo, o jogador TequilAxBr está com a tag [GG] e o Aureom com a tag [Fight] (Ambas são adicionadas no mesmo listener)
![img_bug](https://i.imgur.com/GLsWxOT.png)

**Reproduzir**
Etapas para reproduzir o comportamento:
Crie um listener utilizando o "SendChannelMessageEvent" e adicione uma tag, diferente para cada jogador para o bug funcionar, após isso adicione na config do UChat, e tente falar ao mesmo tempo no chat com outro jogador

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: PaperSpigot 1.8.8
 - Versão do plug-in: UltimateChat-1.9.0-b245-Universal.jar
 - Versão do Java: 1.8

**Contexto adicional**

O codigo no qual registro as tags: 
```Java
	@EventHandler
	private void onChat(SendChannelMessageEvent event) {
		if(event.getSender() instanceof Player) {
			Player player = (Player) event.getSender();
			Tag tag = plugin.getTagManager().getPlayerTag(player).getInUse();
			if(tag != null) {
				event.addTag("{customtags}", tag.getTag());
			}
		}
	}
```

Como está na config:
```
  customtags:
    format: '{customtags} '
```

**Comment by FabioZumbi12** [comment]
Eu não consegui reproduzir esse problema. Tenta isso na dev build 287.
