### ISSUE TITLE
[BUG] Sponge Version Fails to start 1.12.2-2838-7.2.1-RC4011

### ISSUE THREAD

**Issue by blacksythe** [FabioZumbi12/UltimateChat#274]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
uchat Fails to load, latest version spongeforge, forge 2838, uchat shows in sponge plugins command,

No uchat is available and no commands are runnable

**To Reproduce**
1. Spongeforge, forge 2838 and ultimate chat'
2. Click on 'Start server'
3. See error
Sponge lists plugin as loaded but no chat commands are available

**Expected behavior**
U chat to start

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to 

https://gist.github.com/blacksythe/d5b1abf7ecf977f54bf7d01491ef7361

**Server and plugins versions (please complete the following information):**
 - Server: Spongeforge 7.2.1-rc4011
 - Plugin Version: latest Jenkins 248
 - Java Version: 8

**Additional context**
Working fine on spigot

**Comment by FabioZumbi12** [comment]
Has been fixed on latest dev builds
