### ISSUE TITLE
[BUG] Some long time respond errors 

### ISSUE THREAD

**Issue by Kichiro72** [FabioZumbi12/UltimateChat#275]
b248
1.15.2 Paper

https://pastebin.com/Nst3sFNj

**Comment by FabioZumbi12** [comment]
`br.net.fabiozumbi12.translationapi.TranslationCore.translateItem` maybe the wrong or delayed response from Google. You can try to remove TranslationCore to see if happens and maybe open an issue on TC github.

**Comment by Kichiro72** [comment]
Avoid usage of translation api when is not needed - After this update I have not seen this problem yet again. I will observe more, but I hope it helped

**Comment by FabioZumbi12** [comment]
Oh, right. You opened this issue before i upload that fix.
