### ISSUE TITLE
JDALoader Error

### ISSUE THREAD

**Issue by ijo42** [FabioZumbi12/UltimateChat#277]
I fix an loading of JDALoader in c46b6dc, but JDA Bot Login still erroring

1. Get 250 Universal and JDA Build from Jenkins
2. Get Forge 2825, MC 1.12.2
3. Get SpongeForge-1.12.2-2838-7.2.0 
4. Fill an config (bot token and `use` flag
5. Start server
6. **An error occured**

I really expected thats bot turn on Online and server successful continue starting

LOG - https://p.fns.wtf/ehewajorof.vbs

 - Java Version: 1.8.0_171

Open to discussion Discord - `spinel#2440`

**Comment by FabioZumbi12** [comment]
Try the latest dev build

**Comment by ijo42** [comment]
Yes,thanks!
