### ISSUE TITLE
[BUG] COOLDOWN BUG AND CH-COLOR NOT WORK

### ISSUE THREAD

**Issue by Lucasmm016** [FabioZumbi12/UltimateChat#280]
The plugin does not allow me to spawn on my warp when the server starts.
The plugin is broken in question to cooldowns between messages, it just doesn't work.
The plugin does not allow me to decide a color for {message} using {ch-color} in "message> format> HERE".

Your plugin is perfect, but please fix this.

**Comment by FabioZumbi12** [comment]
1. Uchat don't handle this, if its interfering, paste error logs generated by uchat.
2. Its works for non ops, tested locally.
3. ch-color dont work on `message` tag (on tags config), you need to put the ch-color on last tag before `message`.
