### ISSUE TITLE
"/tell"   "/tell <player><msg>"  not work!

### ISSUE THREAD

**Issue by IIIVVIII** [FabioZumbi12/UltimateChat#281]
UltimateChat-1.9.0-b253-Universal.jar

/tell don`t work

![2020-05-17_03 42 44](https://user-images.githubusercontent.com/34328781/82131634-9cfd1b80-97f0-11ea-8af5-05f31b26a23e.png)
![2020-05-17_03 42 58](https://user-images.githubusercontent.com/34328781/82131635-9e2e4880-97f0-11ea-901e-8ba280837ff8.png)
![2020-05-17_03 43 00](https://user-images.githubusercontent.com/34328781/82131636-9ec6df00-97f0-11ea-8be2-d156263662f6.png)

**Comment by guimartino** [comment]
Add 'tell' in the alias on the config
Will look like this:
tell:
  cmd-aliases: 't,w,m,msg,private,priv,r,tell'

**Comment by IIIVVIII** [comment]
this line is present in the config initially. But the / tell command does not work.
![image](https://user-images.githubusercontent.com/34328781/82141238-ea5ba600-984d-11ea-8b65-513f9607ebeb.png)
when entering the / tell <player> commands, nothing happens, except for the output of "uchat Help" with a description of the commands.
![image](https://user-images.githubusercontent.com/34328781/82141330-779efa80-984e-11ea-8af8-841b7f999cb3.png)

functions / lock \ unlock private channels also do not work

**Comment by guimartino** [comment]
Yes, the line is present but you don't have the "tell" alias on the line
You have: `cmd-aliases: 't,w,m,msg,private,priv,r'`
But must be: `cmd-aliases: 't,w,m,msg,private,priv,r,**tell**'`

**Comment by IIIVVIII** [comment]
OK,Thanks!
