### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by YummiKun** [FabioZumbi12/UltimateChat#283]
an internal error occurred while attempting to perform this commands

toda vez que executo um comando, aparece isto!

**Comment by FabioZumbi12** [comment]
Usa o template e escolhe a opção "3 - Reportar BUG - PT-BR" pra abrir uma issue com as informações que pede como versão do plugin, do server, erro completo e etc. Sem isso não da pra arrumar nem saber onde ta ruim!
