### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError em servidores bukkit+forge na 1.7.10

### ISSUE THREAD

**Issue by juanmuscaria** [FabioZumbi12/UltimateChat#284]
**Descreva o bug**
Se você der `@hand` ele não irá aparecer nada e ocorrerá um NoClassDefFoundError ao tentar usar uma classe do guava.

**Reproduzir**
Digite `@hand` no chat.

**Comportamento esperado**
Serializar corretamente o item e aparecer as informações do item no chat.

**Capturas de tela e registros**
https://gist.github.com/juanmuscaria/bf410590680021ae7657fe2df25135e5

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Crucible 3.1 (Minecraft 1.7.10)
 - Versão do plug-in: UltimateChat-1.9.0-b259-Universal.jar
 - Versão do Java: Java 1.8

**Contexto adicional**
Esse erro parece ser o mesmo erro que o LuckPerms tem em versões legacy do bukkit, muito provavelmente dar shade no guava irá resolver esse problema.

**Comment by FabioZumbi12** [comment]
O servidor que vc ta rodando não tem uma biblioteca necessária para deserializar o ItemStack: 
java.lang.NoClassDefFoundError: guava10/com/google/common/base/Utf8

**Comment by juanmuscaria** [comment]
Ele tem, mas pelo fato de ser uma versão antiga (Minecraft 1.7.10) ele não tem essa classe em especifico. A versão do guava a ser usada no servidor é guava 16.0

**Comment by FabioZumbi12** [comment]
O problema é que eu no posso deixar o plugin compatível com a versão do Crucible e deixar de funcionar nas versões de Bukkit/Spigot/Paper. Ve com pessoal do Crucible pra deixar na merma versão do spigot e fica certo! 

Pelo que vi, o Crucible ainda ta em desenvolvimento e ta com uma grande lista de tarefas ainda.
