### ISSUE TITLE
SaberFactions chat disconnection[BUG] 

### ISSUE THREAD

**Issue by Sylensky** [FabioZumbi12/UltimateChat#286]
**Describe the bug**
Hi do wanted to integrate Faction onto my paper server and ultimatechat should support factions as i could read from the descriptions and configurations. 
Unfortunately it doesn't hook into factions or vice versa and it instead disconnects you from the server when you try to send a chat message to any channel. 

**To Reproduce**
1. use both jars together
2. join the server
3. additionally check logs since there is no hook message as it is for example for the old simpleclans plugin
4. you will get disconnected

**Expected behavior**
the chat message should be send properly.

**Screenshots and LOGs**
Apparently i cant take screenshots of this since it keeps me disconnecting.

**Server and plugins versions (please complete the following information):**
- UltimateChat v1.9.0 b235
- not using it for the first time
- Saberfactions [1.6.9.5-2.4.0-RC]
- Catserver 1.12.2-de0a1c1 
- inherits forge 14.23.5.2854
 - Java 1.8]

**Comment by Sylensky** [comment]
Oh well i didn't read properly on your spigot description page.. you only support the massivecore factions which different than saberfactions..
So this topic would be more likely a feature request to integrate the saberfactions hook aswell.

**Comment by FabioZumbi12** [comment]
I got a pr from an forked reposutory from other guy and now its compatible with SaberFactions, but only for tags. SaberFaction still need to listen for cancelled chat events to do not get error or wrong results with UltimateChat. Check the latest dev build.
