### ISSUE TITLE
Bungeecord instalation

### ISSUE THREAD

**Issue by sebastiaanlavell** [FabioZumbi12/UltimateChat#289]
so I am sorry if this is a noob question I am still kinda new to mc servers in general and I wanted to use this plugin fur my bungee cord server soo you can not only  read/write message across server but also for the discord and I first tested the plugin on a paper server it worked fine, but now that I want to use it with bungee I drag the jar files into bungee plugins restart my server and noting happens was wondering what I am doing wrong

![image](https://user-images.githubusercontent.com/30122362/86609728-a6169780-bfac-11ea-9cbe-b9b06aa046d0.png)

**Comment by FabioZumbi12** [comment]
You can follow this instructions: https://github.com/FabioZumbi12/UltimateChat/wiki/(4)-BungeeCoord

If still not working, check the console for errors and put the versions is using, including bungee and server versions. Btw, try the latest dev build: http://host.areaz12server.net.br:8081/job/UltimateChat/
