### ISSUE TITLE
[BUG] GeyserMC Bedrock Players Cant See Player Chat Messages

### ISSUE THREAD

**Issue by FlatOutGamer3000** [FabioZumbi12/UltimateChat#298]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
 When connected with bedrock edition through GeyserMC, player chat messages are not visible, only Java players can see them.

**To Reproduce**
1. Install GeyserMC, Floodgate, and Ultimate Chat on a spigot server
2. Connect a java account and bedrock account to the server
3. Send a chat message from the java account
4. You will see that the bedrock account doesn't see the message

**Expected behavior**
Bedrock players see chat messages from other Java and Bedrock players when in the same channel.

**Screenshots and LOGs**
![2020-08-10 (3)](https://user-images.githubusercontent.com/25018581/89828824-99dfa600-db27-11ea-8279-46c93bec0601.png)

 Upload your logs to https://gist.github.com/

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.16.1
 - Plugin Version: 1.9.1-b265-Universal
 - Java Version: 1.8

**Additional context**

**Comment by FabioZumbi12** [comment]
Its a problem with Geyser, as plugins cant know about Geyser or any of this proxies types
