### ISSUE TITLE
SimpleClans

### ISSUE THREAD

**Issue by iPokenWIGGLE** [FabioZumbi12/UltimateChat#3]
Bom , eu coloco o [] para deixar a tag do clan dentro , mas quando o player não tem clan os [] continuam sem nada dentro , teria como fazer eles sumirem ?

http://prntscr.com/bgqlsu

Vlw-

**Comment by FabioZumbi12** [comment]
Já arrumou? Mals pela demora. Nas configs ve se tem isso:

`general:
  remove-from-chat: '[]'`

Isso vai remover as tags vazias com []
