### ISSUE TITLE
Suggestion: More ignore permissions/options

### ISSUE THREAD

**Issue by Mike5357** [FabioZumbi12/UltimateChat#30]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform you RedProtect jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-Spigot-1.7.3-b574

_Your server Minecraft version_  
Minecraft version:  1.12.1

_Issue or Suggestion?_  
What you want?:  Suggestion: A permission node so that staff members cant be "/ignore"'d, as well as disabling specific channels from being ignored (like Global).

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  I would like to request a permission node so that staff members cant be ignored by players. We haven't been able to give our players permissions to /ignore because they could get annoyed at a staff member for telling them to follow the rules and then ignore them.
As well, I'd like to request as an option in the channel configs to disable a channel from being ignored (like Global). Could be something like "allow-channel-to-be-ignored:false"

**Comment by FabioZumbi12** [comment]
Added, please test on latest jenkins build.

The ignore permission is `uchat.cant-ignore.<player/channel>`

And on this build the channel permissions changed to:

```
uchat.channel.<channelname>.read
uchat.channel.<channelname>.write
```

**Comment by Mike5357** [comment]
To clarify, how does the ignore permission work?
Do I have to add a permission for each player who cant be ignored like:
uchat.cant-ignore.Mike5357, etc
or does uchat.cant-ignore.player block anyone in that permission group from being ignored? (This way would be preferred)

**Comment by FabioZumbi12** [comment]
Players cant ignore admins with permission `uchat.admin` or you give the permission `uchat.cant-ignore.Mike5357` to your players, or default group.
