### ISSUE TITLE
Remover mensagens é possivel ?

### ISSUE THREAD

**Issue by Jysdsod** [FabioZumbi12/UltimateChat#306]
gostaria de saber se e possivel remover essas duas mensagem pois acho totalmente desnecessarios elas,estou tentando deixar o chat mais clean possivel,organizado, mas essas mensagem enchem o saco.
essa primeira e do arquivo de "lang", tem em todos os arquivos de lang de qualquer idioma a unica opção que tem e para mudar a mensagem após " = ", mas eu gostaria de remover por completo, ja tentei apagando as 2 linha mas elas aparecem denovo após qualquer mensagem.

essa primeira mensagem e para notificar que quando alguem manda mensagem e não tem ninguém no mundo 
**channel.noplayer.world=**
já essa segunda mensagem e para dizer que não tem ninguém por perto para receber a mensagem(é claro vc pode escolher o raio de distancia em blocos para a mensagem local chegar,mas não é esse o ponto que eu quero aqui.)
**channel.noplayer.near=**

**Comment by FabioZumbi12** [comment]
Deixa em branco ou muda a opção que tem ali mesmo, noplayermesage = false (algo assim)
