### ISSUE TITLE
[Suggestion] Permission per color.

### ISSUE THREAD

**Issue by Remski01** [FabioZumbi12/UltimateChat#307]
**Is your feature request related to a problem? Please describe.**
Hello, can you add permissions per color instead of none or all, like `uchat.chat.color.darkred` with also support for per channel, so `uchat.chat.color.darkred.<channel>`

**Describe the solution you'd like**
`cmi.colors.<color>` & `cmi.colors.<color>.<channel>`

**Additional context**
I'm not talking about the Hex colors, i understand you cant add permissions for them as you otherwise have to add 16 miljoen permissions, but the default one atleast should have it imo.

**Comment by FabioZumbi12** [comment]
Already added
