### ISSUE TITLE
Suggestion - Add a shortcut to display item in chat

### ISSUE THREAD

**Issue by Cat121** [FabioZumbi12/UltimateChat#31]
This is a suggestion right after I tried to use ItemChat with UltimateChat and it's so convenient to "link" item in chat.

Inspiration is from this plugin : 
https://forums.spongepowered.org/t/itemchat-allows-you-to-display-your-item-in-chat/19269/12

Also, could you add regex filter and words replacement ?

**Comment by FabioZumbi12** [comment]
Easy to implement ;)

> Also, could you add regex filter and words replacement ?
regex and word replecement in what part of plugin/message?

**Comment by Cat121** [comment]
Nice ! You will have to rename it to OverkillChat haha.

Well, replacement in chat with associated permission uchat.replace.bypass.
e.g. replace _b[i](1+)tch_ by _honey_

Also is there a way to see all channels we joined ? And talk is the chosen one, WoW like

**Comment by FabioZumbi12** [comment]
You can join in only one channel at once.
The replacement you mean is for censor?

**Comment by Cat121** [comment]
It could be cool to join X channels at the same time but 1 is cool too.

Replacement is for censor, **** is not what I would ike to do.

**Comment by FabioZumbi12** [comment]
Done, try the latest dev build (or sponge ore for sponge).
