### ISSUE TITLE
[BUG] Regex seems to be broken?

### ISSUE THREAD

**Issue by MissPotato** [FabioZumbi12/UltimateChat#310]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
Seemingly valid regex such as [list below] all don't work. Some returning errors about Unclosed group near index errors, specifically the ones including \bs in them. The other ones do not return any errors but also does not replace.

- (([s][a][m][p][l][e])|(sample))"
- (sample)
- ([s][a][m][p][l][e])
- \([s]*[a]*[m]*[p]*[l]*[e]*\)
- (\\b.?f+[a4&*]+i*g+[oei1]*[t+]*[sz%]*\\b)
- (\b.?f+[a4&*]+i*g+[oei1]*[t+]*[sz%]*\\b)
- (f+[a4&*]+i*g+[oei1]*[t+]*[sz%]*)
- \([s]*[a]*[m]*[p]*[l]*[e]*\)

**Expected behavior**
For regex to work the same way that just having ass: does. 

**Screenshots and LOGs**
Config File: https://pastebin.com/cvrNVerq

**Server and plugins versions (please complete the following information):**
 - Server: Paper-209
 - Plugin Version: UltimateChat-1.9.1-b265-Universal
 - Java Version: Java Version: 1.8.261 b12

**Comment by FabioZumbi12** [comment]
Its a java limitation about string. You need to ad another `\` to close the regexes.
