### ISSUE TITLE
[Suggestion] Allow disabling switching channel without commands

### ISSUE THREAD

**Issue by Katrix** [FabioZumbi12/UltimateChat#312]
**Is your feature request related to a problem? Please describe.**
It seems like if you type the name or alias of a channel at the start of a message, it consumes that token, and sends/switches to that channel. We use the alias `G` for our global channel, which means we can't begin sentences with `G`.

**Describe the solution you'd like**
An option to disable the behavior

**Describe alternatives you've considered**
Using another chat plugin

**Comment by FabioZumbi12** [comment]
This only happens if you set `char-alias: ''` to the channel letter, otwise, nothing happens. I cant reproduce this.
