### ISSUE TITLE
[BUG] Crash when sending messages

### ISSUE THREAD

**Issue by HeberonYT** [FabioZumbi12/UltimateChat#313]
**Describe the bug**
When sending a message using the / tell command, the server freezes and the console throws many errors, and the messages are never delivered.

**Screenshots and LOGs**
https://pastebin.com/raw/LTNviPLp

**Server and plugins versions (please complete the following information):**
 - Server: Paper-1.12.2-b1618
 - Plugin Version: UltimateChat-1.9.1-b283-Universal
 - Java Version: Java 1.8

**Additional context**
Usaba una versión muy vieja y no ocurría este error.

**Comment by Dowritos** [comment]
i have kinda same problem but with deluxetags :/

**Comment by FabioZumbi12** [comment]
Unfortunately i'm also having this problem 👎🏻 

I need to fix asap!

**Comment by HeberonYT** [comment]
@FabioZumbi12 thanks for the new version (v284), unfortunately I still get the problem using the Tell command.

https://pastebin.com/raw/3MPb9he9
