### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by Dowritos** [FabioZumbi12/UltimateChat#314]
**Before open an issue, checkout this steps:**
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://host.areaz12server.net.br:8081/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

**Describe the bug**
So, when i select a /tags from deluxe tags the chat stops working, sometimes it does work, i don't know how. but then again it stops working. also my console is giving errors with UltimateChat

**To Reproduce**

**Expected behavior**
For the plugin to work normally, because i have a friend of me and it works fine on his server.

**Screenshots and LOGs**
https://gist.github.com/Dowritos/63b61ddff4a38a19c533eef2972eabdb

**Server and plugins versions (please complete the following information):**
 - Server: Paper 1.16.4 [Latest]
 - Plugin Version: UltimateChat-1.9.1-b277-Universal.jar
 - Java Version: Java 11

**Additional context**
I spoke to helper in your discord server named Kichiro. He helped me alot with setting up this plugin, but the tags just bug out somehow.

**Comment by FabioZumbi12** [comment]
The error in your logs its because you have removed a tag on `tags` config or have set some `format:` to an empty value. Regenerate the config and check again for the errors. Change the config file in parts to do not break all.
