### ISSUE TITLE
[Suggestion] Message display

### ISSUE THREAD

**Issue by HeberonYT** [FabioZumbi12/UltimateChat#315]
I would like to suggest an improvement.

When using the / tell command on an external server connected via Redis, it would be useful if the sender of the message also observes the message in the chat, currently no messages are output and it is difficult to know if it was delivered successfully.

It would be useful for the sender to view the message in their own chat, just as the receiver can see it.

-UltimateChat-1.9.1-b283-Universal.jar

**Comment by HeberonYT** [comment]
This is an example of the Nucleus setup, it might help to get ideas.

`# If true, players can message themselves which may be useful for testing.
    can-message-self=true
    # The prefix for received messages. This is displayed to the receiever. Use {{from}} and {{to}} for the message sender/receiver, {{fromDisplay}} or {{toDisplay}} for the display names.
    msg-receiver-prefix="&7[{{fromDisplay}}&7 -> me]: &r"
    # The prefix for sent messages. This is displayed to the sender. Use {{from}} and {{to}} for the message sender/receiver, {{fromDisplay}} or {{toDisplay}} for the display names.
    msg-sender-prefix="&7[me -> {{toDisplay}}&7]: &r"`

**Comment by FabioZumbi12** [comment]
I will not add more features to sponge version, just fixing errors, sorry.
