### ISSUE TITLE
[BUG] Constantly crashes

### ISSUE THREAD

**Issue by HeberonYT** [FabioZumbi12/UltimateChat#316]
**Describe the bug**
I made a new report because now the server is crashing after 5 minutes of starting it.
To play you don't need to do anything, just start the server and wait 5 minutes, no players, no messages, nothing.

**Screenshots and LOGs**
https://pastebin.com/raw/Gq2fc4yA

**Server and plugins versions (please complete the following information):**
 - Server: Paper-1.12.2-b1618
 - Plugin Version: UltimateChat-1.9.1-b286-Universal.jar
 - Java Version: Java 1.8

**Comment by FabioZumbi12** [comment]
Its seems is caused by Redis... try to disable

**Comment by HeberonYT** [comment]
> Parece que es causado por Redis ... intenta deshabilitar

Of course that solves it, but we need to use Redis for communication between multiple servers, due to the bungeecord option it is also bug and does not connect with sponge servers, so I prefer to use Redis.
I have updated some Paper 1.16.4 servers and they get the same error, it seems that a plugin update broke the Redis function. Attached is the server log Paper 1.16.4.
https://pastebin.com/raw/nfu7qbi7

**Comment by HeberonYT** [comment]
@FabioZumbi12 I did a lot of tests, I have identified that version 281 is the first that breaks the use of Redis, there are several changes made in that update, so maybe reviewing the changes will help to solve the problem in all subsequent versions.

**Comment by FabioZumbi12** [comment]
Thank you. Ill take a look!
