### ISSUE TITLE
[BUG] Messages don't send (New Nucleus 2.2.5)

### ISSUE THREAD

**Issue by yaroslav4167** [FabioZumbi12/UltimateChat#319]
I send a message, but it does not appear in the chat, and an error appears on the server.
Nucleus: 2.2.5
UltimateChat: 1.9.0-b259

Minecraft: 1.12.2
SpongeAPI: 7.3.0-6662937
Sponge: 1.12.2-7.3.1-SNAPSHOT
SpongeForge: 1.12.2-2838-7.3.1-RC4093
Minecraft Forge: 14.23.5.2847
JVM: 1.8.0_272/64-bit (Debian)
OS: Linux (5.9.0-2-amd64/amd64)

Console-log: [gist.github.com](https://gist.github.com/yaroslav4167/5fd8e0859cead372ad13d8ca73d668d1)

**Comment by liampearson96** [comment]
I am having the same issue.

**Comment by FabioZumbi12** [comment]
@yaroslav4167 @liampearson96 update to latest dev build. This is because Nucleus updates their APIs and the latest dev build of UChat its already compatible.
http://host.areaz12server.net.br:8081/job/UltimateChat/

**Comment by yaroslav4167** [comment]
I tested UltimateChat-1.9.1-b286 - All works fine!
Thank you!
