### ISSUE TITLE
[BUG] Hex colours dont work correctly in json messages

### ISSUE THREAD

**Issue by Soapiee** [FabioZumbi12/UltimateChat#321]
**Describe the bug**
Hex colours seem to invert themselves when used in placeholders json messages.
Hex colours dont seem to work at all when directly inserted into json messages.

**To Reproduce**
1. Install PrisonRanksX and UltimateChat
2. Set up ranks in the PrisonRanks. Change their display name to be formatted with a hex code. (https://i.imgur.com/mHgbCsm.png)
3. Set up a chat tag for PrisonRanksX. (https://i.imgur.com/97WFoCc.png)
4. Add the placeholders to your json message.
5. Talk in chat and put your mouse over the rank to view. (https://i.imgur.com/5eWCg8N.png)
6. NOTE: You can re-produce this without PrisonRanksX placeholders. Simply put in a hex code into any json message within your tag builder. (https://i.imgur.com/po3uQjm.png + https://i.imgur.com/EjDw7OM.png)

**Expected behavior**
The hex colours are meant to display their actual colour.

**Screenshots and LOGs**
Placeholder chat tag: https://i.imgur.com/97WFoCc.png
How its meant to look: https://i.imgur.com/D4Utq5H.png
How it actually looks: https://i.imgur.com/5eWCg8N.png

Plain chat tag: https://i.imgur.com/po3uQjm.png
Outcome: https://i.imgur.com/EjDw7OM.png

**Server and plugins versions (please complete the following information):**
 - Server: Paper version git-Paper-391
 - Plugin Version: UltimateChat-1.9.1-b287-Universal.jar
 - Java Version: Java 15

**Additional context**
None.

**Comment by FabioZumbi12** [comment]
As the color come from integrations, probably the PAPI its removing the hex color, or something like this. using directly on uchat config/chat, it works fine.
