### ISSUE TITLE
[BUG] 2 Chats 

### ISSUE THREAD

**Issue by Nayston** [FabioZumbi12/UltimateChat#322]
When i send a message always shows 2 messages instead of only 1. The chat one, and not the default.

**Expected behavior**
Should appear only the [world]... message, the default one should not appear. This way always appear 2 messages each time i send a message.

**Screenshots and LOGs**
https://gyazo.com/85db4488a233afd6444d17b5fee48d41

**Server and plugins versions (please complete the following information):**
 - Server: Spigot 1.12.2
 - Plugin Version:  UltimateChat-1.9.1-b287-Universal.jar
 - Java Version: Java 1.8

**Comment by Nayston** [comment]
https://gyazo.com/4a436b27ed6de818b8e64336ce5c2915

**Comment by FabioZumbi12** [comment]
Check for errors on console and for other chat plugins!
