### ISSUE TITLE
Problema com Hex color

### ISSUE THREAD

**Issue by 0D10** [FabioZumbi12/UltimateChat#323]
Estou com um problema com Hex color no chat e nas prefix
A prefix que eu uso no meu cargo e essa:
&#CCF769🔥&#FF9F32&l&ki&r&#CCF769&lOwner&#FF9F32&l&ki&r&#CCF769🔥&#FF9F32
Mais infelizmente ele não mostra as cores
O rank Owner fica branco 
(Vou anexar 2 prints: 1° E de como deveria ser 2° de como o plugin mostra)
![IMG_20210113_125818_857](https://user-images.githubusercontent.com/54384258/104476465-06f7db80-559f-11eb-90e2-f5ce98acd26e.png)
![IMG_20210113_125821_765](https://user-images.githubusercontent.com/54384258/104476489-0cedbc80-559f-11eb-9b11-68a981eed409.png)
Se quiser eu explico melhor no Discord: 0D10#9325

**Comment by FabioZumbi12** [comment]
O `&l` remove a formatação, poe ele antes do codigo da cor.
