### ISSUE TITLE
[Suggestion] DiscordSRV hook

### ISSUE THREAD

**Issue by Triangulum598** [FabioZumbi12/UltimateChat#328]
**Is your feature request related to a problem? Please describe.**
My server is bugging me about a JDA error, and I love the features this plugin offers, I just wish I could also have the features of DiscordSRV without it spamming me.

**Describe the solution you'd like**
I would like there to be some way for the plugin to hook into DiscordSRV to maybe use it's formatting, or have it automatically fill in the config with DiscordSRV's information? Maybe also let it use the webhooks it uses?

**Describe alternatives you've considered**
There aren't really any alternatives right now, other than just not using the features your plugin offers, which I would like to use those.

**Additional context**
https://paste.gg/p/anonymous/8af41dc5b65e4f41b0ad0188f02be8a8

**Comment by Folas1337** [comment]
In the currently latest version of UltimateChat it seems that DiscordSRV doesn't work anymore at all. Even in their Discord they have an auto reply that tells you that UltimateChat isn't supported.

According to the DiscordSRV debug logs, the chat event is canceled by UltimateChat and thus it's not being sent to Discord. If this could be addressed, it'd be wonderful!

**Comment by FabioZumbi12** [comment]
On latest builds, will work naturally with DSRV
