### ISSUE TITLE
[Sugestão] Local Amarelo Global Cinza [Tutorial] Simpleclan TAG colorida, formatada.

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/UltimateChat#329]
Fiz um vídeo tutorial para ajudar os novos donos de servidores a formatar a mensagem dos players nos canais Local [Amarelo] e Global [Cinza] e aproveitei para ensinar a deixar a tag do Simpleclan com a formatação colorida no chat também.
Vídeo Tutorial no meu canal de YT. https://youtu.be/OXEGbJud4N8

**Comment by FabioZumbi12** [comment]
Adicionei no readme seu video, vlw
