### ISSUE TITLE
Mute em minutos com as variáveis <player1>, <player2>, <tempo> e <motivo>.

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/UltimateChat#33]
player1: quem usou o comando.
player2: quem foi mutado.
tempo: em minutos
motivo: aceitar mais de 1 palavra exemplo: "regra3 e regra4"

   O uchat é um plugin de chat profissional, muito parecido com o LegendChat e eu conheci ele após atualizar o meu servidor para a versão 1.12 pois na epoca o LegendChat ainda não tinha sido atualizado, nesse meio tempo eu adorei o fato de que o vanish realmente funcionava perfeitamente, quando no LegendChat ele era bugado uma vez que qualquer player conseguia whispar alguém no vanish. No uchat o player recebia a mensagem de que o player não estava online. Porém o que me fez voltar para o LegendChat após sair uma atualização compatível com a 1.12, foi o fato de que ele possui o comando lc mute player tempo motivo que eu acho muito útil e importante para que os moderadores do meu servidor possam manter a paz e a ordem de acordo com as regras do servidor. Ou seja, preferi continuar com o problema do vanish não ser perfeito mas ter o mute com as variáveis.

Exemplo: Digamos que o player Miguel foi mutado pelo moderador Paulo.
Paulo seguindo as regras, mutou Miguel por spam.
A regra 3 que Paulo aplicou dizia que qualquer player que fizer spam seria mutado por 30 minutos.

Paulo então aplica o comando:

mute player tempo motivo
/mute miguel 30 "regra3" ou "spam"

screen: (como a mensagem aparece no chat global para os players verem)

Eu gosto de deixar esse tipo de informação bem visível para servir de exemplo para os outros players logo eu costumo aplicar 5 linhas de aviso em cada aplicação de regra, veja se você consegue entender, antes de mais nada o número de tracinhos para completar o chat que faz pular para a proxima linha é 53, caso ele não aceite a função \n para pular de linha.

Linha1: -----------------------------------------------------
Linha2: Jogador(a): player2
Linha3: Foi mutado por tempo minuto(s) pelo staff player1
linha3: Motivo: motivo
linha5: -----------------------------------------------------

**Comment by FabioZumbi12** [comment]
Adicionado, mas de forma mais simples do que a sugerida.
