### ISSUE TITLE
[BUG] Always stats with uppercase - long text ends always with a dot

### ISSUE THREAD

**Issue by LachCraft** [FabioZumbi12/UltimateChat#330]
When players write a text, the first character always starts with a capital. If there are several words, a dot follows. Not for short phrases.
To me, as an operator, this does not happen.

I have not found any corresponding settings in the configuration.

[Screenshot](https://user-images.githubusercontent.com/80180445/110224637-93f34d00-7edd-11eb-8a01-e16b1e5f58b5.png)

Current compilation: https://lachcraft.de/server/serverinfo/plugins

**Comment by FabioZumbi12** [comment]
OPs, have all permissions, bypassing the permissions for this configurations. You can check on permissions pages to negate that spacific permissions for you (as op).
