### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by cid998** [FabioZumbi12/UltimateChat#335]
**Descreva o bug**
O bug ocorre quando se é escrito específicas cores no padrão RGB, adicionado na versão 1.16, juntamente do prefixo '&', mostrando apenas o placeholder.

**Reproduzir**
Etapas para reproduzir o comportamento:
1. Escreva a cor '&#ff552f!', como exemplo
2. Aperte 'Enter'

**Comportamento esperado**
Esperava que a frase saísse colorida.

**Versões de servidor e plug-ins (preencha as seguintes informações):**
 - Servidor: Spigot 1.16.5
 - Versão do plug-in: UltimateChat-1.9.1-b265-Universal.jar
 - Versão do Java: Java 1.8 (Versão 8)

**Captura de tela**
[image](https://user-images.githubusercontent.com/69721004/113734774-feacc980-96d1-11eb-8559-92596e46e9e7.png)

**Comment by FabioZumbi12** [comment]
Não consegui reproduzir, aqui funcionou normal, porem precuisa das permissões de corer pra funcionar
