### ISSUE TITLE
@[username] mention does not seem to work [BUG] 

### ISSUE THREAD

**Issue by Pigna** [FabioZumbi12/UltimateChat#338]
**Describe the bug**
The usage of the mention feature does not seem to work.
When typing @[username] in the chat it does not change the text or give the player a sound.
No errors in the console

**Config**
(#)Use mentions on chat to change the player name color and play a sound on mention.
mention:
  enable: true
  color-template: '&e@{mentioned-player}{group-suffix}'
(#)May change if using old minecraft version.
  playsound: 'note_pling'
  hover-message: '&e{playername} mentioned you!'

**Screenshots and LOGs**
If applicable, add screenshots to help explain your problem. Upload your logs to https://gist.github.com/

**Server and plugins versions (please complete the following information):**
Plugin file:
UltimateChat-1.9.1-b265-Universal.jar

Paper file:
paper-1.16.5-642 (Also tested on main server 1.16.4)

Java Version: 
Java 1.7

Added screenshot of me trying to tag myself in an up to date server with newest UChat from spigot.
This is a test server, so I was not able to mention someone else. But the same thing is happening on my main server.

![Uchat_mention](https://user-images.githubusercontent.com/7887168/116985978-8126aa00-accd-11eb-892d-a0bb8ba38fe5.PNG)

**Comment by FabioZumbi12** [comment]
This will mention only other players. Try reseting the config and test again. Check for errors on console.
