### ISSUE TITLE
Emoji request [Suggestion] 

### ISSUE THREAD

**Issue by liampearson96** [FabioZumbi12/UltimateChat#339]
Hello, would it be possible to add the ability for Ultimate chat to stop processing emojis.
I have an addition mod which does this for me and ultimate chat messes up this function.

![image](https://user-images.githubusercontent.com/11605270/117812992-6ec2e800-b25a-11eb-8fe3-8f4ae61c204f.png)

**Comment by FabioZumbi12** [comment]
Uchat dont process, your mod do. Plugins dont have this habillity.
