### ISSUE TITLE
Change uchat.cant-ignore permission

### ISSUE THREAD

**Issue by Mike5357** [FabioZumbi12/UltimateChat#34]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Sponge

_Inform you RedProtect jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.0-b80-Universal

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  Suggestion

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Currently the permission node needs to be applied to the PLAYER groups and specifically targets individual players. Instead, it should work like other plugins such as Essentials used to where the permission node could simply be applied to the STAFF groups, and players would not be able to ignore anybody who was a part of that group.

**Comment by FabioZumbi12** [comment]
Using this way i dont need to check the permission for offline player, once i check only the permission for the sender, and not for the victim. If i set like other plugins, i need to check if that player has the permission, and suppsing that player is offline, the sender can ignore that player when offline. 

Yes, i can check permissions for offline players, but is not a good way for offline (cracked) server, and server performance too.
