### ISSUE TITLE
Cant seem to get Nucleus and Ultimatechat to work together

### ISSUE THREAD

**Issue by bgibbs992** [FabioZumbi12/UltimateChat#340]
Hello I tried to join your discord for support but it seems the invite link is expired.

I am currently running ultimatechat and it runs fine but as soon as I add Nucleus to the server I cant use global chat anymore, I am sure there must be something in the config I need to set up different but I cant find it anywhere, any help on what I need to do? Thanks!

**Comment by FabioZumbi12** [comment]
On the latest dev build already works: http://host.areaz12server.net.br:8081/job/UltimateChat/293/
