### ISSUE TITLE
Dynmap support

### ISSUE THREAD

**Issue by Sylensky** [FabioZumbi12/UltimateChat#341]
**Is your feature request related to a problem? Please describe.**
By default players are able to chat via webinterface of dynmap with the players on the server. Apparently players on the server can't communicate with the webinterface.

**Describe the solution you'd like**
An option in the channel configuration to be able to send the message also to dynmaps webinterface.

**Describe alternatives you've considered**
there is no alternative as far as i know.

**Comment by FabioZumbi12** [comment]
The latest dev versions already work with dynmap, download on http://host.areaz12server.net.br:8081/job/UltimateChat/
