### ISSUE TITLE
Crash on Sponge using build 1.8.0-b80

### ISSUE THREAD

**Issue by evernife** [FabioZumbi12/UltimateChat#35]
Plataform:  Sponge

Jar version:  UltimateChat-1.8.0-b80-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.10.2

Description: 
Servidor não liga 🗡 
 Erro : https://hastebin.com/ejigeguhip.swift

**Comment by FabioZumbi12** [comment]
Ajeitei isso na ultima build, baixa la e testa (pelomenos aqui, com SpongeVanilla na ultima versão funcionou).
