### ISSUE TITLE
[Suggestion] Add Support for Fabric

### ISSUE THREAD

**Issue by Gizmo0320** [FabioZumbi12/UltimateChat#358]
**Is your feature request related to a problem? Please describe.**
No problem currently. But once I expand servers I would like support of Fabric.

**Describe the solution you'd like**
Add support for Fabric.

**Describe alternatives you've considered**
Tried looking for other Chat plugins that support Fabric and Velocity along with SpongeForge and Paper and have had no luck.

**Additional context**

**Comment by Gizmo0320** [comment]
Any update on this?

**Comment by FabioZumbi12** [comment]
I am not supporting sponge anymore, only Bukkit servers (like Arclight), sorry :/
