### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by CripTiiC-Patrick** [FabioZumbi12/UltimateChat#359]
Desciption:
Basically i cant type in global and local chat but in admin chat.

Console Error:
https://gist.github.com/CripTiiC-Patrick/500f9bffac71f348b47fa1f4dbe0e157

SpongeForge 7.3.0 - UltimateChat 1.9.1-b256-Universal - Forge version: 14.23.5.2854

**Comment by CripTiiC-Patrick** [comment]
:(

**Comment by FabioZumbi12** [comment]
This is already fixed on latest dev builds: http://host.areaz12server.net.br:8081/job/UltimateChat/
