### ISSUE TITLE
SimpleClans Spy (Clan Chat and Ally Chat)

### ISSUE THREAD

**Issue by 538Michael** [FabioZumbi12/UltimateChat#36]
Add Clan Chat and Ally Chat to spy mode.

**Comment by FabioZumbi12** [comment]
I dont need to add this on uchat. You can give this permission to players you want to spy SimpleClans chats: **simpleclans.admin.all-seeing-eye**

Não preciso adicionar isso no uchat, vc pode dar a permissão pra quem vc quer q possa ver todos os chats do SimpleClans: **simpleclans.admin.all-seeing-eye**
