### ISSUE TITLE
[Suggestion] Velocity proxy support

### ISSUE THREAD

**Issue by ElTodoFull** [FabioZumbi12/UltimateChat#363]
**Is your feature request related to a problem? Please describe.**
Paper will drop development of waterfall, and bungee itself is not as secure or performant.

**Describe the solution you'd like**
Support Velocity, a modern and secure proxy software for minecraft networks.

**Describe alternatives you've considered**
Bungee nor waterfall aren't alternaives. Snap is a velocity plugin that allows to run bungee plugins, but it's less than ideal.

**Comment by FabioZumbi12** [comment]
Already support on latest builds
