### ISSUE TITLE
clan-tag "bug"

### ISSUE THREAD

**Issue by 538Michael** [FabioZumbi12/UltimateChat#37]
Percebi que se por algo no format da clan-tag, quando falar no chat, mesmo que não está em clan, aparece o que foi colocado lá. Séria uma boa não aparecer a clan-tag se não tivesse em algum clan.

**Comment by FabioZumbi12** [comment]
Isso eh pq o uchat identifica que a tag que vem do SimpleClans não esta vazia, ai o uchat não ignora. Tira qqr formato do clan-tag do simpleclans e poe os fortamos apenas no uchat, ai quando a tag vier vazia (pq n tem clan) o uchat vai ignorar.
