### ISSUE TITLE
[BUG] Pixelmon legendary announces

### ISSUE THREAD

**Issue by ghost** [FabioZumbi12/UltimateChat#371]
Hi, I'm using Sponge and getting the following error for pixelmon announcements. I will be grateful if you can help me.

https://paste2.org/U96nLJzd

Sponge 1.12.2
UltimateChat-1.9.0-259
Pixelmon 8.4.2

**Comment by FabioZumbi12** [comment]
I am not supporting sponge anymore, sorry :/
