### ISSUE TITLE
UCDiscord prevents plugin from loading

### ISSUE THREAD

**Issue by Cat121** [FabioZumbi12/UltimateChat#38]
Versions : 
UltimateChat-1.8.0-b82-Universal (same issue with 1.8.0-b82)
spongevanilla-1.11.2-6.1.0-BETA-19

Trace here : 
https://pastebin.com/w7r9Ncr1

**Comment by Cat121** [comment]
Just tried with UltimateChat-1.8.1-b84-Universal and I got the following : https://pastebin.com/wXuebCvh

**Comment by FabioZumbi12** [comment]
I tested here on SpongeVanilla and now seems working, can you confirm?

**Comment by Cat121** [comment]
Latest version UltimateChat-1.8.1-b85-Universal has no problem, thanks 😄
