### ISSUE TITLE
ThrownException during chat event

### ISSUE THREAD

**Issue by mcsnetworks** [FabioZumbi12/UltimateChat#39]
Hello,

I've found an incompatibility against the newest version of sponge:  
*spongeforge-1.12.2-2486-7.0.0-BETA-2665

Error:  https://gist.github.com/mcsnetworks/d1f69b03104be26e27ae5e6e3217a38b

I am using:  UltimateChat-1.8.1-b86-Universal.jar

Thank you,

**Comment by FabioZumbi12** [comment]
What version of UChat? (paste the jar name)

**Comment by mcsnetworks** [comment]
See above, UltimateChat-1.8.1-b86-Universal

**Comment by mcsnetworks** [comment]
Since Gabi just pushed changed to the cause tracker in SF, I figured that was the cause of this.

**Comment by FabioZumbi12** [comment]
Oh sorry. This is already fixed on latest jenkins build. Download from here: http://areaz12server.net.br:8080/job/UltimateChat/

**Comment by mcsnetworks** [comment]
Thank you, Wasn't sure since I couldn't see a commit to the cause system.
