### ISSUE TITLE
Erro na ordem dos caracteres de cor e formatação

### ISSUE THREAD

**Issue by evernife** [FabioZumbi12/UltimateChat#40]
```
Plataform:  Thermos
Jar version:  UltimateChat-1.8.3-b95-Universal
Minecraft version:  1.7.10
```
A formatação e aplicação de cores no chat esta equivocada.
Esta trocada

Por exemplo, se eu tenho uma custom tag que esta escrita:

`&e<message>` a coloração da mensagem sairá amarela!
`&e&l<message>` a coloração da mensagem sairá branca, contudo sairá em negrito!
`&l&e<message>` a coloração da mensagem sairá amarela e em negrito!

O mesmo vale para todos os outros simbolos de formatação ´&l&o&k...´

Resumindo, o plugin inverteu a ordem natural do minecraft, onde é : 

> "COR + FORMATAÇÂO + MENSAGEM"

para 

> "FORMATAÇÃO + COR + MENSAGEM"

Nota: isso é valido apenas para as custom-tags, se vc digitar no chat a formatação convencional `&e&lTeste` ele sairá como deveria, amarelo e em negrito!

**Comment by FabioZumbi12** [comment]
Parece q isso ta dando só com Thermos ou pelomenos até a versão 1.8. nas ultimas parece funcionar independente da ordem.

**Comment by evernife** [comment]
Vou me manter na `UltimateChat-Spigot-1.7.3-b574` então :D

**Comment by FabioZumbi12** [comment]
Mas testou as ultimas builds? Eu desinverti a ordem na lib, porem n fez diferença por ser json. Ai ja n sei se faz na 1.8

**Comment by evernife** [comment]
Testado, mesmo problema ainda :D 

![image](https://user-images.githubusercontent.com/11357801/31844057-3afe0f02-b5d5-11e7-8658-d6ffec0d20a0.png)

```
  ch-global:
    format: '&8&l(&a&l&oG&8&l) &r'
```
