### ISSUE TITLE
Sponge-API7 - Cast Double against INT exception

### ISSUE THREAD

**Issue by Dockter** [FabioZumbi12/UltimateChat#41]
Hello,
Error Generic:  **java.lang.ClassCastException: java.lang.Integer cannot be cast to java.lang.Double**
Error Gist:  https://gist.github.com/Dockter/d87caf72193c31654f1d1820d60eb43a

* Ultimate Chat: **UltimateChat-1.8.3-b95-Universal**
* Sponge: **spongeforge-1.12.2-2486-7.0.0-BETA-0** (Developer Build version == build against latest commit on 9/30/2017)
* Forge: **forge-1.12.2-14.23.0.2493-universal**
* Minecraft: **1.12.2**

**Comment by FabioZumbi12** [comment]
Fixed on latests builds.
