### ISSUE TITLE
Support relational placeholders in PlaceholderAPI 

### ISSUE THREAD

**Issue by MarkehMe** [FabioZumbi12/UltimateChat#42]
_Put if is the **Spigot** or **Sponge** version._  
**Plataform**:  1.12 (git-Spigot-7754231-94b0980)

_Inform you RedProtect jar name like **UltimateChat-Spigot-7.0.3.jar**._  
**Jar version**:  1.8.3

_Your server Minecraft version_  
**Minecraft version**:  1.12.1

_Issue or Suggestion?_  
**What you want**?:  Relational Placeholders

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
**Description**: Please add support for PlaceholderAPI relational placeholders! 

**See: https://www.spigotmc.org/resources/placeholderapi.6245/update?update=167267**

**Comment by PandaShadowz** [comment]
i'd love to see relational placeholders support too 👍

**Comment by FabioZumbi12** [comment]
Cool thing this PHAPI feature. I ll add. Join on our discord to get the latest dev build when i implement this..

**Comment by MarkehMe** [comment]
@FabioZumbi12 looking forward to it!

**Comment by FabioZumbi12** [comment]
Added on latest dev builds (#98 +) http://149.56.100.129:8080/job/UltimateChat/ (and tested by @MarkehMe ^^
