### ISSUE TITLE
Bungee Channel Help

### ISSUE THREAD

**Issue by PAINmatrix** [FabioZumbi12/UltimateChat#43]
Platform:  Spigot (CraftBukkit version git-Spigot-28463de-a2af8f0 (MC: 1.11.2) (Implementing API version 1.11.2-R0.1-SNAPSHOT))

Jar version:  UltimateChat-1.8.3-b97-Universal.jar

Minecraft version:  1.11.2

What you want?:  Help/Maybe issue

Description:  I have edited the Global channel to work with Bungeecord, but the channel builder and tags do not seem to be working fully. I may be missing something, but I'm really stumped. Here's what the chat looks like:

![2017-10-15_19 57 41](https://user-images.githubusercontent.com/13605587/31590743-ae0f6342-b1e3-11e7-86c7-2b30d6af4aa7.png)
Config: https://pastebin.com/uPZ2xQn1
Global Channel: https://pastebin.com/MujJeEGT

**Comment by FabioZumbi12** [comment]
Try the latest build. This version will send all tags to bungee proxys, not only some tags.
http://149.56.100.129:8080/job/UltimateChat/
