### ISSUE TITLE
Ubroad not working on Sponge

### ISSUE THREAD

**Issue by evernife** [FabioZumbi12/UltimateChat#44]
Plataform:  Sponge
Jar version:  **UltimateChat-1.8.4-b103-Universal.jar**
Minecraft version:  1.10.2

Comando `/ubroad` não funciona, simplesmente nem existe : D

![image](https://user-images.githubusercontent.com/11357801/31597055-18fb7768-b225-11e7-953d-ffb4ca4cb150.png)

Embora esteja mostrando ele no `/uchat ?`
![image](https://user-images.githubusercontent.com/11357801/31597067-29a0dfa4-b225-11e7-8b99-05e27174a544.png)

**Comment by FabioZumbi12** [comment]
Testou **/ubroadcast**? Talvez seja so o alias **ubroad** q n tenha.

**Comment by FabioZumbi12** [comment]
Por padrão não colokei na versão de sponge, só vc add no `config.confg`
