### ISSUE TITLE
Adding Distance Bypass Permission

### ISSUE THREAD

**Issue by herm1ne** [FabioZumbi12/UltimateChat#45]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.3-b106-Universal.jar

_Your server Minecraft version_  
Minecraft version:  Spigot 1.8.9 Latest 

_Issue or Suggestion?_  
What you want?:  Suggestion

Description:  
Adding the special permission for ignoring `distance` limit like `uchat.bypass-distance.<ChannelName>` would be just awesome :D  
This could be done with another chat plugin and needed for admin.  
Thanks for your consideration.

**Comment by FabioZumbi12** [comment]
Hi,
As admin, you can enable spy feature, where you already see all local channels and privates.

**Comment by herm1ne** [comment]
Thanks for reply.
I would like moderators to watch all chats (even distance limit enabled channel) but would not like them to watch Admin channel and private messages.  
Can I archive that?

**Comment by FabioZumbi12** [comment]
Maybe yes. I can add spy permissions by channel ;)

**Comment by herm1ne** [comment]
Oh that's gonna be super great.  
Thanks!

**Comment by FabioZumbi12** [comment]
I added the spy permissions. Join on our Discord if you encounter some isues or download from jenkins dev build.
