### ISSUE TITLE
Prefix doesn''t work with LuckPerms - Not Parsed Over

### ISSUE THREAD

**Issue by Auroratic** [FabioZumbi12/UltimateChat#48]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Sponge

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.3-b97-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.10.2

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:   Prefixes dont show over from LuckPerms (v3.2.60) 
Rank has weight of **100** - Ran the following command:
`/lp group owner addprefix 100 Owner` , so it should be showing but it isnt.

Can''t seem to get any prefix parsed over from LP to UltimateChat. Is there a workaround or can you get it resolved please?

Thanks and Best Regards

**Comment by FabioZumbi12** [comment]
Already helped on Dsicord!
