### ISSUE TITLE
UltimateChat + FactionsUUID errors

### ISSUE THREAD

**Issue by PandaShadowz** [FabioZumbi12/UltimateChat#49]
Plataform:  Spigot

Jar version:  UltimateChat-1.8.4-b111-Universal.jar

Minecraft version:  1.12.2

What you want?: Fix when you use FactionsUUID where  UltimateChat throw alot of errors

Description: https://hastebin.com/fizifazohu.go

**Comment by FabioZumbi12** [comment]
`java.lang.ClassNotFoundException: com.massivecraft.factions.RelationParticipator`

Theres some FactionsUUID class not found. Check if you is using the latest version of factionsUUID.

**Comment by PandaShadowz** [comment]
Ok , its a problem from FactionsUUID 
Tried with latest version and same errors , gonna try with another factions plugin
