### ISSUE TITLE
Factions

### ISSUE THREAD

**Issue by xrhyno2x** [FabioZumbi12/UltimateChat#5]
hey, this plugins is awesome

very easy to configure and setup, however i am wondering if there is anychance you could hook into factions chat api for there tags ?

https://www.massivecraft.com/factions

thankyou
-xrhyno2x

**Comment by FabioZumbi12** [comment]
I have added hook with PlaceHolderAPI, then you can use all this placeholders: https://www.spigotmc.org/wiki/placeholderapi-placeholders/

Will be available on next version.
