### ISSUE TITLE
2 Bugs

### ISSUE THREAD

**Issue by RaulH22** [FabioZumbi12/UltimateChat#50]
Plataform:  Spigot
Jar version:  UltimateChat-1.8.3-b97-Universal
Minecraft version:  1.12
What you want?:  Reportar um bug
Description:  
 Espero poder escrever em pt msm... 
 1- Quando coloco o formato na config "&6&l" o texto volta para branco ao invés de amarelo.
 2- O @hand Não esta funcianado bem. Imagem para mostrar:  https://i.imgur.com/mNB8aSt.png

Log: https://hastebin.com/oviboqalex.md

**Comment by FabioZumbi12** [comment]
Testa as versões dev: http://areaz12server.net.br:8080/job/UltimateChat/
