### ISSUE TITLE
Sugestão de mensagem que o player mutado recebe quando tem digitar em um canal.

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/UltimateChat#51]
Quando um player tentar digitar qualquer mensagem em um canal enquanto ele estiver mutado receber a mensagem de que ainda está mutado por tanto tempo.

Aproveitando para reportar 1 sistema q poderia ser melhorado. Quando o staff usa o comando /chat mute player - o player é mutado e recebe a mensagem q foi mutado em todos os canais, eu sei que vc decidiu usar o mesmo comando para desmutar, ou seja, para desmutar o staff usa o mesmo comando: /chat mute player - e o player recebe novamente a mesma mensagem de q foi mutado em todos os canais, mesmo ele tendo sido desmutado. Não sei se para melhorar esse sistema você teria que mudar o comando para chat unmute player ou se você consegue configurar para o player receber a mensagem de q foi desmutado sem precisar mudar o comando de mute para unmute.

**Comment by FabioZumbi12** [comment]
Adicionado em https://github.com/FabioZumbi12/UltimateChat/commit/f339db9ce848f9824472c69f42e8a2134d396620

Baixa do jenkins la no discord do UChat.

**Comment by comonier** [comment]
ficou perfeito, mas ficaria melhor se a mensagem reportada fosse mostrada em minutos e não em segundos, imagina que número grande vai aparecer quando o jogador for mutado por uma hora.
e tem uma pequena falha, quando o comando /chat mute player é usado pela segunda vez para desmutar o player , o player no caso recebe 2 mensagem, de que foi desmutado e de que foi mutado em todos os canais.
