### ISSUE TITLE
ultima build do uchat

### ISSUE THREAD

**Issue by comonier** [FabioZumbi12/UltimateChat#52]
1 - ficou quase perfeito parabens, porém quando o player tenta falar mutado, está mostrando  o tempo em segundos, seria melhor em minutos, imagina 1 player mutado 1 hora que numero grande apareceria.. exagero
   1.a - quando vc usa o comando chat tempmute 3 player   > aparece a msg 
vc mutou o jogador player em todos os canais por 3 minutos [em verde]
    1.b - e o player recebe a mensagem em vermelho [4] 
vc foi mutado em todos os canais por 3 minutos 

2 - quando o comando chat mute player é usado pela segunda vez para remover o mute o player ...
     2.a - você recebe a msg de que desmutou o player e mtodos os canais - em verde (Normal OK)
      2.b - o player recebe a mensagem de que foi mutado em todos os canais (apesar de ter sido desmutado) (corrigir)

**Comment by FabioZumbi12** [comment]
1a e b: Não entendi o problema... Pra vc aparece verde pois o player foi mutado com sucesso (aviso) e pro player aparece em vermelho (como um alerta). Não vejo erro ai.

2b. Entendi e vo arrumar.

**Comment by FabioZumbi12** [comment]
2b. Testei aqui aparece q ele foi desmutado normal, não q ele foi mutado denovo.
