### ISSUE TITLE
Bug with BungeeCord channels and Discord

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#54]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Bug with BungeeCord channels and Discord

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  When you are using the Discord feature on a BungeeCord channel (bungee: true), the messages are not send to the Discord channel.

**Comment by FabioZumbi12** [comment]
Download the latest version from dev buils on our discord to test if now bungee channel is sending messages to discord.

**Comment by n0dai** [comment]
Works fine, thank you!
