### ISSUE TITLE
Discord commands permissions

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#55]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version: 1.12.2  

_Issue or Suggestion?_  
What you want?:  Discord commands permissions

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Is this possible to add a permissions system when someone from Discord are using in-game commands? If not, is this possible to use per channels whitelist and blacklists commands, instead of global whitelist and blacklist? Thanks.

**Comment by FabioZumbi12** [comment]
You need to set permissions on your discord, since uchat doesn't have a link with discord users.
