### ISSUE TITLE
BungeeCord placeholders in languages files

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#56]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  BungeeCord placeholders in languages files

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Is this possible to add some BungeeCord placeholders in the languages files? For example, for the Discord status, I need to put "## players online on the server #####". I tried to use {bungee-id} placeholder, but it didn't worked. Thanks.

**Comment by FabioZumbi12** [comment]
You can just create a tag on config file, take the tag name and put on default-builder or bungee channel, then add what placeholder you want.

**Comment by n0dai** [comment]
Yes.
