### ISSUE TITLE
Adding MySQL support

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#57]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Adding MySQL support

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Is this possible to add MySQL support, exactly like Redis, in order to allow us to synchronize private messages, global broadcasts, and other messages across all connected servers with BungeeCord.

**Comment by FabioZumbi12** [comment]
You already can use Redis with UChat. I think is not needed to add other cross server message because the already available option you can use.

**Comment by n0dai** [comment]
Yes, but MySQL is the most common used storage. 90% of the premium plugins are using it, so it can be great for you, and your plugin, to support it.

**Comment by FabioZumbi12** [comment]
For storage yes, not for chat proxy.

**Comment by n0dai** [comment]
Do  you plan to allow us to use BungeeCord as a chat proxy, instead of your Redis?
