### ISSUE TITLE
Ingame Range Editor causing Error

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [FabioZumbi12/UltimateChat#59]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b116-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Changing the Range using the ingame channel editor command causes a configuration error. For example, setting a channel range to 35 ingame, sets the config to 35.0 which causes the error and stops that channel, and any further channels in alphabetical order from working. Changing this in the config to 35 and using /chat reload repairs the problem, making the channel work again.

Might be worth adjusting the code to remove the .0 from the range adjustment command as this would fix the problem.

**Comment by FabioZumbi12** [comment]
Try the latest dev build from http://areaz12server.net.br:8080/job/UltimateChat

**Comment by NiNjAiKoToBa** [comment]
Confirmed, latest version fixed bug!
