### ISSUE TITLE
Suggestion: Multiple Use /r and Remembering Last Channel

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [FabioZumbi12/UltimateChat#60]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b118-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  Suggestion

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  
If possible, please consider the following two features:
- The plugin remembering a players last chat channel, and attempting to put them back into it on a restart/relog (With permission check of course).
- The plugin having the ability for /r to be used more than once in a row. I have had a few complaints about /r only working for a single reply, then the player has to use /msg and recieve another message before /r will work again.

**Comment by FabioZumbi12** [comment]
Added on latest versions (dev versions)
