### ISSUE TITLE
 I'm having a problem with the tell it's duplicating the message it appears twice to whoever sends and who receives. How can I fix this is something I did wrong in setup?

### ISSUE THREAD

**Issue by gabyflor** [FabioZumbi12/UltimateChat#61]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  

_Your server Minecraft version_  
Minecraft version:  

_Issue or Suggestion?_  
What you want?:  

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:

**Comment by FabioZumbi12** [comment]
You need tu inform your server version, jar version and add a description on topic, and if issue, put the error log or prints on description (like the template says '-' )

I ll reopen qhen you fill up the template with this info.
