### ISSUE TITLE
Issue: Using Auto Complete for Nicks in channel commands.

### ISSUE THREAD

**Issue by 538Michael** [FabioZumbi12/UltimateChat#62]
Não sei se tinha antes, mas se não tiver, seria bom ter um auto complete para os Nicks quando usamos /g ou /l.

**Comment by aWitch-Doctor** [comment]
I also can't get usernames or nicknames to tab complete for build 120 on sponge vanilla api 7 build 356

**Comment by FabioZumbi12** [comment]
Fixed for spigot.
For sponge, seems to be a bug: https://github.com/SpongePowered/SpongeCommon/issues/1634
