### ISSUE TITLE
Servers stop sending messages to redis.

### ISSUE THREAD

**Issue by aWitch-Doctor** [FabioZumbi12/UltimateChat#63]
Plataform:  Sponge 1.12.2 api 7 beta build 356

Jar version:  UltimateChat-1.8.4-b120-Universal.jar

Minecraft version:  1.12.2

What you want?:  I have 6 servers all setup with cross server chat using redis. At first they are fine and everything works. After a little time, one by one, the servers stop transmitting chat to redis. They will still receive messages but wont transmit. 
 
Description:  This is the only error I have seen in the logs https://hastebin.com/kodacasisa.sql

**Comment by SergioMvl** [comment]
I also can confirm this issue on 1.7.10 (KCauldron/Thermos) / 1.10.2 (Sponge) servers

**Comment by FabioZumbi12** [comment]
Can you confirm if all of you is using redis with password? Can you count the time before servers disconnect? Seems be a redis/jedis timeouts.

**Comment by aWitch-Doctor** [comment]
I did both with and without a password. Happened both ways. Tried with default settings and then with some different setting in redis. Do you want the redis config?

**Comment by SergioMvl** [comment]
I did it without password. In my network redis installed on ubuntu 16.04, i also tried to connect UChat to the redis installed on CentOS using default setting - same issue. Aprox time 3-5 min. As already marked aWitch-Doctor, it still receive messages from the redis but not transmit.

**Comment by bakr0008** [comment]
We have set the redis time out to 31m seconds which is around 300+ days.
no password was set for the server and it is hosted locally on the same box as all of our mc servers.

**Comment by FabioZumbi12** [comment]
I dont know what can be. I'm not using Redis on my servers, only discord link. Btw seems is not related with UChat but redis cnofiguration. Did you tryd to look for something abour this on google to see is happening with other redis servers?

**Comment by FabioZumbi12** [comment]
I will completly remove redis and add bungee to sponge!
