### ISSUE TITLE
Links Not Working in Chat/Ignore Channels Not Working

### ISSUE THREAD

**Issue by NiNjAiKoToBa** [FabioZumbi12/UltimateChat#64]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.3-b97-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
What you want?:  Issue

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  
Hello, I am finding that /chat ignore is occasionally not working, and somethimes when it does, it stops a player being able to see a channel forever until a restart after they relog. Not sure why this is happening though

Also, i have found that links are not working when posted in any chat channel, by any user. Not Sure why though.

**Comment by NiNjAiKoToBa** [comment]
By links not working- I mean they are Un-Clickable.

**Comment by FabioZumbi12** [comment]
Tryed with latest ev build? http://areaz12server.net.br:8080/job/UltimateChat

**Comment by aWitch-Doctor** [comment]
I can confirm, I'm using build 120 and links are not clickable in sponge vanilla api7 build 356

**Comment by FabioZumbi12** [comment]
Test the latest build

**Comment by FabioZumbi12** [comment]
All added/fixed on latest version.
