### ISSUE TITLE
[1.12] Player cannot send message

### ISSUE THREAD

**Issue by SkyFire55** [FabioZumbi12/UltimateChat#66]
==> Click on PREVIEW tab!

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  

_Your server Minecraft version_  
Minecraft version:  1.12

_Issue or Suggestion?_  
Error when player try to send message

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  https://pastebin.com/pXYqZXF7

**Comment by SkyFire55** [comment]
Sorry:
spongeforge-1.12.2-2529-7.0.0-BETA-2742.jar
UltimateChat-1.8.4-b125-Universal.jar
Default config

**Comment by FabioZumbi12** [comment]
Sorry for late response, i'm very busy but ill check when i can.

**Comment by FabioZumbi12** [comment]
Use the latest version of API 7.0.0. SOme things changed on latests versions!

**Comment by SkyFire55** [comment]
Upgraded to the latest versions of SpongeForge and to UltimateChat 128b, and it helped. I don't see any errors. Issue can be closed.
