### ISSUE TITLE
Sponge channel lock not working

### ISSUE THREAD

**Issue by evernife** [FabioZumbi12/UltimateChat#67]
Plataform:  **SpongeForge-1.10.2-2477-5.2.0-BETA-2777.jar**
Jar version:  **UltimateChat-1.8.4-b125-Universal.jar**
Minecraft version:  **1.10.2**

Quando eu uso **/ch g**

![image](https://user-images.githubusercontent.com/11357801/34074470-cccc8d4e-e296-11e7-83c8-c74ec411aeaf.png)

ele continua travado no canal que eu estava.

E quando eu uso **/g** ele vai normal

![image](https://user-images.githubusercontent.com/11357801/34074474-f7f0ef74-e296-11e7-941d-e8bfbf5ac8ec.png)

**Comment by FabioZumbi12** [comment]
Vc deve ta tendo algum erro no console na hora de verificar permissões, ve ai pf pq a ultima versão ta funcionando pra todos usuários q tão usando ela.

**Comment by SkyFire55** [comment]
There is no any errors in console, at least with turned off debug mode. I have the same problem at the same version.

**Comment by evernife** [comment]
Nada no console aqui T.T
Mesmo com debug-mod ativado

Sad World
Vamo espera pra vê se aparece mais uma alma azarada que nem eu com o mesmo problema  :D 
![image](https://user-images.githubusercontent.com/11357801/34082454-d26fe778-e345-11e7-940d-e58ec634151e.png)

**Comment by FabioZumbi12** [comment]
Achei o problema / i found the problem!

Download the latest version from our discord!
