### ISSUE TITLE
Global BungeeCord mute

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#68]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Global BungeeCord mute

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Adding a global mute in all servers connected to the BungeeCord proxy.

**Comment by FabioZumbi12** [comment]
I don't have in mind add this.

**Comment by n0dai** [comment]
Alright, maybe in the future?
Because this is really useful for networks.

**Comment by n0dai** [comment]
What's about it? It's one of the most needed feature in every chat plugin, lol.

**Comment by FabioZumbi12** [comment]
They never asked for it and I never heard of it. I ll not add for now.
