### ISSUE TITLE
Faction Tag

### ISSUE THREAD

**Issue by cybernerd17** [FabioZumbi12/UltimateChat#7]
Sei q ja fiz um ticket mas eu aqui dnv kkkk
preciso colocar as tags de factions no chat mas n encontro nenhuma forma

o meu esta assim 
http://prntscr.com/cdh8xy

@OFF-TOPIC
Esse plugin é muito bom, melhor plugin de chat que ja testei ate hoje, parabens

**Comment by FabioZumbi12** [comment]
Que bom que curtiu ^^

Se vc tiver usando a ultima versão, usa os placeholders do PlaceHolderAPI: https://www.spigotmc.org/wiki/placeholderapi-placeholders/

Pode por como ta na página do PlaceHolderAPI com os %% que funciona certinho.

Qualquer duvida: https://discord.gg/YWmGSHs
Abraço.

**Comment by cybernerd17** [comment]
Voltei, desculpe n especificar 100% meu problema estava atrazado !
meu problema é que eu crio uma facção mas n mostra o Prefixo dela no chat
http://prntscr.com/cdi18e

Mais uma vez, desculpa n especificar o problema no primeiro ticket

**Comment by FabioZumbi12** [comment]
E na config vc colocou as tags do placeholder? E no placeholder vc precisa ativar uma opção pra habilitar a tag...

Posta sua config aki na seção de factions igual vc fez antes.

**Comment by cybernerd17** [comment]
# Arquivo de configuração do Uchat
# Autor: FabioZumbi12
# Recomando usar o Notepad++ para editar este arquivo!
# ------------------------------------------------------------------------
# Tags é onde voce vai personalizar os textos pra aparecer no chat, ao passar o mouse ou clicar na tag.
# Para adicionar uma tag, copie uma existente e troque o nome para um de sua escolha.
# Depois de criar e personalizar a tag, adicione ela em 'general > default-tag-builder'.
# ------------------------------------------------------------------------
# Replacers disponíveis:
# uChat:
#  - {default-format-full}: Use esta tag para ver todas tags de plugins que estão usando o formato padrão do bukkit. Normalmente usado por plugins de 'mito' e tags temporárias. Caso queira apenas usar uma delas elas são separadas por espaços e abaixo vc pode usar apenas uma de cada.
#  - {default-format-0}: Use esta tag para usar apenas uma tag das descritas acima. O numero é a posição dela entre os espaços;
#  - {world}: O mundo de quem enviou a mensagem;
#  - {message}: Mensagem enviada;
#  - {playername}: O nome de quem enviou;
#  - {nickname}: O nick de quem enviou. Se o nick não foi definido irá mostrar o nome;
#  - {ch-name}: Nome do canal;
#  - {ch-alias}: Atalho do canal;
#  - {ch-color}: Cor do canal;
# Vault:
#  - {group-prefix}: Prefixo do grupo do player;
#  - {group-suffix}: Sufixo do grupo do player;
#  - {balance}: Dinheiro do player;
#  - {prim-group}: Tag do grupo primário;
#  - {player-groups}: Lista todos grupos que o player faz parte;
# Simpleclans:
#  - {clan-tag}: Tag do Clan sem cores;
#  - {clan-ctag}: Tag do Clan com cores;
#  - {clan-name}: Nome do Clan;
#  - {clan-kdr}: KDR do player do Clan;
#  - {clan-isleader}: O player é lider;
#  - {clan-rank}: Rank do player no Clan;
#  - {clan-totalkdr}: Clan KDR (não do player);
# Marry Plugins:
#  - {marry-partner}: Mostra o nome do(a) parceiro(a);
#  - {marry-prefix}: Pega a tag de prefixo, normalmente o coração;
#  - {marry-suffix}: Pega a tag de sufixo, ou simbolo masculino do Marriage Reloaded;
# BungeeCord:
# Para bungee cord tem 2 tags novas. Algumas das outras tags ainda funcionam, com excessão da username, de grupo e de outros plugins.
# - {world}: Mundo de quem enviou;
# - {server}: O Server de quem enviou, igual o especificado em config.yml do BungeeCord;

config-version: 1.1
debug-messages: false
language: PT-BR
mention:
  enable: true
  prefix-color: '&e@'
  playsound: note_pling
  hover-message: '&e{playername} mencionou você!'
general:
  custom-tags: [faction-tag]
  console-tag: '&6 {console}&3'
  remove-from-chat: '[]'
  channel-cmd-aliases: channel,ch
  hover-events: true
  default-channel: g
  spy-format: '&7&o[Spy] {output}'
  default-tag-builder: faction-tag,marry-tag,ch-tags,clan-tag,group-prefix,nickname,group-suffix,message
tell:
  cmd-aliases: tell,t,w,m,msg,private,priv,r
  prefix: '&6[&c{playername} &6-> &c{receivername}&6]: '
  format: '{message}'
  hover-messages: []
bungee:
  prefix: '&6[&c{playername} &6-> &c{receivername}&6]: '
  format: '{message}'
  hover-messages: []
broadcast:
  enable: true
  on-hover: 'hover:'
  on-click: 'click:'
  aliases: ubroadcast,ubroad,uannounce,usay,uaction,all,anunciar,todos
tags:
  group-prefix:
    format: '{group-prefix}&r'
    click-cmd: ''
    hover-messages:
    - '&bRank: &e{prim-group}'
  playername:
    format: '{playername}'
    click-cmd: tpa {playername}
    hover-messages:
    - '&7Click to send teleport request'
  nickname:
    format: '{nickname}'
    click-cmd: 'tpa {playername}'
    hover-messages:
    - '&6Realname: {playername}'
    - '&6Clique para mandar um pedido de teleporte'
  group-suffix:
    format: '&r{group-suffix}: '
    click-cmd: ''
    hover-messages: []
  world:
    format: '&7[{world}]&r'
    click-cmd: ''
    hover-messages:
    - '&7Sent from world {world}'
  message:
    format: '{message}'
    click-cmd: ''
    hover-messages: []
  ch-tags:
    format: '{ch-color}[{ch-alias}]&r'
    click-cmd: ch {ch-alias}
    hover-messages:
    - '&3Channel name: {ch-color}{ch-name}'
    - '&bClick to go to this channel!'
  clan-tag:
    format: '{clan-ctag}'
    click-cmd: clan search {playername}
    hover-messages:
    - '&bClan Tag: &7{clan-tag}'
    - '&bClan Name: &7{clan-name}'
    - '&bClan KDR: &7{clan-totalkdr}'
    - '&bPlayer KDR: &7{clan-kdr}'
    - '&bPlayer Rank: &7{clan-rank}'
    - '&bIs Leader: &7{clan-isleader}'
    - '&3Click for more info about this player'
  marry-tag:
    format: '{marry-prefix}{marry-suffix}'
    click-cmd: ''
    hover-messages:
    - '&cMarried with {marry-partner}'
  admin-chat:
    format: '&b[&r{playername}&b] '
    click-cmd: ''
    hover-messages: []
  bungee:
    format: '&7[{world}]{ch-color}[Bungee-{server}] {playername}: &7'
    click-cmd: ''
    hover-messages:
    - '{ch-color}Sent from server -{server}-'
  faction-tag:
    format: '{%factions-chat-tag%}'
    click-cmd: 'f f {factions-name}'
    hover-messages:
    - '&bClique para info da facção'

**Comment by FabioZumbi12** [comment]
Nn mano. Olhando na lista de placeholders do PLaceHolderAPI tem assim:

Por exemplo:

%factions_faction%
%factions_title%
%factions_role%

Usa um desses e não precisa por {}. Usar {} só para as tag do UChat.

**Comment by cybernerd17** [comment]
testei todos eles e n funcionou :(

**Comment by FabioZumbi12** [comment]
Vc tem que instalar um hook no placeholderapi. Usa /placeholderapi help e vai aparecer. Assim que vc fizer isso e instalar o tal placeholder pro Factions já vai aparecer.

**Comment by cybernerd17** [comment]
Funcionou vlw msm pela ajuda e desculpa dar tanto trabalho kkk n entendo mt de placeholder api

e sugestão! coloca sistema de automessage com hoverclick ficaria epico XD
