### ISSUE TITLE
/tell NICKNAME

### ISSUE THREAD

**Issue by Dockter** [FabioZumbi12/UltimateChat#70]
Hello,

Using Sponge version b128,

Is it possible to do a /tell "nicknamehere"

Using Nucleus to provide Nickname support.

Please advise.

**Comment by FabioZumbi12** [comment]
I think is not really necessary, since we can hover the nickname and get the realname, and as performance, i need to loop into online players to get the player by nick instead playername.

**Comment by Dockter** [comment]
Down size of this is that people will need to figure out what that persons real name is.  I guess I can fork this and add it to our own version :/

**Comment by FabioZumbi12** [comment]
As an optional feature i think i dont need to add for now or as a long time, but you can add if you need it in a shorter time.
