### ISSUE TITLE
BungeeCord global spy

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#71]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  BungeeCord global spy

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Adding the possibility to spy across all servers connected to BungeeCord.

**Comment by FabioZumbi12** [comment]
Maybe i add this, but not for now.

**Comment by n0dai** [comment]
Alright thanks.

**Comment by n0dai** [comment]
What's about it?
