### ISSUE TITLE
BungeeCord mentions

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#72]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  BungeeCord mentions

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Sync the mentions in BungeeCord channels.

**Comment by FabioZumbi12** [comment]
Cant, because bungee coord/redis uses a template json to send between servers, in other words, an unmodifiable json message sent from sender server.
