### ISSUE TITLE
MySQL chats logs

### ISSUE THREAD

**Issue by n0dai** [FabioZumbi12/UltimateChat#73]
_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b115-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  MySQL chats logs

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  Log all chats in MySQL, with the channel name, the time, etc.

**Comment by FabioZumbi12** [comment]
I ll not add. Mysql is a low peformance log system, and is not really needed/wanted feature.
