### ISSUE TITLE
I broke the plugin more then 1 way.

### ISSUE THREAD

**Issue by DutchUser** [FabioZumbi12/UltimateChat#77]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  **Spigot: 
(This server is running CraftBukkit version git-Spigot-7754231-94b0980 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT))**

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  **UltimateChat-1.8.4-b130-Universal.jar**

_Your server Minecraft version_  
Minecraft version:  **1.12.2**

_Issue or Suggestion?_  
What you want?:  **Issue**

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  

I got this error when i tried it first https://pastebin.com/ThNgxw1J **Now its dont give any error.**

INFO:
I cannot remove the channel. I tried it as:
1, Use /uchat delchannel TeamChat2, Where it the  say it have been removed. When i re-do the command is also say that its gone. Also the file is gone. But, After a reload its back, (https://postimg.org/image/74hakygkd/4d375017/)

2, Close the server, Remove the file, But teh its again back when i started the server,

**Subnote:** I cannot edit ANY uchat file. It will awlays return to what it was before i edited it. This also when i only change something like ut to lr.

**This happen when you add a file instead using the ingame channel creater.**

additional files

Config: https://pastebin.com/0sJTjU5X
Channel that wont go away: https://pastebin.com/fd0WJy1S

More needed? Just ask me.

**Comment by DutchUser** [comment]
**UPDATE** I think i also broke my console. Because.. well so down below.

1: Removed the plugin. 
2: Closed the server.
3: Started the server. (whitout the plugin)
4: Closed the server.
5: Removed the channel.
6: Started the server. (Still whitout plugin)
7: Closed the server.
8: re-added the plugin.
9: Started the server.
10: BAM, The file is still back. Its really like magic.

So i cannot remove the channel in ANY way so far.

**Comment by FabioZumbi12** [comment]
This is not magic, its witchcraft

**Comment by DutchUser** [comment]
I updated to the lastest dev build. And now it seem to handle it difr. First it only fixed by stopping the server and removing. But now its much more ez. See explain.

Fix: Remove the file with captical letters. 

Cause: When you create a file by hand and not by the ingame thing. **and** use TAB letters. The plugin cannot use or read it and will create a new fille with the same stats. **But** i dont know why you cannot edit anything in it. (or why it let the plugin get stupid) **But by remove the one with TAB letters its fixed.**
