### ISSUE TITLE
MC to Discord error

### ISSUE THREAD

**Issue by Noobcrafteryt** [FabioZumbi12/UltimateChat#78]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  Universal Chat 1.8.3 b97

_Your server Minecraft version_  
Minecraft version:  1.11.2

_Issue or Suggestion?_  
What you want?:  
You can send discord to server but not server to discord. Get the listed error in Hastebin link.
_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  https://hastebin.com/inejuxoyif.vbs

**Comment by FabioZumbi12** [comment]
Download the latest versions of uchat and JDA from here http://areaz12server.net.br:8080/job/UltimateChat
This is already fixed.

**Comment by Noobcrafteryt** [comment]
Awesome. Thank you for the quick reply. Love the plugin, first time user having ran servers for about 2 years now. Definitely in my must have plugins for any future servers! Take care.
