### ISSUE TITLE
Issue with Chat Spy as well as a suggestion for it

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#79]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b132

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Both

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  
**Isue**: I, for example, have an Admin role and a Senior Admin role. Admins are given access to /chat spy. If I wanted to create a Senior Admin chat channel, Admins with /chat spy enabled would still be able to see the chat through the spy.
**Suggestion(s):** So I have two suggestions in mind:
1) Admins can't see messages from /chat spy from channels they don't have permissions for. So for example, if they don't have uchat.channel.SeniorAdmin they can't get spy messages for that channel.
2) Add something like a uchat.chat.spy.exempt permission. Players with this permission would be exempt from being spied on.

**Comment by FabioZumbi12** [comment]
This can help you https://github.com/FabioZumbi12/UltimateChat/wiki/(2)-Permissions#chat-spy

**Comment by Coaley** [comment]
That worked! Thanks very much.
