### ISSUE TITLE
Erro

### ISSUE THREAD

**Issue by TheMito** [FabioZumbi12/UltimateChat#8]
Olá, para mim está dando o seguinte erro:
http://hastebin.com/tapepiwata.vbs
Versão: UltimateChat-1.6.6-b442
Desculpe-me qualquer coisa.
Att

**Comment by FabioZumbi12** [comment]
Olá.

Vc deve atualizar ou usar outra versão do SimpleClans. Ele que esta dando esse erro no uChat, quando tenta pegar a tag do clan! Tira o plugin SimpleClans q n vai dar isso.
