### ISSUE TITLE
Automatically enable Spy

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#80]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b132

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Suggestion

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  After every server start, /chat spy has to be re-enabled. I was wondering if there could be an option for it to be constantly enabled. Like a permission that enables it automatically once a specific player logs on?

**Comment by FabioZumbi12** [comment]
Added on latest dev build http://areaz12server.net.br:8080/job/UltimateChat
