### ISSUE TITLE
1.12 Cannot read config

### ISSUE THREAD

**Issue by SkyFire55** [FabioZumbi12/UltimateChat#81]
UltimateChat-1.8.4-b137-Universal.jar
spongeforge-1.12.2-2555-7.0.0-BETA-2797.jar

Problem: plugin ignores config file. Language - the only string i have changed after generating fresh config
And it ignores config not everywhere - some tags works. Tell block modifying doesn't have any effect too.

![h1](https://user-images.githubusercontent.com/22179405/34750871-829eb77e-f5ba-11e7-9d8c-e53771224da3.PNG)
![h2](https://user-images.githubusercontent.com/22179405/34750879-881b2bce-f5ba-11e7-9078-ac007b8e3a45.PNG)

**Comment by FabioZumbi12** [comment]
Solved on https://github.com/FabioZumbi12/UltimateChat/commit/64b1342dfd453c02d256be49ba31a0e92ec898bf
