### ISSUE TITLE
 java.lang.NoClassDefFoundError: org/spongepowered/api/data/meta/ItemEnchantment

### ISSUE THREAD

**Issue by DiCO3** [FabioZumbi12/UltimateChat#82]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  
UltimateChat-1.8.3-b97-Universal.jar
_Your server Minecraft version_  
Minecraft version:  
1.12.2-forge2555
_Issue or Suggestion?_  
What you want?:  
fix the issues(?)
_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  
there're few noclassdef errors in the Java code which can't be executed with SpongeAPI 7.1.0
and also some typos of value in protection.conf and config.conf like "lenght" and "vannila", which I've considered those are preserved words since I haven't checked the source code yet.
just to be mentioned :>
<img width="1680" alt="screen shot 2018-01-11 at 00 57 42" src="https://user-images.githubusercontent.com/13800794/34785176-5632cdd6-f66b-11e7-8dea-d1b81156dc66.png">

**Comment by FabioZumbi12** [comment]
Did you really tryed the latest version?

> Before open an issue, checkout this steps:
- If you are running the plugin at first time, try to run again to see if the problem persists.
- Check if your build is the latest on our Jenkins. Click Here: http://areaz12server.net.br:8080/job/UltimateChat
- Its important to you include the plugin jar name, because version and build info.

This is already fixed on latest dev build ;)

**Comment by DiCO3** [comment]
yeah I noticed from your Jenkins server :3, I will add them into my server then
great work btw !
