### ISSUE TITLE
{ch-color} in language file

### ISSUE THREAD

**Issue by Coaley** [FabioZumbi12/UltimateChat#83]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b137

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  Suggestion

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  So in the language file, we are able to change the message they get when players change channels. So for example, I set mine to "&7You have changed your channel to &c{channel}&7." I was wondering if we could use {ch-color} in this file so we could make it something like this "&7You have changed your channel to {ch-color}{channel}&7." So if we would have a Moderator chat that is gold, it would be "You have changed your channel to &6{channel}&7." and so on.

**Comment by FabioZumbi12** [comment]
Allowed on latest dev version http://areaz12server.net.br:8080/job/UltimateChat
ref https://github.com/FabioZumbi12/UltimateChat/commit/0e002992b4956f247b85c7a35f4dcae4e600fe45
