### ISSUE TITLE
Channel Changing Issue.

### ISSUE THREAD

**Issue by Ash10744** [FabioZumbi12/UltimateChat#84]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Platform: Spigot  

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-18.4-b139-Universal.Jar

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  I have had a recent issue when a player changes channel it doesn't send the message through:
https://i.imgur.com/PL7yOgJ.png

Also on top of this, I was curious to see if there was a way to /leave {channel} then rejoin it at will so we can block out other channels then rejoin them as we wish.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  [No errors]

**Comment by FabioZumbi12** [comment]
Yeah, this a know issue and sometimes theres a delay. Its only on Spigot, not on Sponge, then, i cant fix this for now, but i am looking for.

I dont know what you mean with /leave channel!

**Comment by Shiunin** [comment]
I have the same issue and am on Sponge using UltimateChat-1.8.8-b196-Universal.jar

**Comment by FabioZumbi12** [comment]
Still happening?

**Comment by Shiunin** [comment]
Yes it is, sometimes very rarely people are even trapped in channels until restart.

**Comment by FabioZumbi12** [comment]
May be solved on next dev builds.

**Comment by Ash10744** [comment]
I'd like to reopen this since the error is still occurring.
https://cdn.discordapp.com/attachments/562038894594490368/756850816601817088/2020-09-15_12.36.24-1.png
