### ISSUE TITLE
Adjust Channel Topic

### ISSUE THREAD

**Issue by rouing** [FabioZumbi12/UltimateChat#86]
Idea Taken from MagiBridge:

Change the Topic of the Channel to the following:

Players %players%/%maxplayer% | TPS: %tps% | %serverip/url%

Add a config to tell how many minutes until next update.

**Comment by FabioZumbi12** [comment]
Maybe no. UChat bridge is a basic integration. MB its a dedicated integration and its 100% compatible with uchat. If using Spigot, you can use DSRV for a more complete integration.

Thanks for the suggestion.
