### ISSUE TITLE
Problema nas cores

### ISSUE THREAD

**Issue by MarkPVA** [FabioZumbi12/UltimateChat#87]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b138-Universal

_Your server Minecraft version_  
Minecraft version:  1.8.8

_Issue or Suggestion?_  
What you want?:  Problema

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  As cores estao com problemas, so estao pegando as cores do começo eo &r nao resolve
https://i.imgur.com/9M1X4hz.png
https://i.imgur.com/oDD0DQ6.png

**Comment by FabioZumbi12** [comment]
Resolvido no discord.
