### ISSUE TITLE
Chat Input Error

### ISSUE THREAD

**Issue by sakurazilla** [FabioZumbi12/UltimateChat#88]
_Put if is the **Spigot** or **Sponge** version._  
Platform:  Sponge

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  1.8.4 b138

_Your server Minecraft version_  
Minecraft version:  1.12.2 

_Issue or Suggestion?_  
What you want?:  Help with fixing a console error

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  I get this error in console when i send a message, any way to fix? https://gyazo.com/41648e488e64077859cd546aa3d0c343

**Comment by FabioZumbi12** [comment]
Try the latest dev build 141 : http://areaz12server.net.br:8080/job/UltimateChat/
And please, report on discord if worked (or here)
https://discord.gg/YWmGSHs
