### ISSUE TITLE
API Request

### ISSUE THREAD

**Issue by cnaude** [FabioZumbi12/UltimateChat#9]
Please add an API method for sending messages to channels. Something like this:
```java
uChatAPI.sendRawMessage(channelName, message);
```

**Comment by Androkai** [comment]
I'm also searching for a possibility to send a message to all players which listen to a channel. Any possibility to do this?

**Comment by klennan** [comment]
PurpleIRC recently added uChat compatibility. Hope this helps:
https://github.com/cnaude/PurpleIRC-spigot/commit/fba98f6aee4beefbf066216ec218fabf9eda8b21

**Comment by Scarsz** [comment]
@cnaude @Androkai https://github.com/FabioZumbi12/UltimateChat/commit/e11eb903f1bacc0909c12148396728c158ac8a5d

**Comment by Androkai** [comment]
Seems like it's only possible to send a message with a player as sender but what if I have no player as sender object?

**Comment by FabioZumbi12** [comment]
Try to add `Bukkit.getServer().getConsoleSender()` (if i remeber)

But i have not fully tested this implementation.

**Comment by Androkai** [comment]
This is not possible.

**Comment by Scarsz** [comment]
@cnaude https://github.com/FabioZumbi12/UltimateChat/commit/009f2c210776ddd4c32c9675b4d93ef1851dd9c7

**Comment by FabioZumbi12** [comment]
@Androkai add raw message is not possible because Fanciful is in the end of process chat messages.

Btw, you can make a loop into players or get the player channel and check if filter the players by channel and then send a raw message using Bukkit.
