### ISSUE TITLE
[Suggestion]How about to add the alias to display the corresponding value？

### ISSUE THREAD

**Issue by Tollainmear** [FabioZumbi12/UltimateChat#90]
I have use Uchat for long time, And it was a nice plugin! Thank for keep developing Uchat!
I have a suggestion for Uchat about message localization，why don‘t you add a function that make tags has there corresponding value?
 just like key-value, the World tag always as 'world' in English but it was '主世界（dgoo shi jye）' in chinese;
the channel tag always as 'local' but it was '本地（ben dee）' or '附近（foo jin）'in chinese；
the group tag always as 'Default' but '默认（moa ren）' in chinese.
And this is a internationalization problem for every different language speaker right?
IF there were some problem with this suggestion,  I'll sorry about to bother you, Anyway, thanks for keep develping Uchat~
Love U!

**Comment by Tollainmear** [comment]
I mean 'key-value' like 'tag-foo', such as '{world} = "世界"' or sth?

**Comment by Tollainmear** [comment]
Did you remember the file world.yml in multiverse-core?
Admins could customize the world display name in chat element with ['alias'](https://github.com/Multiverse/Multiverse-Core/wiki/World-properties#alias).
I mean if we could customize the tag's display "name"(just like edit world alias in Multiverse) in Uchat, that will be brilliant!

**Comment by FabioZumbi12** [comment]
Now i know what you mean haha
I ll add this!

**Comment by Tollainmear** [comment]
Another one! How about 'Mention All'?
if admin type 'mention all''s placeholder， the message will be replaced with the player name which received?
such as"Hey @ALL how is your ping？”, then player Foo will received " Hey @Foo how is your ping?", and the same as player Bar shown "Hey @Bar how is your ping?"
Sometimes, you know, players will ignore the message when they think admin may not ask them.

**Comment by bar** [comment]
@Tollainmear please don't use my handle to document your code :p

**Comment by Tollainmear** [comment]
Wooool, My bad :P

**Comment by Tollainmear** [comment]
@FabioZumbi12 Thx for add world alias!
How about edit group aliases to rename group name to other name?
In another way, if specific string was replaced by specific string, I mean, aliases should not restricted to world aliases, could also use with group or something others, that will be great!

**Comment by FabioZumbi12** [comment]
Need to be restricted because the recplacer need to know what to replace and from what string to other string, but a replacer for group is easy to add too ;)

**Comment by FabioZumbi12** [comment]
Added groupnames replacers to latest dev builds.
