### ISSUE TITLE
French translation problem

### ISSUE THREAD

**Issue by killianperez** [FabioZumbi12/UltimateChat#92]
**Platform**: Sponge
**Jar version**: UltimateChat-1.8.4-b141-Universal
**Minecraft version**: 1.11.2
**Description**:  The langFR.properties is not the French language but Spanish... So, I fully re-translated the plugin into French (France)
**Link**:  https://hastebin.com/wowisocozi.tex

**Comment by FabioZumbi12** [comment]
added, thanks.
