### ISSUE TITLE
Sugestão UltimateChat

### ISSUE THREAD

**Issue by zKingOfKill** [FabioZumbi12/UltimateChat#95]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.4-b141-Universal.jar

_Your server Minecraft version_  
Minecraft version:  1.8

_Issue or Suggestion?_  
What you want?:  Suggestion

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  

**1° sugestão:**
Adicionar compatibilidade dos emojis do MinEmojis com o chat do plugin Uchat no discord!

**2° Sugestão:**

fazer com que o placeholdersAPI funcione no hover das tags, pois seria muito bom pra adicionar informações importantes sobre o jogador!

**Comment by FabioZumbi12** [comment]
O 2 ja funciona. Enviar emojis pro dicord do MineEmojis depende do MineEmojis, que provavelmente n vai dar p adicionar isso.
