### ISSUE TITLE
JDA jar causing UltimateChat to automatically disable. 

### ISSUE THREAD

**Issue by Aeneas1022** [FabioZumbi12/UltimateChat#98]
==> Click on PREVIEW tab!

### Before open an issue, checkout this steps:
* If you are running the plugin at first time, try to run again to see if the problem persists.
* Check if your build is the latest on our Jenkins. Click Here: <http://areaz12server.net.br:8080/job/UltimateChat>
* Its important to you include the plugin jar name, because version and build info.

_Put if is the **Spigot** or **Sponge** version._  
Plataform:  Spigot

_Inform your UltimateChat jar name like **UltimateChat-Spigot-7.0.3.jar**._  
Jar version:  UltimateChat-1.8.6-b157-Universal.jar & UltimateChat-JDA.jar (build 157)

_Your server Minecraft version_  
Minecraft version:  1.12.2

_Issue or Suggestion?_  
What you want?:  The issue is that the most recent UltimateChat-JDA.jar is causing my uchat to stop working completely. I've triple checked all tokens, channel ids, and that I had the most recent versions from Jenkins. When I remove JDA, the plugin works fine.

_Descript your issue/Suggestion. If issue, use the site [hastebin.com](https://hastebin.com/) to put your error or console logs._  
Description:  https://hastebin.com/leranoxuka.vbs

**Comment by FabioZumbi12** [comment]
You is using an outdated version of ultimatechat, or didnt updated JDA to latest version.

**Comment by Aeneas1022** [comment]
they're both at the most recent version... unless the UltimateChat on the spigot page is outdated and the same with the Jenkins build for the JDA.

**Comment by Aeneas1022** [comment]
went ahead and got the most recent version from the Jenkins site for both Uchat and the JDA. Updated my original post to reflect that. The problem is still occurring.

**Comment by FabioZumbi12** [comment]
On latest builds this is fixed!
