### ISSUE TITLE
Enchancement:  Chat channels splitting

### ISSUE THREAD

**Issue by Foxgreat** [FabioZumbi12/UltimateChat#99]
How about to re-code the default chat window to splitted channels?

For example we have 5 channels, global, local, guild, trade, dimensional. Every channel by default on one frame. But each channel can be separated to new frame. Also you can create sub-channels where shows game logs and personal messages. 

Good example - chat in world of warcraft, or tabby chat on liteloader mods as in minecraft example. Or may be integration with this tabby chat. What you say?

**Comment by FabioZumbi12** [comment]
This is possible only on mods. In a plugin using the default minecraft will too many expensive for client.
